/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.ProveedorDAO;
import Pojos.Compras;
import Pojos.Proveedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JDBuscarProveedor extends javax.swing.JDialog {

    /**
     * Creates new form JDBuscarProveedor
     */
    ProveedorDAO daoproveedor = new ProveedorDAO();
    JIFIngresoProducto IngresoProd;
    
    Mayusculas mayus= new Mayusculas();
  
    String op;
    JIFIngresoProdPendiente frmprodpend;
    List<Proveedor> listprov = new ArrayList<>();
    Proveedor proveedor= new Proveedor();
    public JDBuscarProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listprov=daoproveedor.mostrarproveedor(jtabla);
        this.setLocationRelativeTo(null);
    }
    public JDBuscarProveedor(java.awt.Frame parent, boolean modal,JIFIngresoProducto IngresoProd) {
        super(parent, modal);
        initComponents();
        listprov=daoproveedor.mostrarproveedor(jtabla);
        this.IngresoProd=IngresoProd;
        this.setLocationRelativeTo(null);
      
        op="INGRESOPROD";
    }
     public JDBuscarProveedor(java.awt.Frame parent, boolean modal,JIFIngresoProdPendiente frmprodpend) {
        super(parent, modal);
        initComponents();
        listprov=daoproveedor.mostrarproveedor(jtabla);
        this.setLocationRelativeTo(null);
        this.frmprodpend=frmprodpend;
        op= "PENDIENTES";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfrazonsocial = new javax.swing.JTextField();
        jbtnaceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUSCAR PROVEEDOR");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtfrazonsocial.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfrazonsocial.setText("NOMBRE O RAZON SOCIAL");
        jtfrazonsocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfrazonsocialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfrazonsocialFocusLost(evt);
            }
        });
        jtfrazonsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfrazonsocialActionPerformed(evt);
            }
        });
        jtfrazonsocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfrazonsocialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfrazonsocialKeyTyped(evt);
            }
        });

        jbtnaceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept2.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });

        jtabla.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtfrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnaceptar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnaceptar))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfrazonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfrazonsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfrazonsocialActionPerformed

    private void jtfrazonsocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrazonsocialFocusGained
        // TODO add your handling code here:
        if (jtfrazonsocial.getText().equals("NOMBRE O RAZON SOCIAL")){
            jtfrazonsocial.setText("");
        
        }
    }//GEN-LAST:event_jtfrazonsocialFocusGained

    private void jtfrazonsocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrazonsocialFocusLost
        // TODO add your handling code here:
         if (jtfrazonsocial.getText().equals("")){
            jtfrazonsocial.setText("NOMBRE O RAZON SOCIAL");
        
        }
    }//GEN-LAST:event_jtfrazonsocialFocusLost

    private void jtfrazonsocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrazonsocialKeyReleased
        // TODO add your handling code here:
        String razonS= jtfrazonsocial.getText().trim().toUpperCase();
        listprov=daoproveedor.busquedasensitivaproveedor("NOMBRE", razonS,jtabla);
    }//GEN-LAST:event_jtfrazonsocialKeyReleased

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        int index= jtabla.getSelectedRow();
        if(index>=0){
             proveedor = listprov.get(index);
            if(op.equals("INGRESOPROD")){
                
        //        proveedor.setIdproveedor(id);
        //        proveedor.setNombrerazons(razonS);
        //        proveedor.setRut(rut);
              
                IngresoProd.setproveedor(proveedor);
                IngresoProd.validaguardar();
                this.dispose(); 
            }
            if(op.equals("PENDIENTES")){
             
               proveedor.setIdproveedor(proveedor.getIdproveedor());
               proveedor.setNombrerazons(proveedor.getNombrerazons());
               proveedor.setRut(proveedor.getRut());
               frmprodpend.setproveedor(proveedor);
               this.dispose(); 
            }
        
        
        
        } else {
        
            JOptionPane.showMessageDialog(null, "SELECCIONE UN PROVEEDOR");
        }
       
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfrazonsocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrazonsocialKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfrazonsocial);
    }//GEN-LAST:event_jtfrazonsocialKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBuscarProveedor dialog = new JDBuscarProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfrazonsocial;
    // End of variables declaration//GEN-END:variables
}
