/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.FamiliaDAO;
import Pojos.Familia;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JDBuscarFamilia extends javax.swing.JDialog {

    /**
     * Creates new form JDBuscarFamilia
     */
    FamiliaDAO daofamilia= new FamiliaDAO();
    Familia familia ;
    JIProductos productos;
    Mayusculas mayus = new Mayusculas ();
    List<Familia> listfamili;
    public JDBuscarFamilia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        this.setLocationRelativeTo(null);
//        listfamili=daofamilia.mostrarfamilia(jtablafamilia);
//         setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent evt) {
//                close();
//            }
//        });
    }
     public JDBuscarFamilia(java.awt.Frame parent, boolean modal,JIProductos productos) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
       mostrar();
//        this.familia=familia;
        this.productos=productos;
//         setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosing(java.awt.event.WindowEvent evt) {
//                close();
//            }
//        });
    }
     public void mostrar(){
     Runnable runnable = new Runnable() {

         @Override
         public void run() {
//             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             jlblimagencarga.setVisible(true);
             jlblletracarga.setVisible(true);
              listfamili=daofamilia.mostrarfamilia(jtablafamilia);
              jlblimagencarga.setVisible(false);
             jlblletracarga.setVisible(false);
             
         }
     };
     Thread T = new Thread(runnable);
     T.start();
     
     }
     public synchronized void sensitiva(){
         jlblimagencarga.setVisible(true);
         jlblletracarga.setVisible(true);
         String descrip=jtfdescripcion.getText().toUpperCase();
         listfamili=daofamilia.busquedasensitivafamilia("DESCRIPCION",descrip,jtablafamilia);
         jlblimagencarga.setVisible(false);
         jlblletracarga.setVisible(false);
     }
   
//    public void close(){
//        jbtnaceptar.doClick();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblimagencarga = new javax.swing.JLabel();
        jlblletracarga = new javax.swing.JLabel();
        jtfdescripcion = new javax.swing.JTextField();
        jbtnaceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablafamilia = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblimagencarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        jPanel1.add(jlblimagencarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 190, 240));

        jlblletracarga.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblletracarga.setText("Cargando Registros ...");
        jPanel1.add(jlblletracarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jtfdescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfdescripcion.setText("DESCRIPCION");
        jtfdescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusLost(evt);
            }
        });
        jtfdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdescripcionActionPerformed(evt);
            }
        });
        jtfdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyTyped(evt);
            }
        });
        jPanel1.add(jtfdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 309, -1));

        jbtnaceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept2.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 68, -1, -1));

        jtablafamilia.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtablafamilia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtablafamilia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtablafamilia.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtablafamilia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, 781, 378));

        jPanel7.setBackground(new java.awt.Color(220, 151, 96));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BUSCAR FAMILIA DE PRODUCTOS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 822, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfdescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusGained
        // TODO add your handling code here:
        if (jtfdescripcion.getText().equals("DESCRIPCION")){
            jtfdescripcion.setText("");
        }
    }//GEN-LAST:event_jtfdescripcionFocusGained

    private void jtfdescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusLost
        // TODO add your handling code here:
         if (jtfdescripcion.getText().equals("")){
            jtfdescripcion.setText("DESCRIPCION");
        }
    }//GEN-LAST:event_jtfdescripcionFocusLost

    private void jtfdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyReleased
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtfdescripcionKeyReleased

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        int index= jtablafamilia.getSelectedRow();
        if (index >=0 ){
        familia = listfamili.get(index);
        productos.setfamilia(familia);
        productos.validaguardar();
        this.dispose();
        }
        
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayus(jtfdescripcion);
    }//GEN-LAST:event_jtfdescripcionKeyTyped

    private void jtfdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdescripcionActionPerformed
        // TODO add your handling code here:
       Runnable runnable = new Runnable() {

         @Override
         public void run() {
//             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            sensitiva();
             
         }
     };
     Thread T = new Thread(runnable);
     T.start();
    }//GEN-LAST:event_jtfdescripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBuscarFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBuscarFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBuscarFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBuscarFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBuscarFamilia dialog = new JDBuscarFamilia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JLabel jlblimagencarga;
    private javax.swing.JLabel jlblletracarga;
    private javax.swing.JTable jtablafamilia;
    private javax.swing.JTextField jtfdescripcion;
    // End of variables declaration//GEN-END:variables
}
