/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.ProveedorDAO;
import Pojos.Proveedor;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JDBuscarProveedor extends javax.swing.JDialog {

    /**
     * Creates new form JDBuscarProveedor
     */
    ProveedorDAO daoproveedor = new ProveedorDAO();
    JIFIngresoProducto IngresoProd;
    
    Mayusculas mayus= new Mayusculas();
  
    String op;
    JIFIngresoProdPendiente frmprodpend;
    List<Proveedor> listprov = new ArrayList<>();
    Proveedor proveedor= new Proveedor();
    public JDBuscarProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mostrar();
        this.setLocationRelativeTo(null);
    }
    public JDBuscarProveedor(java.awt.Frame parent, boolean modal,JIFIngresoProducto IngresoProd) {
        super(parent, modal);
        initComponents();
        mostrar();
        this.IngresoProd=IngresoProd;
        this.setLocationRelativeTo(null);
      
        op="INGRESOPROD";
        jtfrazonsocial.requestFocus();
    }
     public JDBuscarProveedor(java.awt.Frame parent, boolean modal,JIFIngresoProdPendiente frmprodpend) {
        super(parent, modal);
        initComponents();
        mostrar();
        this.setLocationRelativeTo(null);
        this.frmprodpend=frmprodpend;
        op= "PENDIENTES";
        jtfrazonsocial.requestFocus();
    }
     
     public void mostrar(){
     Runnable runnable = new Runnable() {

         @Override
         public void run() {
//             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             jlblimagencarga.setVisible(true);
             jlblletracarga.setVisible(true);
             listprov=daoproveedor.mostrarproveedor(jtabla);
              jlblimagencarga.setVisible(false);
             jlblletracarga.setVisible(false);
             
         }
     };
     Thread T = new Thread(runnable);
     T.start();
     }
     
      public synchronized void sensitiva(){
         jlblimagencarga.setVisible(true);
         jlblletracarga.setVisible(true);
         String razonS= jtfrazonsocial.getText().trim().toUpperCase();
        listprov=daoproveedor.busquedasensitivaproveedor("NOMBRE", razonS,jtabla);
         jlblimagencarga.setVisible(false);
         jlblletracarga.setVisible(false);
         if(listprov.size()>0)
         {
             jtabla.requestFocus();
         }
     }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblimagencarga = new javax.swing.JLabel();
        jlblletracarga = new javax.swing.JLabel();
        jtfrazonsocial = new javax.swing.JTextField();
        jbtnaceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblimagencarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        jPanel1.add(jlblimagencarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 190, 240));

        jlblletracarga.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblletracarga.setText("Cargando Registros ...");
        jPanel1.add(jlblletracarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jtfrazonsocial.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfrazonsocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfrazonsocialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfrazonsocialFocusLost(evt);
            }
        });
        jtfrazonsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfrazonsocialActionPerformed(evt);
            }
        });
        jtfrazonsocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfrazonsocialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfrazonsocialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfrazonsocialKeyTyped(evt);
            }
        });
        jPanel1.add(jtfrazonsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 70, 620, -1));

        jbtnaceptar.setBackground(new java.awt.Color(77, 161, 227));
        jbtnaceptar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbtnaceptar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.setBorderPainted(false);
        jbtnaceptar.setContentAreaFilled(false);
        jbtnaceptar.setOpaque(true);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 130, 40));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla.getTableHeader().setReorderingAllowed(false);
        jtabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtablaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 890, 432));

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setText("BUSCAR PROVEEDOR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        jLabel1.setText("Señor(es):");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfrazonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfrazonsocialActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfrazonsocialActionPerformed

    private void jtfrazonsocialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrazonsocialFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfrazonsocialFocusGained

    private void jtfrazonsocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrazonsocialFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfrazonsocialFocusLost

    private void jtfrazonsocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrazonsocialKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfrazonsocialKeyReleased

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        int index= jtabla.getSelectedRow();
        if(index>=0){
             proveedor = listprov.get(index);
            if(op.equals("INGRESOPROD")){
                
        //        proveedor.setIdproveedor(id);
        //        proveedor.setNombrerazons(razonS);
        //        proveedor.setRut(rut);
              
                IngresoProd.setproveedor(proveedor);
                IngresoProd.validaguardar();
                this.dispose(); 
            }
//            if(op.equals("PENDIENTES")){
//             
//               proveedor.setIdproveedor(proveedor.getIdproveedor());
//               proveedor.setNombrerazons(proveedor.getNombrerazons());
//               proveedor.setRut(proveedor.getRut());
//               frmprodpend.setproveedor(proveedor);
//               this.dispose(); 
//            }
        
        
        
        } else {
        
            JOptionPane.showMessageDialog(null, "Seleccione Item","",JOptionPane.ERROR_MESSAGE);
        }
       
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfrazonsocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrazonsocialKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayus(jtfrazonsocial);
    }//GEN-LAST:event_jtfrazonsocialKeyTyped

    private void jtfrazonsocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrazonsocialKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Runnable runnable = new Runnable() {

            @Override
            public void run() {
   //             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
               sensitiva();

            }
            };
            Thread T = new Thread(runnable);
            T.start();
        
        
        }
            
    }//GEN-LAST:event_jtfrazonsocialKeyPressed

    private void jtablaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jbtnaceptar.doClick();
        
        }
    }//GEN-LAST:event_jtablaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDBuscarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDBuscarProveedor dialog = new JDBuscarProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JLabel jlblimagencarga;
    private javax.swing.JLabel jlblletracarga;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfrazonsocial;
    // End of variables declaration//GEN-END:variables
}
