/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Pojos.Ventas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 *
 * @author HERNAN
 */
public class JDConsultarEstadoSunat extends javax.swing.JDialog {

    /**
     * Creates new form JDConsultarEstadoSunat
     */
    Ventas v;
    public JDConsultarEstadoSunat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
      public JDConsultarEstadoSunat(java.awt.Frame parent, boolean modal,Ventas v) {
        super(parent, modal);
        initComponents();
        this.v=v;
        
        jlbldocumento.setText(v.getSerie()+" - "+v.getNumero());
        if(v.isAceptadasunat()==true){
            jlblaceptada.setText("Aceptada por sunat: Si");
        }else {
            jlblaceptada.setText("Aceptada por sunat: No");
        }
        jlbldescripcion.setText("Descripción: "+v.getSunatdescrip());
        
        this.setLocationRelativeTo(null);
          addEscapeListener(this);
    }
      
          public static void addEscapeListener(final JDialog dialog) {
    ActionListener escListener = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            dialog.setVisible(false);
        }
    };

    dialog.getRootPane().registerKeyboardAction(escListener,
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            JComponent.WHEN_IN_FOCUSED_WINDOW);

}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblaceptada = new javax.swing.JLabel();
        jlbldescripcion = new javax.swing.JLabel();
        jlbldocumento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta SUNAT");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(560, 124));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblaceptada.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlblaceptada.setForeground(new java.awt.Color(34, 75, 139));
        jlblaceptada.setText("jLabel1");
        getContentPane().add(jlblaceptada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 530, -1));

        jlbldescripcion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlbldescripcion.setForeground(new java.awt.Color(34, 75, 139));
        jlbldescripcion.setText("jLabel1");
        getContentPane().add(jlbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 520, -1));

        jlbldocumento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlbldocumento.setForeground(new java.awt.Color(34, 75, 139));
        jlbldocumento.setText("jLabel1");
        getContentPane().add(jlbldocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDConsultarEstadoSunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDConsultarEstadoSunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDConsultarEstadoSunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDConsultarEstadoSunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDConsultarEstadoSunat dialog = new JDConsultarEstadoSunat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblaceptada;
    private javax.swing.JLabel jlbldescripcion;
    private javax.swing.JLabel jlbldocumento;
    // End of variables declaration//GEN-END:variables
}
