/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.ReparacionDAO;
import Pojos.DetalleCaja;
import Pojos.Reparacion;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author info2017
 */
public class JDCobrarCaja extends javax.swing.JDialog {

    /**
     * Creates new form JDCobrarCaja
     */
    JIFCaja frmcaja;
    DetalleCaja detcaja = new DetalleCaja();
    String estado;
    double abonoo;
    Reparacion reparacion  = new Reparacion();
    ReparacionDAO daoreparacion = new ReparacionDAO();
    double total;
    NumberFormat nf = NumberFormat.getInstance();
    public JDCobrarCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
   
    public JDCobrarCaja(java.awt.Frame parent, boolean modal,JIFCaja frmcaja,Reparacion reparacion, double total) {
        super(parent, modal);
        initComponents();
        abonoo=0;
        this.frmcaja= frmcaja;
//        Double total=frmcaja.calculatotal();
        this.total=total;
        jlbltotal.setText(nf.format(total));
        jbtncobrar.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.reparacion=reparacion;
        if(reparacion.getIdreparacion()==0){
            jtfabono.setEnabled(false);
            
        }
    }
    public boolean calculavuelto(){
        Double vuelto=0.0,pago=0.0,saldo=0.0;
        boolean valida=false;
        System.out.println("tecla");
        try {
            double abono= Double.parseDouble(jtfabono.getValue().toString());
            
//            double total = Double.parseDouble(jlbltotal.getValue().toString());
            pago = Double.parseDouble(jtfpago.getText());
            detcaja.setPagocon(pago);
            if( total >= abono && pago>=abono){
                saldo= total-abono;
                vuelto= pago- abono;
                abonoo=abono;
                jlblvuelto.setValue(vuelto);
                jlblsaldo.setValue(saldo);
                jlblmensaje.setText("");
                jbtncobrar.setEnabled(true);
                valida=true;
                if(saldo==0){
                    estado="COBRADO";
                }else {
                    estado="DEBE";
                }
            }else {
                jlblmensaje.setText("VERIFIQUE LAS CANTIDADES INGRESADAS");
                jbtncobrar.setEnabled(false);
                jlblvuelto.setText("");
        }
            
        } catch (NullPointerException e) {
            jlblmensaje.setText("");
            jbtncobrar.setEnabled(false);
            valida=false;
            jlblvuelto.setText("");
        }
        
    return valida;
    }
    public void calculavueltoventa(){
        Double vuelto=0.0;
        try {
//             Double total = Double.parseDouble(jlbltotal.getValue().toString());
        Double pago = Double.parseDouble(jtfpago.getText());
        if(pago >= total){
        vuelto= pago - total;
        jlblvuelto.setValue(vuelto);
        jbtncobrar.setEnabled(true);
        jlblmensaje.setText("");
        estado="COBRADO";
        }else {
            jlblmensaje.setText("EL PAGO DEBE DE SER MAYOR O IGUAL AL TOTAL");
            jbtncobrar.setEnabled(false);
        }
            
        } catch (NullPointerException e) {
            jlblmensaje.setText("EL PAGO DEBE DE SER MAYOR O IGUAL AL TOTAL");
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtncobrar = new javax.swing.JButton();
        jlblmensaje = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfabono = new javax.swing.JFormattedTextField();
        jlblsaldo = new javax.swing.JFormattedTextField();
        jlblvuelto = new javax.swing.JFormattedTextField();
        jlbltotal = new javax.swing.JLabel();
        jtfpago = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COBRO CAJA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL A PAGAR:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ABONO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 60, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("VUELTO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 20));

        jbtncobrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtncobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cashier_icon-icons.64X64.png"))); // NOI18N
        jbtncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncobrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jlblmensaje.setForeground(new java.awt.Color(255, 51, 51));
        jlblmensaje.setText("---");
        jPanel1.add(jlblmensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 120, 10, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("SALDO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 140, 50, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PAGO CON:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 100, 70, 20));

        jtfabono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfabono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfabonoKeyReleased(evt);
            }
        });
        jPanel1.add(jtfabono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));

        jlblsaldo.setEditable(false);
        jlblsaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jPanel1.add(jlblsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, -1));

        jlblvuelto.setEditable(false);
        jlblvuelto.setForeground(new java.awt.Color(255, 51, 51));
        jlblvuelto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jlblvuelto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jlblvuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 270, 40));

        jlbltotal.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlbltotal.setForeground(new java.awt.Color(255, 51, 51));
        jlbltotal.setText("* * *");
        jPanel1.add(jlbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 250, 30));

        jtfpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfpagoActionPerformed(evt);
            }
        });
        jtfpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfpagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfpagoKeyTyped(evt);
            }
        });
        jPanel1.add(jtfpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 230, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncobrarActionPerformed
        // TODO add your handling code here:
         frmcaja.cobrar(detcaja,estado,abonoo,reparacion);
         System.out.println("repara"+reparacion.getIdreparacion());
         this.setVisible(false);
         if(reparacion.getIdreparacion()!=0){
             daoreparacion.imprimir(reparacion.getIdreparacion());
         
         }
         frmcaja.newcobro();
         this.dispose();
    }//GEN-LAST:event_jbtncobrarActionPerformed

    private void jtfabonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfabonoKeyReleased
        // TODO add your handling code here:
        if(reparacion.getIdreparacion()==0){
            calculavueltoventa();
        
        }else {
            calculavuelto();
        }
            
    }//GEN-LAST:event_jtfabonoKeyReleased

    private void jtfpagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfpagoKeyReleased
        // TODO add your handling code here:
         if(reparacion.getIdreparacion()==0){
            calculavueltoventa();
        
        }else {
            calculavuelto();
        }
    }//GEN-LAST:event_jtfpagoKeyReleased

    private void jtfpagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfpagoKeyTyped
        // TODO add your handling code here:
                 char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) 
        && (caracter != KeyEvent.VK_BACK_SPACE)
        && (caracter != '-' || jtfpago.getText().contains("-")) ) {
            evt.consume();
}
    }//GEN-LAST:event_jtfpagoKeyTyped

    private void jtfpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfpagoActionPerformed
        // TODO add your handling code here:
        jbtncobrar.doClick();
    }//GEN-LAST:event_jtfpagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCobrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCobrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCobrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCobrarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCobrarCaja dialog = new JDCobrarCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtncobrar;
    private javax.swing.JLabel jlblmensaje;
    private javax.swing.JFormattedTextField jlblsaldo;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JFormattedTextField jlblvuelto;
    private javax.swing.JFormattedTextField jtfabono;
    private javax.swing.JTextField jtfpago;
    // End of variables declaration//GEN-END:variables
}
