/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.ReparacionDAO;
import Pojos.Reparacion;
import Pojos.UsuarioSingleton;

/**
 *
 * @author info2017
 */
public class JDDiagnosticoReparacion extends javax.swing.JDialog {

    /**
     * Creates new form JDDiagnosticoReparacion
     */
    Reparacion reparacion;
    ReparacionDAO daoreparacion =new ReparacionDAO();
    JIFReparacionesPendientes frmreparacionespen;
    UsuarioSingleton usersingleton= UsuarioSingleton.getintancia();
    Mayusculas mayus= new Mayusculas();
    public JDDiagnosticoReparacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }
    public JDDiagnosticoReparacion(java.awt.Frame parent, boolean modal,Reparacion reparacion,
            JIFReparacionesPendientes frmreparaciones) {
        super(parent, modal);
        initComponents();
        jlblmodelo.setText("Cod. "+"r"+reparacion.getIdreparacion());
        this.reparacion= reparacion;
        this.frmreparacionespen= frmreparaciones;
         jbtnaceptar.setEnabled(false);
         this.setLocationRelativeTo(null);
    }
    public void valida(){
        if(!jtadiagnostico.getText().equals("")){
            jbtnaceptar.setEnabled(true);
        }else {
            jbtnaceptar.setEnabled(false);
        }
            
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtadiagnostico = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jrbtnno = new javax.swing.JRadioButton();
        jrbtnsi = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jlblmodelo = new javax.swing.JLabel();
        jbtnaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtadiagnostico.setColumns(20);
        jtadiagnostico.setRows(5);
        jtadiagnostico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtadiagnosticoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtadiagnosticoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtadiagnostico);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 460, 220));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reparado?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12))); // NOI18N

        jrbtnno.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbtnno);
        jrbtnno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnno.setText("No");

        jrbtnsi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbtnsi);
        jrbtnsi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnsi.setSelected(true);
        jrbtnsi.setText("Si");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jrbtnsi)
                .addGap(18, 18, 18)
                .addComponent(jrbtnno)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnno)
                    .addComponent(jrbtnsi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("Diagnostico:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jlblmodelo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlblmodelo.setForeground(new java.awt.Color(255, 51, 51));
        jlblmodelo.setText("jLabel2");
        jPanel1.add(jlblmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 390, -1));

        jbtnaceptar.setBackground(new java.awt.Color(77, 161, 227));
        jbtnaceptar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbtnaceptar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.setBorderPainted(false);
        jbtnaceptar.setContentAreaFilled(false);
        jbtnaceptar.setDefaultCapable(false);
        jbtnaceptar.setOpaque(true);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        String estado = "";
        if(jrbtnsi.isSelected()== true){
            estado= "REPARADO";
        }else { if(jrbtnno.isSelected()==true){
            estado="NO REPARADO";
        }
        
        }
        reparacion.setEstado(estado);
        reparacion.setDiagnostico(jtadiagnostico.getText().trim().toUpperCase());       
        daoreparacion.editar(reparacion);
        frmreparacionespen.buscar();
        this.dispose();
        
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtadiagnosticoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtadiagnosticoKeyReleased
        // TODO add your handling code here:
         valida();
    }//GEN-LAST:event_jtadiagnosticoKeyReleased

    private void jtadiagnosticoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtadiagnosticoKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayusTA(jtadiagnostico);
    }//GEN-LAST:event_jtadiagnosticoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDDiagnosticoReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDDiagnosticoReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDDiagnosticoReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDDiagnosticoReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDDiagnosticoReparacion dialog = new JDDiagnosticoReparacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JLabel jlblmodelo;
    private javax.swing.JRadioButton jrbtnno;
    private javax.swing.JRadioButton jrbtnsi;
    private javax.swing.JTextArea jtadiagnostico;
    // End of variables declaration//GEN-END:variables
}
