/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.DetalleComprasDAO;
import Pojos.DetalleCompras;

/**
 *
 * @author info2017
 */
public class JDEditarEliminarDetalleCompra extends javax.swing.JDialog {

    /**
     * Creates new form JDEditarEliminarDetalleCompra
     */
    DetalleCompras detcompra = new DetalleCompras();
    JIFIngresoProducto frmingresoprod;
    DetalleComprasDAO daodetc= new DetalleComprasDAO();
    public JDEditarEliminarDetalleCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public JDEditarEliminarDetalleCompra(java.awt.Frame parent, boolean modal,DetalleCompras detcompra,String cod
    ,String descrip, JIFIngresoProducto frmingresoprod) {
        super(parent, modal);
        initComponents();
        this.detcompra= detcompra;
        jlblcodigo.setText(cod);
        jlbldescripcion.setText(descrip);
                
        jtfcantllego.setValue(detcompra.getCantidad());
        jtfcantacord.setValue(detcompra.getCantidadacord());
        jtfprecio.setValue(detcompra.getPrecio());
        jtfimporte.setValue(Double.parseDouble(jtfcantllego.getValue().toString())
                *Double.parseDouble(jtfprecio.getValue().toString()));
        this.frmingresoprod= frmingresoprod;
        this.setLocationRelativeTo(null);
    }
    public void importe(){
        try {
            
            double cant=Double.parseDouble(jtfcantllego.getValue().toString());          
            double precio = Double.parseDouble(jtfprecio.getValue().toString());
            
            double impor = cant*precio;
            jtfimporte.setValue(impor);
        } catch (NumberFormatException e) {
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblcodigo = new javax.swing.JLabel();
        jlbldescripcion = new javax.swing.JLabel();
        jtfcantllego = new javax.swing.JFormattedTextField();
        jtfcantacord = new javax.swing.JFormattedTextField();
        jtfprecio = new javax.swing.JFormattedTextField();
        jtfimporte = new javax.swing.JFormattedTextField();
        jbtneliminar = new javax.swing.JButton();
        jbtneditar = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblcodigo.setText("jLabel1");
        jPanel1.add(jlblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jlbldescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlbldescripcion.setText("jLabel2");
        jPanel1.add(jlbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jtfcantllego.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfcantllego.setEnabled(false);
        jtfcantllego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcantllegoActionPerformed(evt);
            }
        });
        jtfcantllego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcantllegoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfcantllegoKeyTyped(evt);
            }
        });
        jPanel1.add(jtfcantllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 150, -1));

        jtfcantacord.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfcantacord.setEnabled(false);
        jtfcantacord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcantacordActionPerformed(evt);
            }
        });
        jtfcantacord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcantacordKeyReleased(evt);
            }
        });
        jPanel1.add(jtfcantacord, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, -1));

        jtfprecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfprecio.setEnabled(false);
        jtfprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfprecioActionPerformed(evt);
            }
        });
        jtfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfprecioKeyReleased(evt);
            }
        });
        jPanel1.add(jtfprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        jtfimporte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfimporte.setCaretColor(new java.awt.Color(255, 51, 51));
        jtfimporte.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jtfimporte.setEnabled(false);
        jtfimporte.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jtfimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 150, -1));

        jbtneliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recycle.png"))); // NOI18N
        jbtneliminar.setToolTipText("Eliminar");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jbtneditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editlapiz.png"))); // NOI18N
        jbtneditar.setToolTipText("Editar");
        jbtneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jbtnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/savedisk.png"))); // NOI18N
        jbtnguardar.setToolTipText("Guardar");
        jbtnguardar.setEnabled(false);
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CANTIDAD LLEGO:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CANTIDAD ACORDADA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("PRECIO:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("IMPORTE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        // TODO add your handling code here:
        frmingresoprod.seteliminar();
        this.dispose();
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jbtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditarActionPerformed
        // TODO add your handling code here:
        jtfcantacord.setEnabled(true);
        jtfcantllego.setEnabled(true);
        jtfprecio.setEnabled(true);
    }//GEN-LAST:event_jbtneditarActionPerformed

    private void jtfcantllegoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantllegoKeyReleased
        // TODO add your handling code here:
        importe();
        if(evt.getKeyCode()!=10)
        jbtnguardar.setEnabled(false);
    }//GEN-LAST:event_jtfcantllegoKeyReleased

    private void jtfprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfprecioKeyReleased
        // TODO add your handling code here:
        importe();
         if(evt.getKeyCode()!=10)
        jbtnguardar.setEnabled(false);
    }//GEN-LAST:event_jtfprecioKeyReleased

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        // TODO add your handling code here:
        System.out.println("iddet"+detcompra.getIddetallecompra());
        if(detcompra.getIddetallecompra()!=0){
        detcompra.setCantidad(Double.parseDouble(jtfcantllego.getValue().toString()));
        detcompra.setCantidadacord(Double.parseDouble(jtfcantacord.getValue().toString()));
        detcompra.setPrecio(Double.parseDouble(jtfprecio.getValue().toString()));
            System.out.println("idprodguardar"+detcompra.getIdproducto());
        daodetc.editar(detcompra);
        frmingresoprod.seteditar(detcompra,jlblcodigo.getText(),jlbldescripcion.getText(),
                jtfimporte.getValue());
        }else {
        frmingresoprod.seteditar(detcompra,jlblcodigo.getText(),jlbldescripcion.getText(),
                jtfimporte.getValue());
        
        }
        this.dispose();
    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void jtfcantllegoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantllegoKeyTyped
        // TODO add your handling code here:
         importe();
    }//GEN-LAST:event_jtfcantllegoKeyTyped

    private void jtfcantllegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcantllegoActionPerformed
        // TODO add your handling code here:
        jbtnguardar.setEnabled(true);
    }//GEN-LAST:event_jtfcantllegoActionPerformed

    private void jtfprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfprecioActionPerformed
        // TODO add your handling code here:
        jbtnguardar.setEnabled(true);
    }//GEN-LAST:event_jtfprecioActionPerformed

    private void jtfcantacordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcantacordActionPerformed
        // TODO add your handling code here:}
        jbtnguardar.setEnabled(true);
    }//GEN-LAST:event_jtfcantacordActionPerformed

    private void jtfcantacordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantacordKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()!=10)
        jbtnguardar.setEnabled(false);
    }//GEN-LAST:event_jtfcantacordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDEditarEliminarDetalleCompra dialog = new JDEditarEliminarDetalleCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtneditar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JLabel jlblcodigo;
    private javax.swing.JLabel jlbldescripcion;
    private javax.swing.JFormattedTextField jtfcantacord;
    private javax.swing.JFormattedTextField jtfcantllego;
    private javax.swing.JFormattedTextField jtfimporte;
    private javax.swing.JFormattedTextField jtfprecio;
    // End of variables declaration//GEN-END:variables
}
