/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.FormatoNumerico;
import DAO.DetalleComprasDAO;
import Pojos.DetalleCompras;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JDEditarEliminarDetalleCompra extends javax.swing.JDialog {

    /**
     * Creates new form JDEditarEliminarDetalleCompra
     */
    DetalleCompras detcompra = new DetalleCompras();
    JIFIngresoProducto frmingresoprod;
    DetalleComprasDAO daodetc= new DetalleComprasDAO();
    FormatoNumerico fn = new FormatoNumerico();
    boolean valida=true;
    public JDEditarEliminarDetalleCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public JDEditarEliminarDetalleCompra(java.awt.Frame parent, boolean modal,DetalleCompras detcompra,String cod
    ,String descrip, JIFIngresoProducto frmingresoprod) {
        super(parent, modal);
        initComponents();
        this.detcompra= detcompra;
        jlblcodigo.setText(cod);
        jlbldescripcion.setText(descrip);
                
        jtfcantllego.setText(fn.FormatoN(detcompra.getCantidad()));
        jtfcantacord.setText(fn.FormatoN(detcompra.getCantidadacord()));
        jtfprecio.setText(fn.FormatoN(detcompra.getPrecio()));
        jtfimporte.setText(fn.FormatoN(Double.parseDouble(jtfcantllego.getText())
                *Double.parseDouble(jtfprecio.getText())));
        this.frmingresoprod= frmingresoprod;
        
        jtfenable(false, false, false, false);
        this.setLocationRelativeTo(null);
    }
    public void importe(){
        try {
            
            double cant=Double.parseDouble(jtfcantllego.getText());          
            double precio = Double.parseDouble(jtfprecio.getText());
            
            double impor = cant*precio;
            jtfimporte.setText(fn.FormatoN(impor));
            
        } catch (NumberFormatException e) {
            valida=false;
            jtfimporte.setText("Error");
        }
    
    
    }
    public void jtfenable(boolean cantacor,boolean cantllego, boolean precio,
    boolean importe)
    {
        jtfcantacord.setEnabled(cantacor);
        jtfcantllego.setEnabled(cantllego);
        jtfprecio.setEnabled(precio);
        jtfimporte.setEditable(importe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblcodigo = new javax.swing.JLabel();
        jlbldescripcion = new javax.swing.JLabel();
        jbtneliminar = new javax.swing.JButton();
        jbtneditar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfcantllego = new javax.swing.JTextField();
        jtfcantacord = new javax.swing.JTextField();
        jtfprecio = new javax.swing.JTextField();
        jtfimporte = new javax.swing.JTextField();
        jbtnguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblcodigo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblcodigo.setText("jLabel1");
        jPanel1.add(jlblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jlbldescripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlbldescripcion.setText("jLabel2");
        jPanel1.add(jlbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jbtneliminar.setBackground(new java.awt.Color(238, 17, 17));
        jbtneliminar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbtneliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtneliminar.setText("Eliminar");
        jbtneliminar.setToolTipText("");
        jbtneliminar.setBorderPainted(false);
        jbtneliminar.setContentAreaFilled(false);
        jbtneliminar.setOpaque(true);
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 50));

        jbtneditar.setBackground(new java.awt.Color(244, 155, 22));
        jbtneditar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbtneditar.setForeground(new java.awt.Color(255, 255, 255));
        jbtneditar.setText("Editar");
        jbtneditar.setToolTipText("");
        jbtneditar.setBorderPainted(false);
        jbtneditar.setContentAreaFilled(false);
        jbtneditar.setOpaque(true);
        jbtneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 50));

        jLabel9.setText("Cant. Llego:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel10.setText("Cant. Acordada:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 20));

        jLabel11.setText("Precio:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLabel3.setText("Importe:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 20));

        jtfcantllego.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcantllegoKeyReleased(evt);
            }
        });
        jPanel1.add(jtfcantllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 150, -1));

        jtfcantacord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcantacordKeyReleased(evt);
            }
        });
        jPanel1.add(jtfcantacord, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 160, -1));

        jtfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfprecioKeyReleased(evt);
            }
        });
        jPanel1.add(jtfprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 150, -1));

        jtfimporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfimporteKeyReleased(evt);
            }
        });
        jPanel1.add(jtfimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 160, -1));

        jbtnguardar.setBackground(new java.awt.Color(77, 161, 227));
        jbtnguardar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jbtnguardar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnguardar.setText("Guardar");
        jbtnguardar.setToolTipText("");
        jbtnguardar.setBorderPainted(false);
        jbtnguardar.setContentAreaFilled(false);
        jbtnguardar.setOpaque(true);
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"¿Esta seguro de eliminar el item?","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            frmingresoprod.seteliminar(detcompra);
            this.dispose();
        
        }
        
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jbtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditarActionPerformed
        // TODO add your handling code here:
        jtfenable(true, true, true, false);
    }//GEN-LAST:event_jbtneditarActionPerformed

    private void jtfcantllegoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantllegoKeyReleased
        // TODO add your handling code here:
        importe();
    }//GEN-LAST:event_jtfcantllegoKeyReleased

    private void jtfcantacordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantacordKeyReleased
        // TODO add your handling code here:
         importe();
    }//GEN-LAST:event_jtfcantacordKeyReleased

    private void jtfprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfprecioKeyReleased
        // TODO add your handling code here:
         importe();
    }//GEN-LAST:event_jtfprecioKeyReleased

    private void jtfimporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfimporteKeyReleased
        // TODO add your handling code here:
         importe();
    }//GEN-LAST:event_jtfimporteKeyReleased

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        // TODO add your handling code here:
        if(valida==true)
        {
        
            System.out.println("iddet"+detcompra.getIddetallecompra());
            detcompra.setCantidad(Double.parseDouble(jtfcantllego.getText()));
            detcompra.setCantidadacord(Double.parseDouble(jtfcantacord.getText()));
            detcompra.setPrecio(Double.parseDouble(jtfprecio.getText()));
            detcompra.setImporte(Double.parseDouble(jtfimporte.getText()));
            if(detcompra.getIddetallecompra()!=0){

                System.out.println("idprodguardar"+detcompra.getIdproducto());
            daodetc.editar(detcompra);
            frmingresoprod.seteditar(detcompra);
            }else {
            frmingresoprod.seteditar(detcompra);

            }
            this.dispose();

        }else {
            JOptionPane.showMessageDialog(null, "Ingrese datos validos","",JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_jbtnguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEditarEliminarDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDEditarEliminarDetalleCompra dialog = new JDEditarEliminarDetalleCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtneditar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JLabel jlblcodigo;
    private javax.swing.JLabel jlbldescripcion;
    private javax.swing.JTextField jtfcantacord;
    private javax.swing.JTextField jtfcantllego;
    private javax.swing.JTextField jtfimporte;
    private javax.swing.JTextField jtfprecio;
    // End of variables declaration//GEN-END:variables
}
