/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.DetalleCajaDAO;
import Pojos.DetalleCaja;
import java.awt.Color;

/**
 *
 * @author info2017
 */
public class JDEgresoCaja extends javax.swing.JDialog {

    /**
     * Creates new form JDEgresoCaja
     */
    DetalleCajaDAO daodetcaja = new DetalleCajaDAO();
    DetalleCaja detcaja = new DetalleCaja();
    long id;
    public JDEgresoCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public JDEgresoCaja(java.awt.Frame parent, boolean modal,long id) {
        super(parent, modal);
        initComponents();
        this.id=id;
        this.setLocationRelativeTo(null);
    }

     public void valida(){
      try {
            double impor = Double.parseDouble(jtfimporte.getText());
            if(impor>0 && jtamotivo.getText().replaceAll(" ", "").length()>0 && jtfentrega.getText().replaceAll(" ", "").length()>0){
            jbtnaceptar.setEnabled(true);
            
            }else {
            jbtnaceptar.setEnabled(false);
            }
        } catch (Exception e) {
            jbtnaceptar.setEnabled(false);
        }
      
      if(jtfentrega.getText().replaceAll(" ", "").length()<=0){
          jtfentrega.setBackground(new Color(248, 193, 186));
      }else {
          jtfentrega.setBackground(Color.WHITE);
      }
      if(jtamotivo.getText().replaceAll(" ", "").length()<=0){
          jtamotivo.setBackground(new Color(248, 193, 186));
      }else {
             jtamotivo.setBackground(Color.WHITE);
      }
      
         try {
             if(Double.parseDouble(jtfimporte.getText())<=0){
                jtfimporte.setBackground(new Color(248, 193, 186));
            }else {
                jtfimporte.setBackground(Color.WHITE);
            }
             
         } catch (Exception e) {
             jtfimporte.setBackground(new Color(248, 193, 186));
         }
      
      
      
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfimporte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtamotivo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jbtnaceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfentrega = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("EGRESO DE CAJA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 463, -1));

        jLabel2.setText("Importe:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jtfimporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfimporteKeyReleased(evt);
            }
        });
        getContentPane().add(jtfimporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 220, -1));

        jtamotivo.setColumns(20);
        jtamotivo.setRows(5);
        jtamotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtamotivoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtamotivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 431, 190));

        jLabel3.setText("Concepto de:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept2.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar / Imprimir");
        jbtnaceptar.setEnabled(false);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, -1));

        jLabel4.setText("Sirvase entregar a: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jtfentrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfentregaKeyReleased(evt);
            }
        });
        getContentPane().add(jtfentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 430, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        double importe=Double.parseDouble(jtfimporte.getText());
        String motivo = jtamotivo.getText().toUpperCase();
        detcaja.setAbono(-1*importe);
        detcaja.setMotivoanulacion(motivo);
        detcaja.setIdcaja(id);
        detcaja.setEntrega(jtfentrega.getText().toUpperCase());
        long id =daodetcaja.insertaregreso(detcaja);
         this.dispose();
        daodetcaja.printegreso(id);
       
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfimporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfimporteKeyReleased
        // TODO add your handling code here:
      valida();
    }//GEN-LAST:event_jtfimporteKeyReleased

    private void jtamotivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtamotivoKeyReleased
        // TODO add your handling code here:
         valida();
    }//GEN-LAST:event_jtamotivoKeyReleased

    private void jtfentregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfentregaKeyReleased
        // TODO add your handling code here:
        valida();
    }//GEN-LAST:event_jtfentregaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDEgresoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDEgresoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDEgresoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDEgresoCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDEgresoCaja dialog = new JDEgresoCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JTextArea jtamotivo;
    private javax.swing.JTextField jtfentrega;
    private javax.swing.JTextField jtfimporte;
    // End of variables declaration//GEN-END:variables
}
