/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.ReparacionDAO;
import Pojos.Reparacion;
import java.awt.Image;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;

/**
 *
 * @author HERNAN
 */
public class JDMostrarReparacion extends java.awt.Dialog {

    /**
     * Creates new form JDMostrarReparacion
     */
    ReparacionDAO reparadao=new ReparacionDAO();
    Reparacion reparacion;
    long idrepara; 
    DecimalFormat  nf =new DecimalFormat("#.00");
    public JDMostrarReparacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     public JDMostrarReparacion(java.awt.Frame parent, boolean modal,long idrepara) {
        super(parent, modal);
        initComponents();
        this.idrepara=idrepara;
                
        
         SimpleDateFormat sd= new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
         double total =0;
         
        reparacion=reparadao.verdetalle(idrepara);
        jlblcodigo.setText("Cod.: "+reparacion.getCodigo());
        jlblfecha.setText("Fecha Recepción: "+sd.format(reparacion.getFechaR()));
        jlblfechaentrega.setText("Fecha Entrega: "+(reparacion.getFechaE()));
        jlblcliente.setText("Cliente: "+reparacion.getCliente());
        jlbltecnico.setText("Tecnico: "+reparacion.getEmpleado());
        jlblmarca.setText("Marca: "+reparacion.getMarca());
        jlblmodelo.setText("Modelo: "+reparacion.getModelo());
        jtafallas.setText(reparacion.getFallas());
        jtafallas.setLineWrap(true);
        jtadiagnostico.setText(reparacion.getDiagnostico());
        jtadiagnostico.setLineWrap(true);
        jtacausas.setText(reparacion.getCausas());
        jtacausas.setLineWrap(true);
        jtamotivoanulacion.setText(reparacion.getMotivo());
        jtamotivoanulacion.setLineWrap(true);
        jtaobservacion.setText(reparacion.getObservacion());
        jtaobservacion.setLineWrap(true);
        jlblabono.setText("Abono: "+(nf.format(reparacion.getAbono())));
//       jlbldescuento.setText("Descuento: "+(nf.format(reparacion.getDescuento())));
        jlblprecio.setText("Precio: "+(nf.format(reparacion.getPrecio())));
        jlblpreciorevision.setText("Precio Revisión: "+(nf.format(reparacion.getPreciorevision())));
        jlblimporte.setText("Importe: "+(nf.format(reparacion.getTotal())));
        total = reparacion.getTotal()-reparacion.getAbono();
       jlbltotal.setText("Deuda: "+nf.format(total));
       jlblatendido.setText("Atendido por: "+reparacion.getAtendido());
       
       
       jlblestado.setText("Estado: "+reparacion.getEstado());
       
       
        /// mostrar imagen ///
        ImageIcon imageIcon = new ImageIcon(reparacion.getFoto());
        //ImageIcon imageUser = imageIcon;
        Image img = imageIcon.getImage();
        Image newimg = img.getScaledInstance(jlblimagen.getWidth(), jlblimagen.getHeight(), java.awt.Image.SCALE_AREA_AVERAGING);
        imageIcon = new ImageIcon(newimg);
        jlblimagen.setIcon(imageIcon);   
        //////////////////////////////////////////////
       this.setLocationRelativeTo(null);
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblcodigo = new javax.swing.JLabel();
        jlblfecha = new javax.swing.JLabel();
        jlblcliente = new javax.swing.JLabel();
        jlbltecnico = new javax.swing.JLabel();
        jlblimagen = new javax.swing.JLabel();
        jlblmarca = new javax.swing.JLabel();
        jlblmodelo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtafallas = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtacausas = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaobservacion = new javax.swing.JTextArea();
        jlblabono = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtadiagnostico = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jlblfechaentrega = new javax.swing.JLabel();
        jlblatendido = new javax.swing.JLabel();
        jlblestado = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtamotivoanulacion = new javax.swing.JTextArea();
        jbtnimprimir = new javax.swing.JButton();
        jlblprecio = new javax.swing.JLabel();
        jlblpreciorevision = new javax.swing.JLabel();
        jlblimporte = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jlblcodigo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlblcodigo.setForeground(new java.awt.Color(255, 51, 51));
        jlblcodigo.setText("jLabel1");

        jlblfecha.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblfecha.setText("fecha");

        jlblcliente.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblcliente.setText("cliente");

        jlbltecnico.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlbltecnico.setText("tecnico");

        jlblimagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblmarca.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblmarca.setText("marca");

        jlblmodelo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblmodelo.setText("modelo");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel7.setText("Fallas:");

        jtafallas.setEditable(false);
        jtafallas.setColumns(20);
        jtafallas.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtafallas.setRows(5);
        jScrollPane1.setViewportView(jtafallas);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel8.setText("Causas:");

        jtacausas.setEditable(false);
        jtacausas.setColumns(20);
        jtacausas.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtacausas.setRows(5);
        jScrollPane2.setViewportView(jtacausas);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel9.setText("Observación");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(163, 75));

        jtaobservacion.setEditable(false);
        jtaobservacion.setColumns(20);
        jtaobservacion.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtaobservacion.setRows(5);
        jScrollPane3.setViewportView(jtaobservacion);

        jlblabono.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblabono.setText("abono");

        jlbltotal.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlbltotal.setForeground(new java.awt.Color(255, 51, 51));
        jlbltotal.setText("total");

        jLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel.setText("Motivo Anulacion:");

        jtadiagnostico.setEditable(false);
        jtadiagnostico.setColumns(20);
        jtadiagnostico.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtadiagnostico.setRows(5);
        jScrollPane4.setViewportView(jtadiagnostico);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel1.setText("Diagnostico:");

        jlblfechaentrega.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblfechaentrega.setText("fechaentrega");

        jlblatendido.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblatendido.setText("atendido");

        jlblestado.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jlblestado.setText("estado");

        jtamotivoanulacion.setEditable(false);
        jtamotivoanulacion.setColumns(20);
        jtamotivoanulacion.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtamotivoanulacion.setRows(5);
        jScrollPane5.setViewportView(jtamotivoanulacion);

        jbtnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jbtnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirActionPerformed(evt);
            }
        });

        jlblprecio.setText("Precio");

        jlblpreciorevision.setText("preciorevision");

        jlblimporte.setText("totalpagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlblfecha)
                                            .addGap(154, 154, 154)
                                            .addComponent(jlblfechaentrega))
                                        .addComponent(jlblcliente)
                                        .addComponent(jlbltecnico)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlblmarca)
                                            .addGap(263, 263, 263)
                                            .addComponent(jlblmodelo)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbltotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnimprimir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jlblabono)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblatendido)
                                            .addComponent(jlblestado)))
                                    .addComponent(jlblprecio)
                                    .addComponent(jlblpreciorevision)
                                    .addComponent(jlblimporte))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblcodigo)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblfecha)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jlblfechaentrega)))
                        .addGap(9, 9, 9)
                        .addComponent(jlblcliente)
                        .addGap(12, 12, 12)
                        .addComponent(jlbltecnico)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblmarca)
                            .addComponent(jlblmodelo)))
                    .addComponent(jlblimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblatendido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblestado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblabono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblprecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblpreciorevision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblimporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbltotal)
                    .addComponent(jbtnimprimir))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jbtnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirActionPerformed
        // TODO add your handling code here:
        reparadao.imprimir(idrepara);
    }//GEN-LAST:event_jbtnimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDMostrarReparacion dialog = new JDMostrarReparacion(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbtnimprimir;
    private javax.swing.JLabel jlblabono;
    private javax.swing.JLabel jlblatendido;
    private javax.swing.JLabel jlblcliente;
    private javax.swing.JLabel jlblcodigo;
    private javax.swing.JLabel jlblestado;
    private javax.swing.JLabel jlblfecha;
    private javax.swing.JLabel jlblfechaentrega;
    private javax.swing.JLabel jlblimagen;
    private javax.swing.JLabel jlblimporte;
    private javax.swing.JLabel jlblmarca;
    private javax.swing.JLabel jlblmodelo;
    private javax.swing.JLabel jlblprecio;
    private javax.swing.JLabel jlblpreciorevision;
    private javax.swing.JLabel jlbltecnico;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTextArea jtacausas;
    private javax.swing.JTextArea jtadiagnostico;
    private javax.swing.JTextArea jtafallas;
    private javax.swing.JTextArea jtamotivoanulacion;
    private javax.swing.JTextArea jtaobservacion;
    // End of variables declaration//GEN-END:variables
}
