/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

//import Conexion.TestConexionServer;
import com.sun.awt.AWTUtilities;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HERNAN
 */
public class JDReconexion extends java.awt.Dialog {

    /**
     * Creates new form JDReconexion
     */
    public JDReconexion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        pruebaconexion();
        this.setLocationRelativeTo(null);
    }
//    
//    public void pruebaconexion(){
//     
//     Runnable runnable = new Runnable() {
//
//         @Override
//         public void run() {
//             int i=0;
////             throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
////             TestConexionServer test= new TestConexionServer();
//             while(true){
//                
//                 try {
//                     Thread.sleep(1000);
//                 } catch (InterruptedException ex) {
//                     Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                 }
//                  
//                 System.out.println("probando conexion...reconexion");
//                
//                if(test.ping()==true){
//                   
//                    
//                   jlblrpruebaconexion.setText("<html><p style=\"color:#333333\";>"+"Conexión Restablecida");
//                   jlblrpruebaconexion.setIcon(null);
//                   try {
//                     Thread.sleep(2000);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                   JDReconexion.this.dispose();
//                   break;
//                   
//                   
//               } else{ 
////                   jlblrpruebaconexion.setText("<html><p style=\"color:#FF0000 \";>"+"No se obtuvo conexion con el servidor pongase en contacto con el administrador del sistema");
//                   jlblrpruebaconexion.setText("<html><p style=\"color:#333333 \";>"+"Reconectando");
//                 
//                    try {
//                     Thread.sleep(1000);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                    jlblrpruebaconexion.setText("<html><p style=\"color:#333333 \";>"+"Reconectando .");
//                    try {
//                     Thread.sleep(1000);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                    jlblrpruebaconexion.setText("<html><p style=\"color:#333333 \";>"+"Reconectando ..");
//                    try {
//                     Thread.sleep(1000);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                    jlblrpruebaconexion.setText("<html><p style=\"color:#333333 \";>"+"Reconectando ...");
//                    try {
//                     Thread.sleep(1000);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                  
//               }
//             
//              
//             }
//             
//         }
//     };
//     Thread T = new Thread(runnable);
//     T.start();
//     
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblrpruebaconexion = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 170));

        jlblrpruebaconexion.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblrpruebaconexion.setText("Reconectando ...");
        add(jlblrpruebaconexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDReconexion dialog = new JDReconexion(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                
               
                AWTUtilities.setWindowOpaque(dialog, false);
                
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlblrpruebaconexion;
    // End of variables declaration//GEN-END:variables
}
