/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.DetalleCajaDAO;
import DAO.ReparacionDAO;
import DAO.VentasDAO;
import Pojos.Caja;
import Pojos.DetalleCaja;
import Pojos.Reparacion;
import Pojos.Ventas;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author info2017
 */
public class JIFCaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCaja
     */
    List<String> codigo= new ArrayList<>();
    List<String> num= new ArrayList<>();
    boolean codfoco = false;
    boolean numfoco= false;
    VentasDAO daoventa= new VentasDAO();
    Ventas venta=  new Ventas();
    Caja caja= new Caja();
    DetalleCajaDAO daodetcaja= new DetalleCajaDAO();
   // DetalleCaja detcaja= new DetalleCaja();
    Reparacion repara= new Reparacion();
    ReparacionDAO daoreparacion= new ReparacionDAO();
    public JIFCaja() {
        initComponents();
    }
    public JIFCaja(Caja caja) {
        initComponents();
        System.out.println("idcaja"+caja.getId_caja());
        this.caja=caja;
    }
    public void imprimircant(){       
       
    if(codfoco==true){
         String s="";
    for (String lista : codigo){
         s= s + lista;
        
    }
      jtfcodigo.setText(s);
    }
    if(numfoco==true){
         String s1="";
    for (String lista : num){
         s1= s1+ lista;
        
    }
     jtfnumero.setText(s1);
    }
     
   
   
    
    }
//    public double calculatotal(){
//        Double importe=0.0,subtotal,iva,total=0.0;
//        double descuento =venta.getDescuento();
//        for (int i=0;i<=jtabla.getRowCount()-1 ;i++){
//         importe = importe + Double.parseDouble(jtabla.getValueAt(i, 4).toString());
//        }
//        total = importe-descuento;
//        subtotal= total/1.19;
//        iva = total-subtotal;
//       
//        System.out.println("total"+total);
////        BigDecimal totalB = new BigDecimal(total);
////        BigDecimal ivaB = new BigDecimal(iva);
////        BigDecimal subtotalB = new BigDecimal(subtotal);
////        
//        jlbltotal.setValue(total);
//        jlblsubtotal.setValue(subtotal);
//        jlbliva.setValue(iva);
//        jtfdescuento.setValue(descuento);
////        return totalB.setScale(2,BigDecimal.ROUND_HALF_EVEN);
//        return total;
//    }

    public void cobrar(DetalleCaja  detcaja,String estado , double abono,Reparacion repara){
        String tipo="";
        double aabono=abono;
        System.out.println("reparacobrar"+repara.getIdreparacion());
            detcaja.setIdreparacion(repara.getIdreparacion());
            detcaja.setIdventa(venta.getIdventa());
            detcaja.setDocumento(jcbcomprobante.getSelectedItem().toString());
            detcaja.setNumero(jtfnumero.getText());
            detcaja.setIdcaja(caja.getId_caja());
            if(jtfcodigo.getText().substring(0,1).equalsIgnoreCase("R")){
            tipo = "REPARACION";
            
            }else { if(jtfcodigo.getText().substring(0,1).equalsIgnoreCase("V")){
            tipo = "VENTA";
            aabono=Double.parseDouble(jlbltotal.getValue().toString());
            }
            
            }
            detcaja.setAbono(aabono);
            daodetcaja.insertar(detcaja,tipo,estado);
           
           
//            calculatotal();
            jtfnumero.setText("");
            /////////////////////
    
    }
    public void newcobro(){
        //NUEVO OBJETO VENTA
        venta=new Ventas();
        repara = new Reparacion();
        codigo = new ArrayList<>();
        //NUEVO MODELO EN TABLA
        DefaultTableModel modelo= (DefaultTableModel) jtabla.getModel();
         for (int i = 0; i < jtabla.getRowCount(); i++) {
        modelo.removeRow(i);
        i-=1;
        }
        //LIMPIAR JLBL
        jlblcliente.setText("---");
        jlblrut.setText("---");
        jlbltotal.setValue(0);
        jlbliva.setValue(0);
        jlblsubtotal.setValue(0);
        jlblabono.setValue(0);
        jtfnumero.setText("");
        jtfcodigo.setText("COD. VENTA");
        jcbcomprobante.setSelectedIndex(0);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfcodigo = new org.edisoncor.gui.textField.TextFieldRoundIcon();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblcliente = new javax.swing.JLabel();
        jlblrut = new javax.swing.JLabel();
        jlblsubtotal = new javax.swing.JFormattedTextField();
        jlbliva = new javax.swing.JFormattedTextField();
        jlbltotal = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jlblabono = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfdescuento = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jcbcomprobante = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jtfcierrecaja = new org.edisoncor.gui.button.ButtonColoredAction();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        jtbtn7 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn8 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn9 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtnborrar = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtnborrartodo = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn6 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn5 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn4 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn1 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn2 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn3 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtn0 = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtnenter = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtncoma = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtnV = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtnR = new org.edisoncor.gui.button.ButtonColoredAction();
        jtfcobrar = new org.edisoncor.gui.button.ButtonColoredAction();
        jbtnegreso = new org.edisoncor.gui.button.ButtonColoredAction();
        jtfnumero = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtfcodigo.setBackground(new java.awt.Color(204, 204, 204));
        jtfcodigo.setForeground(new java.awt.Color(255, 255, 255));
        jtfcodigo.setText("COD. VENTA");
        jtfcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfcodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfcodigoFocusLost(evt);
            }
        });
        jtfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcodigoActionPerformed(evt);
            }
        });
        jtfcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcodigoKeyReleased(evt);
            }
        });

        panelNice1.setBackground(new java.awt.Color(238, 238, 238));
        panelNice1.setBorderColor(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("CLIENTE:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("R.U.T:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("SUBTOTAL :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("I.V.A (19 %):");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL PAGAR:");

        jlblcliente.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblcliente.setText("* * *");

        jlblrut.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblrut.setText("* * *");

        jlblsubtotal.setEditable(false);
        jlblsubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jlblsubtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblsubtotalActionPerformed(evt);
            }
        });

        jlbliva.setEditable(false);
        jlbliva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jlbliva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jlbltotal.setEditable(false);
        jlbltotal.setForeground(new java.awt.Color(255, 51, 51));
        jlbltotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jlbltotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("ABONO:");

        jlblabono.setEditable(false);
        jlblabono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("DESCUENTO:");

        jtfdescuento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfdescuento.setEnabled(false);

        jtabla.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtabla);

        javax.swing.GroupLayout panelNice1Layout = new javax.swing.GroupLayout(panelNice1);
        panelNice1.setLayout(panelNice1Layout);
        panelNice1Layout.setHorizontalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(jtfdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(jlblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addComponent(jlblabono, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(jlbliva, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(jlbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(panelNice1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblrut, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addComponent(jlblcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNice1Layout.setVerticalGroup(
            panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNice1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlblrut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jtfdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jlblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblabono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jlbliva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelNice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("NUMERO:");

        jcbcomprobante.setBackground(new java.awt.Color(153, 153, 153));
        jcbcomprobante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcbcomprobante.setForeground(new java.awt.Color(0, 0, 0));
        jcbcomprobante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BOLETA", "FACTURA" }));
        jcbcomprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbcomprobanteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("COMPROBANTE:");

        jtfcierrecaja.setBackground(new java.awt.Color(255, 255, 255));
        jtfcierrecaja.setText("Corte");
        jtfcierrecaja.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfcierrecaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcierrecajaActionPerformed(evt);
            }
        });

        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbtn7.setBackground(new java.awt.Color(255, 255, 255));
        jtbtn7.setText("7");
        jtbtn7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jtbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtn7ActionPerformed(evt);
            }
        });
        panelNice2.add(jtbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jbtn8.setBackground(new java.awt.Color(255, 255, 255));
        jbtn8.setText("8");
        jbtn8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 40));

        jbtn9.setBackground(new java.awt.Color(255, 255, 255));
        jbtn9.setText("9");
        jbtn9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 50, 40));

        jbtnborrar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnborrar.setText("<");
        jbtnborrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnborrarActionPerformed(evt);
            }
        });
        panelNice2.add(jbtnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 40));

        jbtnborrartodo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnborrartodo.setText("C");
        jbtnborrartodo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtnborrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnborrartodoActionPerformed(evt);
            }
        });
        panelNice2.add(jbtnborrartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 50, 40));

        jbtn6.setBackground(new java.awt.Color(255, 255, 255));
        jbtn6.setText("6");
        jbtn6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 50, 40));

        jbtn5.setBackground(new java.awt.Color(255, 255, 255));
        jbtn5.setText("5");
        jbtn5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, 40));

        jbtn4.setBackground(new java.awt.Color(255, 255, 255));
        jbtn4.setText("4");
        jbtn4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 40));

        jbtn1.setBackground(new java.awt.Color(255, 255, 255));
        jbtn1.setText("1");
        jbtn1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 40));

        jbtn2.setBackground(new java.awt.Color(255, 255, 255));
        jbtn2.setText("2");
        jbtn2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 50, 40));

        jbtn3.setBackground(new java.awt.Color(255, 255, 255));
        jbtn3.setText("3");
        jbtn3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, 40));

        jbtn0.setBackground(new java.awt.Color(255, 255, 255));
        jbtn0.setText("0");
        jbtn0.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        panelNice2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 40));

        jbtnenter.setBackground(new java.awt.Color(255, 255, 255));
        jbtnenter.setText("ENTER");
        jbtnenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnenterActionPerformed(evt);
            }
        });
        panelNice2.add(jbtnenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 50, 120));

        jbtncoma.setBackground(new java.awt.Color(255, 255, 255));
        jbtncoma.setText(".");
        jbtncoma.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtncoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncomaActionPerformed(evt);
            }
        });
        panelNice2.add(jbtncoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 50, 40));

        jbtnV.setBackground(new java.awt.Color(255, 255, 255));
        jbtnV.setText("v");
        jbtnV.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVActionPerformed(evt);
            }
        });
        panelNice2.add(jbtnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 50, 40));

        jbtnR.setBackground(new java.awt.Color(255, 255, 255));
        jbtnR.setText("r");
        jbtnR.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbtnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRActionPerformed(evt);
            }
        });
        panelNice2.add(jbtnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 50, 40));

        jtfcobrar.setBackground(new java.awt.Color(255, 255, 255));
        jtfcobrar.setText("Cobrar (F2)");
        jtfcobrar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfcobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcobrarActionPerformed(evt);
            }
        });

        jbtnegreso.setText("Egreso");
        jbtnegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnegresoActionPerformed(evt);
            }
        });

        jtfnumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfnumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnumeroFocusLost(evt);
            }
        });
        jtfnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfnumeroKeyReleased(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CAJA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbcomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(733, 733, 733)
                        .addComponent(jtfcierrecaja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNice2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbcomprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jtfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelNice2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfcierrecaja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelNice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
      if(codfoco==true){
        codigo.add(jbtn1.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn1.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
       if(codfoco==true){
        codigo.add(jbtn5.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn5.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        
      if(codfoco==true){
        codigo.add(jbtn6.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn6.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        if(codfoco==true){
        codigo.add(jbtn2.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn2.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        if(codfoco==true){
        codigo.add(jbtn3.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn3.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        if(codfoco==true){
        codigo.add(jbtn8.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn8.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
      if(codfoco==true){
        codigo.add(jbtn9.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn9.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
       if(codfoco==true){
        codigo.add(jbtn4.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn4.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jtbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtn7ActionPerformed
        // TODO add your handling code here:
      if(codfoco==true){
        codigo.add(jtbtn7.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jtbtn7.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jtbtn7ActionPerformed

    private void jbtncomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncomaActionPerformed
        // TODO add your handling code here:
       if(codfoco==true){
        codigo.add(jbtncoma.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtncoma.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtncomaActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        if(codfoco==true){
        codigo.add(jbtn0.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtn0.getText());
        imprimircant();
        }
        
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnborrarActionPerformed
        // TODO add your handling code here:
        if(codfoco==true){
        int digitos=codigo.size()-1;
        System.out.println(digitos);
        if(digitos >= 0){
            codigo.remove(digitos);
            
            imprimircant();
            jbtnenter.doClick();

        }
        jtfcodigo.requestFocus();
        
        }
        if(numfoco==true){
        int digitos=num.size()-1;
        System.out.println(digitos);
        if(digitos >= 0){
            num.remove(digitos);
            imprimircant();

        }
        jtfnumero.requestFocus();
        
        }
        

    }//GEN-LAST:event_jbtnborrarActionPerformed

    private void jbtnborrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnborrartodoActionPerformed
        // TODO add your handling code here:
        if(codfoco==true){
        codigo = new ArrayList<String>();
        jbtnenter.doClick();
        imprimircant();
        jtfcodigo.requestFocus();
        }
        if(numfoco==true){
        num = new ArrayList<String>();
        imprimircant();
        jtfnumero.requestFocus();
        }
        
    }//GEN-LAST:event_jbtnborrartodoActionPerformed

    private void jbtnenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnenterActionPerformed
        // TODO add your handling code here:
        try {
            String cod= (jtfcodigo.getText());
            if(!cod.equals("") && !cod.equals("COD. VENTA")){
                System.out.println("codsub"+cod.substring(0, 1));
                if(cod.substring(0, 1).equalsIgnoreCase("V")){
                venta = daoventa.buscarventa(jtabla, cod,jlblcliente,jlblrut);
                jlbltotal.setValue(venta.getTotal());
                jlbliva.setValue(venta.getIva());
                jlblsubtotal.setValue(venta.getSuvtotal());
                jtfdescuento.setValue(venta.getDescuento());
//                calculatotal();
                
                }else {if(cod.substring(0, 1).equalsIgnoreCase("R")){
                repara= daoreparacion.buscar(jtabla, cod, jlblcliente, jlblrut,jlbltotal,
                        jlblsubtotal,jlbliva,jlblabono);
//                calculatotal();
                }else {
                
                    newcobro();
                }
                
                
                
                }
                
                
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "INGRESE UN CODIGO VALIDO");
        }
        
         
        
    }//GEN-LAST:event_jbtnenterActionPerformed

    private void jtfcodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcodigoFocusGained
        // TODO add your handling code here:
        if(jtfcodigo.getText().equals("COD. VENTA")){
            jtfcodigo.setText("");
        }
        codfoco= true;
        numfoco=false;
        System.out.println("true");
    }//GEN-LAST:event_jtfcodigoFocusGained

    private void jtfcodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcodigoFocusLost
        // TODO add your handling code here:
        if(jtfcodigo.getText().equals("")){
            jtfcodigo.setText("COD. VENTA");
        }
       
    }//GEN-LAST:event_jtfcodigoFocusLost

    private void jtfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcodigoActionPerformed
        // TODO add your handling code here:
        jbtnenter.doClick();
    }//GEN-LAST:event_jtfcodigoActionPerformed

    private void jcbcomprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbcomprobanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbcomprobanteActionPerformed

    private void jtfcobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcobrarActionPerformed
        // TODO add your handling code here:
        System.out.println("idrepara"+repara.getIdreparacion());
        System.out.println("idventa"+venta.getIdventa());
        String tipopago="";
       
        if(repara.getIdreparacion()!=0 || venta.getIdventa()!=0 ){
          double total= Double.parseDouble(jlbltotal.getValue().toString());
                String cod= (jtfcodigo.getText());
                  if(venta.getIdventa()!=0){
                      tipopago="VENTA";
                }else{
                      tipopago="REPARACION";
                }
                JDCobrarCaja cobrarcaja= new JDCobrarCaja(new java.awt.Frame(),isVisible(),this,repara,total);
                cobrarcaja.setVisible(true);
                  
         
            
        }else {
            JOptionPane.showMessageDialog(null, "INGRESE LOS DATOS NECESARIOS PARA REALIZAR EL COBRO E INTENTE"
                    + " NUEVAMENTE");
        
        }
        
        
    }//GEN-LAST:event_jtfcobrarActionPerformed

    private void jtfcierrecajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcierrecajaActionPerformed
        // TODO add your handling code here:
      JDCerrarCaja Ccaja= new JDCerrarCaja(new java.awt.Frame(),isVisible(),caja,this);
      Ccaja.setVisible(true);
      
      
    }//GEN-LAST:event_jtfcierrecajaActionPerformed

    private void jtfnumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnumeroFocusGained
        // TODO add your handling code here:
        numfoco= true;
        codfoco=false;
    }//GEN-LAST:event_jtfnumeroFocusGained

    private void jtfnumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnumeroFocusLost
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jtfnumeroFocusLost

    private void jbtnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRActionPerformed
        // TODO add your handling code here:
          if(codfoco==true){
        codigo.add(jbtnR.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtnR.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtnRActionPerformed

    private void jbtnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVActionPerformed
        // TODO add your handling code here:
          if(codfoco==true){
        codigo.add(jbtnV.getText());
        imprimircant();
        }
          if(numfoco==true){
        num.add(jbtnV.getText());
        imprimircant();
        }
    }//GEN-LAST:event_jbtnVActionPerformed

    private void jlblsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblsubtotalActionPerformed

    private void jtfcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcodigoKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==113){
           jtfcobrar.doClick();
        
        }
    }//GEN-LAST:event_jtfcodigoKeyReleased

    private void jtfnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnumeroKeyReleased
        // TODO add your handling code here:
         if(evt.getKeyCode()==113){
           jtfcobrar.doClick();
        
        }
    }//GEN-LAST:event_jtfnumeroKeyReleased

    private void jbtnegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnegresoActionPerformed
        // TODO add your handling code here:
        JDEgresoCaja egreso = new JDEgresoCaja(new Frame(), isVisible(),caja.getId_caja());
        egreso.setVisible(true);
        
        
    }//GEN-LAST:event_jbtnegresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn0;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn1;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn2;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn3;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn4;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn5;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn6;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn8;
    private org.edisoncor.gui.button.ButtonColoredAction jbtn9;
    private org.edisoncor.gui.button.ButtonColoredAction jbtnR;
    private org.edisoncor.gui.button.ButtonColoredAction jbtnV;
    private org.edisoncor.gui.button.ButtonColoredAction jbtnborrar;
    private org.edisoncor.gui.button.ButtonColoredAction jbtnborrartodo;
    private org.edisoncor.gui.button.ButtonColoredAction jbtncoma;
    private org.edisoncor.gui.button.ButtonColoredAction jbtnegreso;
    private org.edisoncor.gui.button.ButtonColoredAction jbtnenter;
    private javax.swing.JComboBox jcbcomprobante;
    private javax.swing.JFormattedTextField jlblabono;
    private javax.swing.JLabel jlblcliente;
    private javax.swing.JFormattedTextField jlbliva;
    private javax.swing.JLabel jlblrut;
    private javax.swing.JFormattedTextField jlblsubtotal;
    private javax.swing.JFormattedTextField jlbltotal;
    private javax.swing.JTable jtabla;
    private org.edisoncor.gui.button.ButtonColoredAction jtbtn7;
    private org.edisoncor.gui.button.ButtonColoredAction jtfcierrecaja;
    private org.edisoncor.gui.button.ButtonColoredAction jtfcobrar;
    private org.edisoncor.gui.textField.TextFieldRoundIcon jtfcodigo;
    private javax.swing.JFormattedTextField jtfdescuento;
    private javax.swing.JTextField jtfnumero;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    // End of variables declaration//GEN-END:variables
}
