/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.GeneraCarnet;
import ClasesGlobales.Mayusculas;
import DAO.EmpleadoDAO;
import Pojos.Empleado;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author info2017
 */
public class JIFEmpleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFEmpleados
     */
    EmpleadoDAO daoempleado = new EmpleadoDAO();
   Boolean editar;
   long id;
    String rutaimagen=null;
     byte[]  fotoB=new  byte[0];
     Mayusculas mayus= new Mayusculas();
    public JIFEmpleados() {
        initComponents();
        bloquearjtf(false, false, false, false, false);
        bloquearjbtn(true, false, false, false, false, true,false,false);
        daoempleado.mostrarempleado(jtablaempleado);
    }
    

    public void bloquearjtf(boolean rut, boolean nombre,boolean email, boolean direccion, boolean celular){
    jtfrut.setEnabled(rut);
    jtfnombre.setEnabled(nombre);
    jtfemail.setEnabled(email);
    jtfdireccion.setEnabled(direccion);
    jtfcelular.setEnabled(celular);
     
    
    }
    public void bloquearjbtn(boolean nuevo,boolean editar,boolean guardar,boolean eliminar,boolean cancelar,
    boolean salir,boolean foto,boolean carne ){
    jbtnnew.setEnabled(nuevo);
    jbtneditar.setEnabled(editar);
    jbtnguardar.setEnabled(guardar);
    jbtneliminar.setEnabled(eliminar);
    jbtncancelar.setEnabled(cancelar);
//    jbtnsalir.setEnabled(salir);
    jbtnfoto.setEnabled(foto);
    jbtngeneracarnet.setEnabled(carne);
    
    }
     public void limpiarjtf(){
    jtfrut.setText("R.U.T");
    jtfnombre.setText("NOMBRES Y APELLIDOS");
    jtfemail.setText("EMAIL");
    jtfdireccion.setText("DIRECCION");
    jtfcelular.setText("CELULAR");
    jlblImageUser.setIcon(null);
    fotoB= new  byte[0];
    }
    public void validaguardar(){
        String nombre= jtfnombre.getText().replaceAll("\\s","");
        String rut=jtfrut.getText().replaceAll("\\s","");
                
    if(!jtfnombre.getText().trim().equals("NOMBRES Y APELLIDOS") && !nombre.equals("") && !jtfrut.getText().equals("R.U.T") && 
            rut.length()>0 ){
        bloquearjbtn(false, false, true,false ,true, true,true,false);
    }else {
        bloquearjbtn(true, false, false, false, true, true,false,false);
    }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaempleado = new javax.swing.JTable();
        jbtncancelar = new javax.swing.JButton();
        jbtneliminar = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        jbtnnew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtfrut = new javax.swing.JTextField();
        jtfdireccion = new javax.swing.JTextField();
        jtfcelular = new javax.swing.JTextField();
        jtfemail = new javax.swing.JTextField();
        jtfnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfbuscarrut = new javax.swing.JTextField();
        jtfbuscarnombre = new javax.swing.JTextField();
        jbtneditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jlblImageUser = new javax.swing.JLabel();
        jbtnfoto = new javax.swing.JButton();
        jbtngeneracarnet = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtablaempleado.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtablaempleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaempleado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtablaempleado.getTableHeader().setReorderingAllowed(false);
        jtablaempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaempleadoMouseReleased(evt);
            }
        });
        jtablaempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtablaempleadoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaempleado);

        jbtncancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbtncancelar.setText("Cancelar");
        jbtncancelar.setToolTipText("Cancelar");
        jbtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncancelarActionPerformed(evt);
            }
        });

        jbtneliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneliminar.setText("Eliminar");
        jbtneliminar.setToolTipText("Eliminar");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });

        jbtnguardar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnguardar.setText("Guardar");
        jbtnguardar.setToolTipText("Guardar");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });

        jbtnnew.setBackground(new java.awt.Color(255, 255, 255));
        jbtnnew.setText("Nuevo");
        jbtnnew.setToolTipText("Nuevo");
        jbtnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnewActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfrut.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfrut.setText("R.U.T");
        jtfrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfrutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfrutFocusLost(evt);
            }
        });
        jtfrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfrutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfrutKeyTyped(evt);
            }
        });
        jPanel2.add(jtfrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 139, -1));

        jtfdireccion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfdireccion.setText("DIRECCION");
        jtfdireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfdireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdireccionFocusLost(evt);
            }
        });
        jtfdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfdireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdireccionKeyTyped(evt);
            }
        });
        jPanel2.add(jtfdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 420, -1));

        jtfcelular.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfcelular.setText("CELULAR");
        jtfcelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfcelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfcelularFocusLost(evt);
            }
        });
        jtfcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcelularActionPerformed(evt);
            }
        });
        jtfcelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcelularKeyReleased(evt);
            }
        });
        jPanel2.add(jtfcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 140, -1));

        jtfemail.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfemail.setText("EMAIL");
        jtfemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfemailFocusLost(evt);
            }
        });
        jtfemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfemailKeyTyped(evt);
            }
        });
        jPanel2.add(jtfemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 420, -1));

        jtfnombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfnombre.setText("NOMBRE Y APELLIDOS");
        jtfnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnombreFocusLost(evt);
            }
        });
        jtfnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfnombreKeyTyped(evt);
            }
        });
        jPanel2.add(jtfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("Buscar por:");

        jtfbuscarrut.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfbuscarrut.setText("R.U.T");
        jtfbuscarrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfbuscarrutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfbuscarrutFocusLost(evt);
            }
        });
        jtfbuscarrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarrutKeyReleased(evt);
            }
        });

        jtfbuscarnombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfbuscarnombre.setText("NOMBRE Y APELLIDOS");
        jtfbuscarnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfbuscarnombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfbuscarnombreFocusLost(evt);
            }
        });
        jtfbuscarnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfbuscarnombreKeyTyped(evt);
            }
        });

        jbtneditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneditar.setText("Editar");
        jbtneditar.setToolTipText("Editar");
        jbtneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(238, 238, 238));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblImageUser.setBackground(new java.awt.Color(255, 255, 255));
        jlblImageUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jlblImageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 120));

        jbtnfoto.setBackground(new java.awt.Color(255, 255, 255));
        jbtnfoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FOTO.png"))); // NOI18N
        jbtnfoto.setText("FOTO");
        jbtnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfotoActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 50));

        jbtngeneracarnet.setBackground(new java.awt.Color(255, 255, 255));
        jbtngeneracarnet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtngeneracarnet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carnet.png"))); // NOI18N
        jbtngeneracarnet.setText("GENERAR CARNET");
        jbtngeneracarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngeneracarnetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfbuscarrut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(jtfbuscarnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(924, 924, 924)
                                .addComponent(jbtngeneracarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(5, 5, 5)
                                .addComponent(jtfbuscarrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtfbuscarnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtneditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnnew))
                            .addComponent(jbtnguardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtneliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtncancelar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jbtngeneracarnet))
        );

        jPanel4.setBackground(new java.awt.Color(238, 238, 238));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRO EMPLEADOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncancelarActionPerformed
        // TODO add your handling code here:
             int index = jtablaempleado.getSelectedRow();
        if(index>=0){
            jtablaempleadoMouseReleased(null);
        } else {
        limpiarjtf();
        }
         bloquearjtf(false, false,false, false,false);
        bloquearjbtn(true, false, false, false, false, true,false,false);
        
        
       
        //int index= jtablaalumno.getSelectedRow();

        //        limpiarjtext();
        //        habilitarjtext(false);
        //        jbtnguardar.setEnabled(false);
        //        jbtncancelar.setEnabled(false);
        //        jbtneditar.setEnabled(false);
        //
        //        guardar=true;
        //
        //        int fila=jtablaalumno.getSelectedRow();
        //        if(fila>=0){
            //            // Integer idP=Integer.parseInt(jtablaalumno.getValueAt(index, 0).toString());
            //            buscar();
            //        }
    }//GEN-LAST:event_jbtncancelarActionPerformed

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        // TODO add your handling code here:
        //        Integer index= jtablaalumno.getSelectedRow();
        //        Integer id = Integer.parseInt(jtablaalumno.getValueAt(index, 0).toString());
        //        if (index<0){
            //            JOptionPane.showMessageDialog(this, "SELECCIONE ALUMNO A ELIMINAR EN LA TABLA");
            //        }else {
            //            if (JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE ELIMINAR AL ALUMNO","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                //                eliminar(id);
                //                mostrar();
                //                limpiarjtext();
                //                habilitarjtext(false);
                //
                //            }
            //
            //        }
        int index= jtablaempleado.getSelectedRow();
        long id = Long.parseLong(jtablaempleado.getValueAt(index, 0).toString());
        if (index<0){
            JOptionPane.showMessageDialog(this, "SELECCIONE EMPLEADO A ELIMINAR EN LA TABLA");
        }else {
            if (JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE ELIMINAR EL EMPLEADO","ELIMINAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                daoempleado.eliminarempleado(id);
                daoempleado.mostrarempleado(jtablaempleado);
                bloquearjtf(false, false, false, false, false);
                bloquearjbtn(true, false, false, false, false, true,false,false);
                limpiarjtf();
            }

        }
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed

        // TODO add your handling code here:
        
        
        Empleado empleado= new Empleado();
        String nombre=jtfnombre.getText().trim();
        String rut=jtfrut.getText().trim();
        String direccion=jtfdireccion.getText().trim();
        String celular=jtfcelular.getText().trim();
        String email=jtfemail.getText().trim();
        
        
        empleado.setNombre(nombre);
        empleado.setRut(rut);
        empleado.setDireccion(direccion);
        empleado.setCelular(celular);
        empleado.setEmail(email);
        empleado.setFoto(fotoB);
        
        if (nombre.length()>0 && rut.length()>0 && direccion.length()>0
                && celular.length()>0 && email.length()>0){
            if(!nombre.equals("NOMBRES Y APELLIDOS")){
                if(editar==false){
                 boolean valida=daoempleado.duplicado(0, rut,"GUARDAR");
                if(valida==true){
                    daoempleado.insertarempleado(empleado);
                } else {
                    JOptionPane.showMessageDialog(null, "EL EMPLEADO YA SE ENCUENTRA REGISTRADO","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
                }  
                 
                }
               
                else{
                    
                    long id=Long.parseLong(jtablaempleado.getValueAt(jtablaempleado.getSelectedRow(), 0).toString());   
                    empleado.setId_empleado(id);
                    boolean Vvalida=daoempleado.duplicado(id, rut,"EDITAR");
                    if(Vvalida==true){
                      daoempleado.editarempleado(empleado);
                    }else {
                     JOptionPane.showMessageDialog(null, "EL RUT INGRESADO YA SE ENCUENTRA REGISTRADO","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
                    }
                   
                        } 
                
                       
                    
                
                
            }else {
                JOptionPane.showMessageDialog(null, "RELLENE LOS CAMPOS","ERROR",JOptionPane.ERROR_MESSAGE);
            } 
           
        }else {
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS DATOS","ERROR",JOptionPane.ERROR_MESSAGE);
        
        }
        daoempleado.mostrarempleado(jtablaempleado);
        bloquearjtf(false, false, false, false, false);
        bloquearjbtn(true, false, false, false, false, true,false,false);
        limpiarjtf();
        
        //        String RUT = jtfrut.getText();
        //        Integer index= jtablaalumno.getSelectedRow();
        //
        //        if (validarrut(RUT)==true){
            //            if (guardar==true){ //GUARDO
                //                if (validarutduplicado("RUT", RUT,null)==true){ // BUSCA TODOS LOS RUT SI  NO ENCUENTRA CONCIDENCIA CON EL RUT INGRESADO (TRUE)
                    //                    // Limpiartabla();
                    //                    ///insert
                    //                    System.out.println("ruta"+rutaimagen);
                    //                    insertar();
                    //                    mostrar();
                    //                    jbtnguardar.setEnabled(false);
                    //                    jbtncancelar.setEnabled(false);
                    //
                    //                    habilitarjtext(false);
                    //                    limpiarjtext();
                    //                    //                jtfpuesto.setBackground(Color.WHITE);
                    //                    //            }
                //                //        else {
                    //                    //                JOptionPane.showMessageDialog(this,"EL PUESTO "+puesto+" YA SE ENCUENTRA REGISTRADO");
                    //                    //                jtfpuesto.requestFocus();
                    //                    //                jtfpuesto.setBackground(Color.RED);
                    //                    //            }
                //            } else {
                //                JOptionPane.showMessageDialog(this,"EL RUT INGRESADO YA SE ENCUENTRA REGISTRADO");
                //            }
            //        }else {
            //            //EDITO
            //            //              System.out.println("editar");
            //            if (validarutduplicado("RUTDUPLICADO", RUT, id)==true){// RUC DUPLICADO: BUSCA LOS RUC EN BD MENOS EL RUC QUE QUEREMOS EDITAR
                //                //            actualizarrubrospuesto(id,"PUESTO");
                //                Integer idS = Integer.parseInt(jtablaalumno.getValueAt(index,0).toString());
                //                editar(idS,fotoB);
                //                //Limpiartabla();
                //                mostrar();
                //                jbtnguardar.setEnabled(false);
                //                jbtncancelar.setEnabled(false);
                //                habilitarjtext(false);
                //                limpiarjtext();
                //            }else {
                //                JOptionPane.showMessageDialog(this,"EL RUT INGRESADO YA SE ENCUENTRA REGISTRADO");
                //            }
            //
            //        }
        //
        //        guardar=true;
        //        } else {
        //
        //            JOptionPane.showMessageDialog(this,"RUT INVALIDO");
        //            jtfrut.requestFocus();
        //        }
    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void jbtnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnewActionPerformed
        // TODO add your handling code here:
        bloquearjtf(true, true, true, true, true);
        bloquearjbtn(true, false, false, false, true, true,true,false);
        limpiarjtf();

        editar=false;
        //        jbtncancelar.setEnabled(true);
        //
        //        jbtneditar.setEnabled(false);
        //        guardar=false;
    }//GEN-LAST:event_jbtnnewActionPerformed

    private void jtfrutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrutFocusGained
        // TODO add your handling code here:
        if (jtfrut.getText().equals("R.U.T")){
            jtfrut.setText("");
        }
    }//GEN-LAST:event_jtfrutFocusGained

    private void jtfrutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrutFocusLost
        // TODO add your handling code here:
        if (jtfrut.getText().equals("")){
            jtfrut.setText("R.U.T");
        }
    }//GEN-LAST:event_jtfrutFocusLost

    private void jtfdireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdireccionFocusGained
        // TODO add your handling code here:
        if (jtfdireccion.getText().equals("DIRECCION")){
            jtfdireccion.setText("");
        }
    }//GEN-LAST:event_jtfdireccionFocusGained

    private void jtfdireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdireccionFocusLost
        // TODO add your handling code here:
        if (jtfdireccion.getText().equals("")){
            jtfdireccion.setText("DIRECCION");
        }
    }//GEN-LAST:event_jtfdireccionFocusLost

    private void jtfcelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcelularFocusGained
        // TODO add your handling code here:
        if (jtfcelular.getText().equals("CELULAR")){
            jtfcelular.setText("");
        }
    }//GEN-LAST:event_jtfcelularFocusGained

    private void jtfcelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcelularFocusLost
        // TODO add your handling code here:
        if (jtfcelular.getText().equals("")){
            jtfcelular.setText("CELULAR");
        }
    }//GEN-LAST:event_jtfcelularFocusLost

    private void jtfemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfemailFocusGained
        // TODO add your handling code here:
        if (jtfemail.getText().equals("EMAIL")){
            jtfemail.setText("");
        }
    }//GEN-LAST:event_jtfemailFocusGained

    private void jtfemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfemailFocusLost
        // TODO add your handling code here:
        if (jtfemail.getText().equals("")){
            jtfemail.setText("EMAIL");
        }
    }//GEN-LAST:event_jtfemailFocusLost

    private void jtfnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnombreFocusGained
        // TODO add your handling code here:
        if (jtfnombre.getText().equals("NOMBRES Y APELLIDOS")){
            jtfnombre.setText("");
        }
    }//GEN-LAST:event_jtfnombreFocusGained

    private void jtfnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnombreFocusLost
        // TODO add your handling code here:
        if (jtfnombre.getText().equals("")){
            jtfnombre.setText("NOMBRES Y APELLIDOS");
        }
    }//GEN-LAST:event_jtfnombreFocusLost

    private void jtfbuscarrutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarrutFocusGained
        // TODO add your handling code here:
        if (jtfbuscarrut.getText().equals("R.U.T")){
            jtfbuscarrut.setText("");
        }
    }//GEN-LAST:event_jtfbuscarrutFocusGained

    private void jtfbuscarrutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarrutFocusLost
        // TODO add your handling code here:
        if (jtfbuscarrut.getText().equals("")){
            jtfbuscarrut.setText("R.U.T");
        }
    }//GEN-LAST:event_jtfbuscarrutFocusLost

    private void jtfbuscarnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarnombreFocusGained
        // TODO add your handling code here:
        if (jtfbuscarnombre.getText().equals("NOMBRE Y APELLIDOS")){
            jtfbuscarnombre.setText("");
        }
    }//GEN-LAST:event_jtfbuscarnombreFocusGained

    private void jtfbuscarnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarnombreFocusLost
        // TODO add your handling code here:
        if (jtfbuscarnombre.getText().equals("")){
            jtfbuscarnombre.setText("NOMBRE Y APELLIDOS");
        }
    }//GEN-LAST:event_jtfbuscarnombreFocusLost

    private void jbtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditarActionPerformed
        // TODO add your handling code here:
        bloquearjtf(true, true, true,true, true);
        editar=true;
        bloquearjbtn(true, false, false, false, true, true,true,false);
    }//GEN-LAST:event_jbtneditarActionPerformed

    private void jbtnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfotoActionPerformed
        // TODO add your handling code here:
//         falumno falum = new falumno();
        Empleado empleado = new Empleado();
        System.out.println("idfoto"+id);
        empleado.setId_empleado(id);
    JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos png & jpg", "png", "jpg");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {                        
                try {
                    rutaimagen = chooser.getSelectedFile().getAbsolutePath();
                    File file = new File(rutaimagen);
                    byte[]  fotobys= Files.readAllBytes(file.toPath());
                    fotoB=fotobys;
                    
                    
                    Image icono=ImageIO.read(chooser.getSelectedFile()).getScaledInstance
                    (jlblImageUser.getWidth(),jlblImageUser.getHeight(),Image.SCALE_DEFAULT);
                    jlblImageUser.setIcon(new ImageIcon(icono));
                    jlblImageUser.updateUI();

                   validaguardar();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
                }
            }     
        
        
        
        
//        falumno falum = new falumno();
//        valumno valum = new valumno();
//        System.out.println("idfoto"+id);
//        valum.setIdalumno(id);
//        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//            "Archivos png & jpg", "png", "jpg");
//        chooser.setFileFilter(filter);
//        String userHome = System.getProperty( "user.home" );
//        chooser.setCurrentDirectory(new File(userHome));
//        chooser.setAcceptAllFileFilterUsed(false);
//        int retrival = chooser.showOpenDialog(null);
//        if (retrival == JFileChooser.APPROVE_OPTION) {
//            try {
//                rutaimagen = chooser.getSelectedFile().getAbsolutePath();
//                File file = new File(rutaimagen);
//                byte[]  fotobys= Files.readAllBytes(file.toPath());
//                fotoB=fotobys;
//
//                Image icono=ImageIO.read(chooser.getSelectedFile()).getScaledInstance
//                (jlblImageUser2.getWidth(),jlblImageUser2.getHeight(),Image.SCALE_DEFAULT);
//                jlblImageUser2.setIcon(new ImageIcon(icono));
//                jlblImageUser2.updateUI();
//
//                if (validarcamposobligatiorios()==true){
//                    jbtnguardar.setEnabled(true);
//                }else {
//                    jbtnguardar.setEnabled(false);
//                }
//            } catch (IOException ex) {
//                JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
//            }
//        }

        
////////////////////////////////////////////////////////////////////////////////////////////////////////    
        
        
        
        //            try {
            ////                rutaimagen = chooser.getSelectedFile().getAbsolutePath();
            //
            //
            ////                falum.actualizarImagenUsuario(valum, rutaimagen);
            ////                falum.obtenerImagenUsuario(jlblImageUser2, valum);
            ////                falum.obtenerImagenUsuario(guiInterfaz.getJlblImage(), valum);
            //            } catch (Exception ex) {
            //                System.err.println("Error al abrir el archivo: " +ex.getMessage());
            //            }

    }//GEN-LAST:event_jbtnfotoActionPerformed

    private void jbtngeneracarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngeneracarnetActionPerformed
        // TODO add your handling code here:
        GeneraCarnet carnet= new GeneraCarnet();

        String rutsinguion= carnet.formatoruccarne(jtfrut.getText());
        System.out.println("rutsinguion "+rutsinguion);
        String rutconguion = jtfrut.getText();
        String nombre= jtfnombre.getText().replaceAll("\\s","");
        carnet.generarcarnet("CARNÉ DE IDENTIFICACIÓN", nombre, "----", fotoB, "E:\\"+nombre+"-"+rutconguion+".pdf",rutsinguion );
            JOptionPane.showMessageDialog(this,"CARNÉ GENERADO EXITOSAMENTE");
    }//GEN-LAST:event_jbtngeneracarnetActionPerformed

    private void jtfbuscarrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarrutKeyReleased
        // TODO add your handling code here:
        String rut= jtfbuscarrut.getText().trim();
        daoempleado.busquedasensitivaempleado(jtablaempleado,"RUT",rut);
    }//GEN-LAST:event_jtfbuscarrutKeyReleased

    private void jtfbuscarnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarnombreKeyReleased
        // TODO add your handling code here:
          String nombre=jtfbuscarnombre.getText().trim().toUpperCase();
        daoempleado.busquedasensitivaempleado(jtablaempleado,"NOMBRE", nombre);
    }//GEN-LAST:event_jtfbuscarnombreKeyReleased

    private void jtablaempleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaempleadoMouseReleased
        // TODO add your handling code here:
         Empleado empleado = null;
        id = Long.parseLong(jtablaempleado.getValueAt(jtablaempleado.getSelectedRow(), 0).toString());
        empleado = daoempleado.buscarempleado("ID", id,jlblImageUser);    
        jtfnombre.setText(empleado.getNombre());
        jtfrut.setText(empleado.getRut());
        jtfcelular.setText(empleado.getCelular());
        jtfdireccion.setText(empleado.getDireccion());
        jtfemail.setText(empleado.getEmail());
        fotoB= empleado.getFoto();
        bloquearjbtn(true, true, false, true, false, true,false,true);
    }//GEN-LAST:event_jtablaempleadoMouseReleased

    private void jtfnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnombreKeyReleased
        // TODO add your handling code here:
         validaguardar();
        
    }//GEN-LAST:event_jtfnombreKeyReleased

    private void jtfrutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrutKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfrutKeyReleased

    private void jtfcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfcelularActionPerformed

    private void jtfcelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcelularKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfcelularKeyReleased

    private void jtfdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdireccionKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfdireccionKeyReleased

    private void jtfemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfemailKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfemailKeyReleased

    private void jtablaempleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablaempleadoKeyReleased
        // TODO add your handling code here:
        jtablaempleadoMouseReleased(null);
    }//GEN-LAST:event_jtablaempleadoKeyReleased

    private void jtfnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnombreKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfnombre);
    }//GEN-LAST:event_jtfnombreKeyTyped

    private void jtfrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrutKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfrut);
    }//GEN-LAST:event_jtfrutKeyTyped

    private void jtfdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdireccionKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfdireccion);
    }//GEN-LAST:event_jtfdireccionKeyTyped

    private void jtfemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfemailKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfemail);
    }//GEN-LAST:event_jtfemailKeyTyped

    private void jtfbuscarnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarnombreKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfbuscarnombre);
    }//GEN-LAST:event_jtfbuscarnombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JButton jbtneditar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JButton jbtnfoto;
    private javax.swing.JButton jbtngeneracarnet;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JButton jbtnnew;
    private javax.swing.JLabel jlblImageUser;
    private javax.swing.JTable jtablaempleado;
    private javax.swing.JTextField jtfbuscarnombre;
    private javax.swing.JTextField jtfbuscarrut;
    private javax.swing.JTextField jtfcelular;
    private javax.swing.JTextField jtfdireccion;
    private javax.swing.JTextField jtfemail;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JTextField jtfrut;
    // End of variables declaration//GEN-END:variables
}
