/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.ComprasDAO;
import Pojos.Compras;
import Pojos.Proveedor;
import Pojos.SucursalSingleton;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JIFIngresoProdPendiente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFIngresoProdPendiente
     */
    Proveedor proveedor= new Proveedor();
    ComprasDAO daocompras = new ComprasDAO(); 
    SucursalSingleton sucursal= SucursalSingleton.getinstancia();
    List<Compras> listcompra= new ArrayList<>();
    Compras compra;
     int posx;
    int posy;
     public JIFIngresoProdPendiente() {
        initComponents();
//        listcompra=daocompras.pendientes(jtablatodo, sucursal.getId());
        jlblmensajecarga.setVisible(false);
        buscar();
    }
     
     public void buscar(){
      Runnable runnable = new Runnable() {

        @Override
        public void run() {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       jlblimagencarga.setVisible(true);
       jlblletracarga.setVisible(true);
      listcompra=daocompras.busquedasensitivapendientes(jtablatodo, sucursal.getId(), jtfbuscar.getText().toUpperCase());
      jlblimagencarga.setVisible(false);
      jlblletracarga.setVisible(false);
     }
       
         
        };
        Thread T = new Thread(runnable);
        T.start();
     }
     public synchronized void  verdet(){
     
        if(jtablatodo.getSelectedRow()>=0){
                jlblmensajecarga.setVisible(true);
                jlblmensajecarga.setText("Cargando detalle ...");
                System.out.println("size"+ listcompra.size());
                compra=listcompra.get(jtablatodo.getSelectedRow());
                JDDetalleCompra detalle = new JDDetalleCompra(new Frame(), isVisible(),compra);
                 jlblmensajecarga.setVisible(false);
                detalle.setVisible(true);
            
            }else {
                
                JOptionPane.showMessageDialog(null, "Seleccione Comprobante");
            }
           
        }
//    public void setproveedor(Proveedor proveedor){
//    this.proveedor= proveedor;
//    jlblproveedor.setText(proveedor.getNombrerazons());
//    jlblrut.setText(proveedor.getRut());
//    daocompras.pendientesporproveedor(jtablaproveedor, sucursal.getId(), proveedor.getIdproveedor());
//    jbtnimprimir.setEnabled(true);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblletracarga = new javax.swing.JLabel();
        jlblimagencarga = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablatodo = new javax.swing.JTable();
        jbtnimprirtodo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtfbuscar = new javax.swing.JTextField();
        jlblmensajecarga = new javax.swing.JLabel();
        jbtnver = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(220, 151, 96));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOCUMENTOS CON PRODUCTOS PENDIENTES POR ENTREGAR");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarblanco.png"))); // NOI18N
        jLabel8.setToolTipText("Cerrar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, -1));

        jlblletracarga.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblletracarga.setForeground(new java.awt.Color(0, 0, 0));
        jlblletracarga.setText("Cargando Registros ...");
        getContentPane().add(jlblletracarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jlblimagencarga.setBackground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setForeground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblimagencarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        getContentPane().add(jlblimagencarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 970, 290));

        jtablatodo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtablatodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtablatodo.setToolTipText("");
        jtablatodo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtablatodo.getTableHeader().setReorderingAllowed(false);
        jtablatodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablatodoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtablatodo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, 1110, 330));

        jbtnimprirtodo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnimprirtodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jbtnimprirtodo.setText("Imprimir");
        jbtnimprirtodo.setToolTipText("Imprimir");
        jbtnimprirtodo.setBorder(null);
        jbtnimprirtodo.setBorderPainted(false);
        jbtnimprirtodo.setContentAreaFilled(false);
        jbtnimprirtodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprirtodoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnimprirtodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        jLabel4.setText("Doc. Numero / Proveedor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, -1, -1));

        jtfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbuscarActionPerformed(evt);
            }
        });
        jtfbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtfbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 80, 580, -1));

        jlblmensajecarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loading4.gif"))); // NOI18N
        jlblmensajecarga.setText("jLabel1");
        getContentPane().add(jlblmensajecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 200, -1));

        jbtnver.setBackground(new java.awt.Color(255, 255, 255));
        jbtnver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view25px.png"))); // NOI18N
        jbtnver.setText("Ver");
        jbtnver.setToolTipText("Ver detalle");
        jbtnver.setBorder(null);
        jbtnver.setBorderPainted(false);
        jbtnver.setContentAreaFilled(false);
        jbtnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnverActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnimprirtodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprirtodoActionPerformed
        // TODO add your handling code here:
        
        
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                jlblmensajecarga.setVisible(true);
                jlblmensajecarga.setText("Imprimiendo ...");
                daocompras.imprimir(sucursal.getId());
                jlblmensajecarga.setVisible(false);
            }
        };
        Thread T = new Thread(runnable);
        T.start();
    }//GEN-LAST:event_jbtnimprirtodoActionPerformed

    private void jtfbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarKeyReleased
        // TODO add your handling code here:
//        listcompra=daocompras.busquedasensitivapendientes(jtablatodo, sucursal.getId(), jtfbuscar.getText().toUpperCase());
    }//GEN-LAST:event_jtfbuscarKeyReleased

    private void jtablatodoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablatodoMouseReleased
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jtablatodoMouseReleased

    private void jtfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbuscarActionPerformed
        // TODO add your handling code here:
         buscar();
    }//GEN-LAST:event_jtfbuscarActionPerformed

    private void jbtnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnverActionPerformed
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                verdet();
            }
        };
        Thread T = new Thread(runnable);
        T.start();
            
        
              // TODO add your handling code here:
    }//GEN-LAST:event_jbtnverActionPerformed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
          posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
         int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel4MouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnimprirtodo;
    private javax.swing.JButton jbtnver;
    private javax.swing.JLabel jlblimagencarga;
    private javax.swing.JLabel jlblletracarga;
    private javax.swing.JLabel jlblmensajecarga;
    private javax.swing.JTable jtablatodo;
    private javax.swing.JTextField jtfbuscar;
    // End of variables declaration//GEN-END:variables
}
