/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.DetalleMermaDAO;
import DAO.MermaDAO;
import DAO.ProductoDAO;
import Pojos.DetalleMerma;
import Pojos.Merma;
import Pojos.Producto;
import Pojos.SucursalSingleton;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author info2017
 */
public class JIFMerma extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFMerma
     */
    Producto producto = new Producto();
    ProductoDAO daoproducto= new ProductoDAO();
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    Merma merma= new Merma();
    DetalleMerma detallemerma=new DetalleMerma();
    MermaDAO daomerma= new MermaDAO();
    DetalleMermaDAO daodetallemerma= new DetalleMermaDAO();
    Mayusculas mayus = new Mayusculas();
     DefaultTableModel modelo= new DefaultTableModel(){
    public boolean isCellEditable(int row, int column) {
    //      if (column == 5) return true;
    //else
    return false;
}
  }; 
    public JIFMerma() {
        initComponents();
        String titulos[]={"IDDET","ID","CODIGO","DESCRIPCION","CANTIDAD"};
        modelo.setColumnIdentifiers(titulos);
        jtabla.setModel(modelo);
        jtabla.getColumnModel().getColumn(0).setMaxWidth(0);
        jtabla.getColumnModel().getColumn(0).setMinWidth(0);
        jtabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        
        jtabla.getColumnModel().getColumn(1).setMaxWidth(0);
        jtabla.getColumnModel().getColumn(1).setMinWidth(0);
        jtabla.getColumnModel().getColumn(1).setPreferredWidth(0);
 
 
    }
    public void validaingreso(){
    if(producto.getIdproducto()!=0 && Double.parseDouble(jtfcantidad.getValue().toString())>0 
            && jdpfecha.getDate()!=null && jtamotivo.getText().replaceAll("\\s","").length()>0 
            && !jtamotivo.getText().equals("MOTIVO") ){
    jbtnagregar.setEnabled(true);
    }else {
    jbtnagregar.setEnabled(false);
    }
    
    }
    public void nuevoprod(){
    producto= new Producto();
    jtfcantidad.setValue(0);
    jtfproducto.setText("");
    jtfcodigo.setText("CODIGO");
    
    }
    public void validaaceptar(){
     
    if(jdpfecha.getDate()!=null && jtamotivo.getText().replaceAll("\\s","").length()>0 &&
            modelo.getRowCount() > 0  && !jtamotivo.getText().equals("MOTIVO")){
    jbtnaceptar.setEnabled(true);
    
    }else {
    jbtnaceptar.setEnabled(false);
    
    }
  
    }
    public void nuevamerma(){
    merma = new Merma();
//    producto= new Producto();
    modelo= new DefaultTableModel(){
    public boolean isCellEditable(int row, int column) {
    //      if (column == 5) return true;
    //else
    return false;
    }
    }; 
    String titulos[]={"IDDET","ID","CODIGO","DESCRIPCION","CANTIDAD"};
    modelo.setColumnIdentifiers(titulos);
    jtabla.setModel(modelo);
    jtabla.getColumnModel().getColumn(0).setMaxWidth(0);
    jtabla.getColumnModel().getColumn(0).setMinWidth(0);
    jtabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        
    jtabla.getColumnModel().getColumn(1).setMaxWidth(0);
    jtabla.getColumnModel().getColumn(1).setMinWidth(0);
    jtabla.getColumnModel().getColumn(1).setPreferredWidth(0);
    jdpfecha.setDate(null);
    jtamotivo.setText("MOTIVO");
    nuevoprod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdpfecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jtfcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfproducto = new javax.swing.JTextField();
        jbtnagregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfcantidad = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtamotivo = new javax.swing.JTextArea();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jlblimagen = new javax.swing.JLabel();
        jbtnaceptar = new javax.swing.JButton();
        jbtnsalir = new javax.swing.JButton();

        setTitle("INGRESO DE MERMAS");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdpfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpfechaActionPerformed(evt);
            }
        });
        jPanel1.add(jdpfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FECHA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jtabla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla.getTableHeader().setReorderingAllowed(false);
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 254, 900, 253));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfcodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfcodigo.setText("CODIGO");
        jtfcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfcodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfcodigoFocusLost(evt);
            }
        });
        jtfcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcodigoKeyReleased(evt);
            }
        });
        jPanel2.add(jtfcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("PRODUCTO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 20));

        jtfproducto.setEnabled(false);
        jPanel2.add(jtfproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 350, -1));

        jbtnagregar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnagregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnagregar.setText("AGREGAR");
        jbtnagregar.setEnabled(false);
        jbtnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnagregarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CANTIDAD:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));

        jtfcantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfcantidadActionPerformed(evt);
            }
        });
        jtfcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcantidadKeyReleased(evt);
            }
        });
        jPanel2.add(jtfcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 120, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 700, 112));

        jtamotivo.setColumns(20);
        jtamotivo.setRows(5);
        jtamotivo.setText("MOTIVO");
        jtamotivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtamotivoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtamotivoFocusLost(evt);
            }
        });
        jtamotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtamotivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtamotivoKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtamotivo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 700, 70));

        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelNice1.add(jlblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 130));

        jPanel1.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 180, 154));

        jbtnaceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept2.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.setEnabled(false);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 517, -1, -1));

        jbtnsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jbtnsalir.setText("Cancelar");
        jbtnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 517, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcodigoKeyReleased
        // TODO add your handling code here:
           String codigo= jtfcodigo.getText().replaceAll("\\s", "");
        if(codigo.length()>=10){
            producto=daoproducto.buscarproducto("CODIGO", 0,sucursalsingleton.getId(), jlblimagen, codigo);
           // jtfcodigo.setText(producto.getCodigo());
//            jtfstock.setValue((producto.getCantidad()));
            jtfproducto.setText(producto.getDescripcion());
        
        }
        
    }//GEN-LAST:event_jtfcodigoKeyReleased

    private void jbtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnagregarActionPerformed
        // TODO add your handling code here:
         List<Object> returdetorden= new ArrayList<>();
//        long iddet=0;
//        boolean valida=false;
        if(merma.getId_merma()==0){
          /// INSERT MERMA
            merma.setFecha(new java.sql.Date(jdpfecha.getDate().getTime()));
            merma.setMotivo(jtamotivo.getText());
            merma.setId_merma(daomerma.insertar(merma));//insert
           ////// INSERT DETALLE
            detallemerma.setCantidad(Double.parseDouble(jtfcantidad.getValue().toString()));
            detallemerma.setIdproducto(producto.getIdproducto());
            detallemerma.setIdmerma(merma.getId_merma());
            
            returdetorden=daodetallemerma.insertar(detallemerma);
            
        }else {
           ////// INSERT DETALLE
            detallemerma.setCantidad(Double.parseDouble(jtfcantidad.getValue().toString()));
            detallemerma.setIdproducto(producto.getIdproducto());
            detallemerma.setIdmerma(merma.getId_merma());
            
            returdetorden=daodetallemerma.insertar(detallemerma);
        }
//        System.out.println("valida"+valida);
        if(Boolean.parseBoolean(returdetorden.get(0).toString())==true){
             Object[] miarray = new Object[5];
                    miarray[0]=returdetorden.get(1);
                    miarray[1]=producto.getIdproducto();
                    miarray[2]=producto.getCodigo();
                    miarray[3]=producto.getDescripcion();
                    miarray[4]=jtfcantidad.getValue();
                   
                   
        
                    modelo.addRow(miarray);
            
                   nuevoprod();
        
        }
        jbtnagregar.setEnabled(true);
        jdpfecha.setEnabled(false);
        jtamotivo.setEnabled(false);
        validaaceptar();
    }//GEN-LAST:event_jbtnagregarActionPerformed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
               int index= jtabla.getSelectedRow();
        if(index >=0){
            if(evt.getClickCount()==2){

                if(index>=0){
                    if (JOptionPane.showConfirmDialog(null,"ESTA SEGURO DE RETIRAR EL PRODUCTO","SISTEMA",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                        DetalleMerma detmerma= new DetalleMerma();

                        detmerma.setIddetallemerma(Long.parseLong(modelo.getValueAt(index, 0).toString()));
                        detmerma.setIdproducto(Long.parseLong(modelo.getValueAt(index, 1).toString()));
                        detmerma.setCantidad(Double.parseDouble(modelo.getValueAt(index, 4).toString()));
                        daodetallemerma.eliminar(detmerma);
                        modelo.removeRow(index);
                        
                    }

                }

            }
            validaaceptar();
        }
    }//GEN-LAST:event_jtablaMouseReleased

    private void jbtnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsalirActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null, "SEGURO DE CERRAR LA VENTANA INGRESO DE MERMA, SE PERDERAN LOS DATOS INGRESADOS","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           
//            if(modelo.getRowCount()>0){
             
              DetalleMerma detmerma= new DetalleMerma();
              int cont=0;
             System.out.println("modelorow"+modelo.getRowCount()); 
                for(int i=0;i<=modelo.getRowCount()-1;i++){
                    cont++;
                    detmerma.setIddetallemerma(Long.parseLong(modelo.getValueAt(i, 0).toString()));
                    detmerma.setIdproducto(Long.parseLong(modelo.getValueAt(i, 1).toString()));
                    detmerma.setCantidad(Double.parseDouble(modelo.getValueAt(i, 4).toString()));
                    daodetallemerma.eliminar(detmerma);
//                    //modelo.removeRow(i);
//                    cont++;
//            }           
            }
                if(merma.getId_merma()!=0){
                    daomerma.eliminar(merma.getId_merma());
                
                }
              
            
            this.dispose();
        
        }
    }//GEN-LAST:event_jbtnsalirActionPerformed

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        nuevamerma();
        JOptionPane.showMessageDialog(null, "INGRESADO CORRECTAMENTE");
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfcodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcodigoFocusGained
        // TODO add your handling code here:
        if(jtfcodigo.getText().equals("CODIGO")){
        jtfcodigo.setText("");
        }
    }//GEN-LAST:event_jtfcodigoFocusGained

    private void jtfcodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcodigoFocusLost
        // TODO add your handling code here:
        if(jtfcodigo.getText().equals("")){
         jtfcodigo.setText("CODIGO");
        
        }
    }//GEN-LAST:event_jtfcodigoFocusLost

    private void jtamotivoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtamotivoFocusGained
        // TODO add your handling code here:
        if(jtamotivo.getText().equals("MOTIVO")){
        jtamotivo.setText("");
        
        }
    }//GEN-LAST:event_jtamotivoFocusGained

    private void jtamotivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtamotivoFocusLost
        // TODO add your handling code here:
        if(jtamotivo.getText().equals("")){
        jtamotivo.setText("MOTIVO");
               
        }
    }//GEN-LAST:event_jtamotivoFocusLost

    private void jdpfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpfechaActionPerformed
        // TODO add your handling code here:
        validaaceptar();
        validaingreso();
    }//GEN-LAST:event_jdpfechaActionPerformed

    private void jtamotivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtamotivoKeyReleased
        // TODO add your handling code here:
         validaaceptar();
         validaingreso();
    }//GEN-LAST:event_jtamotivoKeyReleased

    private void jtfcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfcantidadKeyReleased

    private void jtfcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfcantidadActionPerformed
        // TODO add your handling code here:
        validaingreso();
         validaaceptar();
    }//GEN-LAST:event_jtfcantidadActionPerformed

    private void jtamotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtamotivoKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayusTA(jtamotivo);
    }//GEN-LAST:event_jtamotivoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JButton jbtnagregar;
    private javax.swing.JButton jbtnsalir;
    private org.jdesktop.swingx.JXDatePicker jdpfecha;
    private javax.swing.JLabel jlblimagen;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextArea jtamotivo;
    private javax.swing.JFormattedTextField jtfcantidad;
    private javax.swing.JTextField jtfcodigo;
    private javax.swing.JTextField jtfproducto;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
}
