/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.DetalleOrdenEntradaDAO;
import DAO.OrdenEntradaDAO;
import DAO.OrdenSalidaDAO;
import DAO.ProductoDAO;
import DAO.SucursalDAO;
import Pojos.DetalleOrdeSalidaEntrada;
import Pojos.OrdenSalidaEntrada;
import Pojos.Producto;
import Pojos.SucursalSingleton;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author info2017
 */
public class JIFOrdenEntrada extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFOrdenEntrada
     */
      ProductoDAO  daoproducto= new ProductoDAO();
    Producto producto= new Producto();
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    SucursalDAO daosucursal= new SucursalDAO();
    DefaultTableModel modelo= new DefaultTableModel(){
    public boolean isCellEditable(int row, int column) {
    //      if (column == 5) return true;
    //else
    return false;
}
  }; 
    DetalleOrdeSalidaEntrada detorden = new DetalleOrdeSalidaEntrada();
    OrdenSalidaEntrada orden = new OrdenSalidaEntrada();
    OrdenEntradaDAO daoorden = new OrdenEntradaDAO();
    OrdenSalidaDAO daoordensalida = new OrdenSalidaDAO();
    DetalleOrdenEntradaDAO daodetorden = new DetalleOrdenEntradaDAO();
    Mayusculas mayus = new Mayusculas();
    List<DetalleOrdeSalidaEntrada> listadet = new ArrayList<DetalleOrdeSalidaEntrada>();
    long idordensalida; 
     int posx;
    int posy;
    public JIFOrdenEntrada() {
        initComponents();
        String titulos[]={"CODIGO","DESCRIPCION","CANTIDAD"};
        modelo.setColumnIdentifiers(titulos);
        jtabla.setModel(modelo);
        //////////
         TableColumnModel columnModel = jtabla.getColumnModel();
     
        columnModel.getColumn(0).setPreferredWidth(90);
        columnModel.getColumn(1).setPreferredWidth(600);
        columnModel.getColumn(2).setPreferredWidth(50);
//        daosucursal.llenarcombo(jcbsucursal);
//        jlblsucursalrecep.setText(sucursalsingleton.getNombre());
//        jbtnagregar.setEnabled(false);
        jbtnaceptar.setEnabled(false);
    }
//    public void validaagregar(){
//        String autori= jtfautorizado.getText().replace("\\s", "");
//        String reci = jtfrecibido.getText().replace("\\s", "");
//        try {
//            if (producto.getIdproducto()!=0 && Integer.parseInt(jtfcantidad.getValue().toString())>0
//            && jcbsucursal.getSelectedIndex()>0 && jdfechaentrega.getDate()!=null && jdfechapedido.getDate()!=null
//            && autori.length() >0 && reci.length() > 0){
//        jbtnagregar.setEnabled(true);
//    
//    }else {
//        jbtnagregar.setEnabled(false);
//    }
//            
//        } catch (NullPointerException e) {
//         jbtnagregar.setEnabled(false);
//        }
//    
//    
//    }
//    public void enableencabezado(boolean val){
//        jdfechaentrega.setEnabled(val);
//        jdfechapedido.setEnabled(val);
//        jcbsucursal.setEnabled(val);
//        jtfautorizado.setEnabled(val);
//        jtfrecibido.setEnabled(val);
//    
//    }
//    public void nuevoprod(){
//        jtfcodigo.setText("");
//        jtfstock.setValue(0);
//        jtfcantidad.setValue(0);
//        jlblproducto.setText(". . .");
//        jbtnagregar.setEnabled(false);
//        jlblimagen.setIcon(null);
//        producto = new Producto();
//        ///// enable orden /////
//        enableencabezado(false);
//    
//    }
    public void nuevoorden(){
//        jtfcodigo.setText("");
//        jtfstock.setValue(0);
//        jtfcantidad.setValue(0);
//        jlblproducto.setText(". . .");
//        jbtnagregar.setEnabled(false);
//        jlblimagen.setIcon(null);
        jdfechaentrega.setDate(null);
        jdfechapedido.setDate(null);
        jlblsucursalrecep.setText("* * *");
        jlblsurcursalenvia.setText("* * *");
        producto = new Producto();
        orden = new OrdenSalidaEntrada();
        jtfautorizado.setText("");
        jtfrecibido.setText("");
//         enableencabezado(true);
        ////////////// /////////////// 
         for (int i = 0; i < jtabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
            }
        
        /////////////////76
        listadet = new ArrayList<>();
        jbtnaceptar.setEnabled(false);
        ////////////////////////////////////////////   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdfechapedido = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdfechaentrega = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jlblsucursalrecep = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jtfautorizado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfrecibido = new javax.swing.JTextField();
        jbtnaceptar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtfnumeroorden = new javax.swing.JFormattedTextField();
        jlblsurcursalenvia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtamensaje = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jbtnsalir = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jdfechapedido.setEnabled(false);
        jdfechapedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdfechapedidoActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha del Pedido:");

        jLabel6.setText("Fecha de Entrega:");

        jdfechaentrega.setEnabled(false);
        jdfechaentrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdfechaentregaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("SUCURSAL QUE ENVIA:");

        jlblsucursalrecep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblsucursalrecep.setText("* * *");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("SUCURSAL QUE RECEPCIONA:");

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla.getTableHeader().setReorderingAllowed(false);
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jLabel8.setText("AUTORIZADO POR:");

        jtfautorizado.setEnabled(false);
        jtfautorizado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfautorizadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfautorizadoKeyTyped(evt);
            }
        });

        jLabel9.setText("RECIBIDO POR:");

        jtfrecibido.setEnabled(false);
        jtfrecibido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfrecibidoMousePressed(evt);
            }
        });
        jtfrecibido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfrecibidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfrecibidoKeyTyped(evt);
            }
        });

        jbtnaceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save20x20.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.setBorderPainted(false);
        jbtnaceptar.setContentAreaFilled(false);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });

        jLabel10.setText("Ingrese N° de Orden de Salida:");

        jtfnumeroorden.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfnumeroorden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfnumeroordenMousePressed(evt);
            }
        });
        jtfnumeroorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnumeroordenActionPerformed(evt);
            }
        });
        jtfnumeroorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfnumeroordenKeyReleased(evt);
            }
        });

        jlblsurcursalenvia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblsurcursalenvia.setText("* * *");

        jtamensaje.setEditable(false);
        jtamensaje.setColumns(20);
        jtamensaje.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jtamensaje.setRows(5);
        jScrollPane2.setViewportView(jtamensaje);

        jPanel7.setBackground(new java.awt.Color(220, 151, 96));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ORDEN DE ENTRADA");

        jbtnsalir.setBackground(new java.awt.Color(255, 255, 255));
        jbtnsalir.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jbtnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarblanco.png"))); // NOI18N
        jbtnsalir.setBorderPainted(false);
        jbtnsalir.setContentAreaFilled(false);
        jbtnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnsalir)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfautorizado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnaceptar)
                        .addGap(125, 125, 125))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)
                                .addGap(50, 50, 50)
                                .addComponent(jtfnumeroorden, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addGap(15, 15, 15)
                                .addComponent(jdfechapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)
                                .addComponent(jdfechaentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1)
                                .addGap(12, 12, 12)
                                .addComponent(jlblsurcursalenvia, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jlblsucursalrecep, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfnumeroorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdfechapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdfechaentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblsurcursalenvia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblsucursalrecep, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbtnaceptar)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jtfautorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jtfrecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdfechapedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdfechapedidoActionPerformed
        // TODO add your handling code here:
//        validaagregar();
    }//GEN-LAST:event_jdfechapedidoActionPerformed

    private void jdfechaentregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdfechaentregaActionPerformed
        // TODO add your handling code here:
//        validaagregar();
    }//GEN-LAST:event_jdfechaentregaActionPerformed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
//        int index= jtabla.getSelectedRow();
//        if(index >=0){
//            if(evt.getClickCount()==2){
//
//                if(index>=0){
//                    if (JOptionPane.showConfirmDialog(null,"ESTA SEGURO DE RETIRAR EL PRODUCTO","",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
//                        DetalleOrdeSalidaEntrada detorden= new DetalleOrdeSalidaEntrada();
//
//                       index=jtabla.getSelectedRow();
//                       modelo.removeRow(index);
//                       listadet.remove(index);
//
//                    }
//
//                }
//
//            }
//
//        }
    }//GEN-LAST:event_jtablaMouseReleased

    private void jtfautorizadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfautorizadoKeyReleased
        // TODO add your handling code here:
//        validaagregar();
    }//GEN-LAST:event_jtfautorizadoKeyReleased

    private void jtfautorizadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfautorizadoKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayus(jtfautorizado);
//        validaagregar();
    }//GEN-LAST:event_jtfautorizadoKeyTyped

    private void jtfrecibidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfrecibidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfrecibidoMousePressed

    private void jtfrecibidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrecibidoKeyReleased
        // TODO add your handling code here:}
//        validaagregar();
    }//GEN-LAST:event_jtfrecibidoKeyReleased

    private void jtfrecibidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfrecibidoKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayus(jtfrecibido);
//        validaagregar();
    }//GEN-LAST:event_jtfrecibidoKeyTyped

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:      
//        orden.setFecha_pedido(new java.sql.Timestamp(jdfechapedido.getDate().getTime()));
//        orden.setFecha_entrega(new java.sql.Timestamp(jdfechaentrega.getDate().getTime()));
//        orden.setSucurenvia(jcbsucursal.getSelectedItem().toString());
//        orden.setSucursolicita(jlblsucursal.getText());
//        orden.setAutorizado(jtfautorizado.getText());
//        orden.setRecibido(jtfrecibido.getText());
        orden.setTipoop("ENTRADA");
        idordensalida= orden.getIdordensalidaentrada();
        orden.setIdordensalidaentrada(daoorden.insertar(orden,idordensalida));
        System.out.println("idc"+orden.getIdordensalidaentrada());
        daodetorden.insertar(listadet,orden.getIdordensalidaentrada(),sucursalsingleton.getId(),jtamensaje,jbtnsalir);
//        daoorden.imprimir(orden.getIdordensalidaentrada());
        nuevoorden();      
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jbtnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsalirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "SEGURO DE CERRAR LA VENTANA ORDEN DE ENTRADA, SE PERDERAN LOS DATOS INGRESADOS","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jbtnsalirActionPerformed

    private void jtfnumeroordenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfnumeroordenMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnumeroordenMousePressed

    private void jtfnumeroordenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfnumeroordenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnumeroordenKeyReleased

    private void jtfnumeroordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnumeroordenActionPerformed
        // TODO add your handling code here:
        long idorden = Long.parseLong(jtfnumeroorden.getValue().toString());
        orden= daoordensalida.buscar(idorden,sucursalsingleton.getId(), jtabla,listadet,jbtnaceptar);
        jdfechaentrega.setDate(orden.getFecha_entrega());
        jdfechapedido.setDate(orden.getFecha_pedido());
        jtfautorizado.setText(orden.getAutorizado());
        jtfrecibido.setText(orden.getRecibido());
        jlblsucursalrecep.setText(orden.getSucursolicita());
        jlblsurcursalenvia.setText(orden.getSucurenvia());
//        jtabla.setModel(modelo);
        
    }//GEN-LAST:event_jtfnumeroordenActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
         posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
         int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
        int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
        posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel7MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JButton jbtnsalir;
    private org.jdesktop.swingx.JXDatePicker jdfechaentrega;
    private org.jdesktop.swingx.JXDatePicker jdfechapedido;
    private javax.swing.JLabel jlblsucursalrecep;
    private javax.swing.JLabel jlblsurcursalenvia;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextArea jtamensaje;
    private javax.swing.JTextField jtfautorizado;
    private javax.swing.JFormattedTextField jtfnumeroorden;
    private javax.swing.JTextField jtfrecibido;
    // End of variables declaration//GEN-END:variables
}
