/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.ReparacionDAO;
import DAO.SucursalDAO;
import Pojos.Cliente;
import Pojos.Reparacion;
import Pojos.Sucursal;
import Pojos.SucursalSingleton;
import java.awt.Frame;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JIFrmReparacionConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmReparacionConsultar
     */
    ReparacionDAO daoreparacion= new ReparacionDAO();
    Cliente cliente = new Cliente();
    List<Reparacion> listreparacli=new ArrayList<>();
     List<Reparacion> listreparatecni=new ArrayList<>();
    Reparacion repara;
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    SucursalDAO daosucursal = new SucursalDAO();
    List<Sucursal> listsucur;
    List<Reparacion> listrepara;
    Sucursal sucursal;
     int posx;
    int posy;
    public JIFrmReparacionConsultar() {
        initComponents();
//        listrepara=daoreparacion.mostrar(jtabla,  jlbltotal,"todo",0);
       jdpdesde.setDate(new Date());
       jdphasta.setDate(new Date());
        
//        jbtnimprimir.setEnabled(false);
//        jbtnimprimirtodo.setEnabled(false);
        refrescar();
    }
    
    
    
//    public void setcliente(Cliente cliente){
//        this.cliente=cliente;
//        jlblcliente.setText(cliente.getNombre_razons());
//        jlblrut.setText(cliente.getRut());
//       listreparacli= daoreparacion.mostrarporcliente(jtablacliente,  cliente.getId_cliente(),jlblmsjcliente,jlbltotalclient);
//        jbtnimprimirtodo.setEnabled(true);
//    }
    
    public void refrescar(){
    Runnable runnable = new Runnable() {

        @Override
        public void run() {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        jlblimagencarga.setVisible(true);
        jlblletracarga.setVisible(true);
        jtfbuscar.setEnabled(false);
        jcbsucursal.setEnabled(false);
        if(listsucur == null){
        listsucur=daosucursal.llenarcombo(jcbsucursal);
        }
        
         if(jcbsucursal.getSelectedIndex()==0){
              listrepara=daoreparacion.busquedasensitiva(jtabla, sucursalsingleton.getId(), jlbltotal, 
                      jtfbuscar.getText().toUpperCase(),"todo",0,new Timestamp(jdpdesde.getDate().getTime()),new Timestamp(jdphasta.getDate().getTime()));
              
         }else {
              sucursal=listsucur.get(jcbsucursal.getSelectedIndex());
              listrepara=daoreparacion.busquedasensitiva(jtabla, sucursal.getId() ,jlbltotal, jtfbuscar.getText().toUpperCase(),"sucursal",0
              ,new Timestamp(jdpdesde.getDate().getTime()),new Timestamp(jdphasta.getDate().getTime()));

         }
        jlblimagencarga.setVisible(false);
        jlblletracarga.setVisible(false);
        jtfbuscar.setEnabled(true);
        jcbsucursal.setEnabled(true);
      }
    };
    Thread T = new Thread(runnable);
    T.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfbuscar = new javax.swing.JTextField();
        jlblletracarga = new javax.swing.JLabel();
        jlblimagencarga = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jcbsucursal = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jdphasta = new org.jdesktop.swingx.JXDatePicker();
        jdpdesde = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CONSULTAR REPARACIONES");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarblanco.png"))); // NOI18N
        jLabel15.setToolTipText("Cerrar");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel15MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 835, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        jLabel9.setText("Cod. / Tecnico / Cliente:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jtfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbuscarActionPerformed(evt);
            }
        });
        jtfbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtfbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 508, -1));

        jlblletracarga.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblletracarga.setText("Cargando Registros ...");
        getContentPane().add(jlblletracarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jlblimagencarga.setBackground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setForeground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblimagencarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        getContentPane().add(jlblimagencarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 510, 310));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setToolTipText("Doble clic para ver detalle");
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jtabla);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1150, 440));

        jcbsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsucursalActionPerformed(evt);
            }
        });
        getContentPane().add(jcbsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 337, -1));

        jLabel10.setText("Sucursal:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, 20));

        jlbltotal.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jlbltotal.setForeground(new java.awt.Color(255, 51, 51));
        jlbltotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal.setText("jLabel1");
        getContentPane().add(jlbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 270, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Fecha"));

        jdphasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdphastaActionPerformed(evt);
            }
        });

        jdpdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpdesdeActionPerformed(evt);
            }
        });

        jLabel1.setText("Desde:");

        jLabel2.setText("Hasta:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdphasta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdphasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdpdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 390, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarKeyReleased
        // TODO add your handling code here:
//        if(jcbsucursal.getSelectedIndex()==0){
//             listrepara=daoreparacion.busquedasensitiva(jtabla, sucursalsingleton.getId(), jlbltotal, jtfbuscar.getText().toUpperCase(),"todo",0);
//        
//        }else {
//             sucursal=listsucur.get(jcbsucursal.getSelectedIndex());
//             listrepara=daoreparacion.busquedasensitiva(jtabla, sucursal.getId() ,jlbltotal, jtfbuscar.getText().toUpperCase(),"sucursal",0);
//        
//        }
       
       
    }//GEN-LAST:event_jtfbuscarKeyReleased

    private void jcbsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsucursalActionPerformed
        // TODO add your handling code here:
//         if(jcbsucursal.getSelectedIndex()==0){
//            listrepara= daoreparacion.busquedasensitiva(jtabla, sucursalsingleton.getId(), jlbltotal, jtfbuscar.getText().toUpperCase(),"todo",0);
//        
//        }else {
//             sucursal=listsucur.get(jcbsucursal.getSelectedIndex());
//            listrepara= daoreparacion.busquedasensitiva(jtabla, sucursal.getId() ,jlbltotal, jtfbuscar.getText().toUpperCase(),"sucursal",0);
//        
//        }
          refrescar();
    }//GEN-LAST:event_jcbsucursalActionPerformed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            repara=listrepara.get(jtabla.getSelectedRow());
            JDMostrarReparacion mostrar=new  JDMostrarReparacion(new Frame(), isVisible(),repara.getIdreparacion());
            mostrar.setVisible(true);
        }
    }//GEN-LAST:event_jtablaMouseReleased

    private void jtfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbuscarActionPerformed
        // TODO add your handling code here:
         refrescar();
    }//GEN-LAST:event_jtfbuscarActionPerformed

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
         int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
          posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel7MousePressed

    private void jdpdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpdesdeActionPerformed
        // TODO add your handling code here:
        refrescar();
    }//GEN-LAST:event_jdpdesdeActionPerformed

    private void jdphastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdphastaActionPerformed
        // TODO add your handling code here:
        refrescar();
    }//GEN-LAST:event_jdphastaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox jcbsucursal;
    private org.jdesktop.swingx.JXDatePicker jdpdesde;
    private org.jdesktop.swingx.JXDatePicker jdphasta;
    private javax.swing.JLabel jlblimagencarga;
    private javax.swing.JLabel jlblletracarga;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfbuscar;
    // End of variables declaration//GEN-END:variables
}
