/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.FamiliaDAO;
import DAO.ProductoDAO;
import DAO.SucursalDAO;
import Pojos.Familia;
import Pojos.Producto;
import Pojos.Sucursal;
import Pojos.SucursalSingleton;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JIFrmInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmInventario
     */
    ProductoDAO daoproducto = new ProductoDAO();
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    SucursalDAO daosucursal = new SucursalDAO();
    Mayusculas mayus = new Mayusculas();
    FamiliaDAO daofamilia = new FamiliaDAO();
    List<Familia> listfamilia;
    Familia fam = new Familia();
    ////
    List<Producto> listprod = new ArrayList<>();
    Sucursal sucursa= new Sucursal();
    List<Sucursal> listsucur;
     int posx;
    int posy;
    public JIFrmInventario() {
        initComponents();
//        jlblimagencarga.setVisible(false);
//        jlblletracarga.setVisible(false);
        jlblmensajeimpresion.setVisible(false);
        
//        double stockmin=Double.parseDouble(jsstockmin.getValue().toString());
       
        mostrar();
    }
    
    public void mostrar () {
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                jlblimagencarga.setVisible(true);
                jlblletracarga.setVisible(true);
                jsstockmin.setEnabled(false);
                jtfdescripcion.setEnabled(false);
                jcbfamilia.setEnabled(false);
                jcbsucursal.setEnabled(false);
                jsstockmin.setValue(sucursalsingleton.getStockmin());
                listfamilia = daofamilia.llenarcombo(jcbfamilia);
                 listsucur = daosucursal.llenarcombo(jcbsucursal);
                listprod= daoproducto.inventario(jtabla,sucursalsingleton.getId(),sucursalsingleton.getStockmin(),"TODO");
                jsstockmin.setEnabled(true);
                jtfdescripcion.setEnabled(true);
                jcbfamilia.setEnabled(true);
                jcbsucursal.setEnabled(true);
                jlblimagencarga.setVisible(false);
                jlblletracarga.setVisible(false);
            }
        };
        Thread T = new Thread(runnable);
        T.start();
    
    
    }
    
    public synchronized void sensitiva(){
       
     
     String descrip= jtfdescripcion.getText().toUpperCase();
       
        fam = listfamilia.get(jcbfamilia.getSelectedIndex());
        sucursa = listsucur.get(jcbsucursal.getSelectedIndex());
            
        if(jcbfamilia.getSelectedIndex()==0 && jcbsucursal.getSelectedIndex()==0){
           
         listprod=daoproducto.busquedasensitivainventario(jtabla, "TODOSUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia(),sucursalsingleton.getStockmin());
        
        }
        if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()==0){
        listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIASUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia(),sucursalsingleton.getStockmin());
        
        }
         if(jcbfamilia.getSelectedIndex() ==0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "TODO", descrip,
        sucursa.getId(),fam.getIdfamilia(),sucursalsingleton.getStockmin());
         }
         
          if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIA", descrip,
        sucursa.getId(),fam.getIdfamilia(),sucursalsingleton.getStockmin());
         }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfdescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jsstockmin = new javax.swing.JSpinner();
        jlblletracarga = new javax.swing.JLabel();
        jlblimagencarga = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jbtnimprimir = new javax.swing.JButton();
        jbtnimprimirstockmin = new javax.swing.JButton();
        jcbsucursal = new javax.swing.JComboBox();
        jcbfamilia = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlblmensajeimpresion = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Buscar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        jtfdescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfdescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusLost(evt);
            }
        });
        jtfdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdescripcionActionPerformed(evt);
            }
        });
        jtfdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyTyped(evt);
            }
        });
        jPanel1.add(jtfdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 600, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Stock Minimo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));

        jsstockmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jsstockmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsstockminStateChanged(evt);
            }
        });
        jPanel1.add(jsstockmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jlblletracarga.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblletracarga.setForeground(new java.awt.Color(0, 0, 0));
        jlblletracarga.setText("Cargando Productos ...");
        jPanel1.add(jlblletracarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        jlblimagencarga.setBackground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setForeground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblimagencarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        jPanel1.add(jlblimagencarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 220, 260));

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jtabla.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla.getTableHeader().setReorderingAllowed(false);
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1160, 370));

        jbtnimprimir.setBackground(new java.awt.Color(255, 255, 255));
        jbtnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jbtnimprimir.setBorderPainted(false);
        jbtnimprimir.setContentAreaFilled(false);
        jbtnimprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtnimprimir.setRequestFocusEnabled(false);
        jbtnimprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnimprimirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnimprimirMousePressed(evt);
            }
        });
        jbtnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        jbtnimprimirstockmin.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jbtnimprimirstockmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jbtnimprimirstockmin.setText("Productos con Stock Minimo");
        jbtnimprimirstockmin.setBorderPainted(false);
        jbtnimprimirstockmin.setContentAreaFilled(false);
        jbtnimprimirstockmin.setRequestFocusEnabled(false);
        jbtnimprimirstockmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnimprimirstockminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnimprimirstockminMousePressed(evt);
            }
        });
        jbtnimprimirstockmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirstockminActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnimprimirstockmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jcbsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsucursalActionPerformed(evt);
            }
        });
        jPanel1.add(jcbsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 323, -1));

        jcbfamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbfamiliaActionPerformed(evt);
            }
        });
        jPanel1.add(jcbfamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 380, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("Familia:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Sucursal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 20));

        jPanel2.setBackground(new java.awt.Color(220, 151, 96));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INVENTARIO DE PRODUCTOS");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarblanco.png"))); // NOI18N
        jLabel15.setToolTipText("Cerrar");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel15MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 825, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(174, 174, 174))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        jlblmensajeimpresion.setForeground(new java.awt.Color(255, 255, 255));
        jlblmensajeimpresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loading4.gif"))); // NOI18N
        jlblmensajeimpresion.setText("Imprimiendo Inventario ...");
        jPanel1.add(jlblmensajeimpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 181, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyTyped
        // TODO add your handling code here:
//       mayus.convertirmayus(jtfdescripcion);
    }//GEN-LAST:event_jtfdescripcionKeyTyped

    private void jsstockminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsstockminStateChanged
        // TODO add your handling code here:
        double stockmin=Double.parseDouble(jsstockmin.getValue().toString());
        daosucursal.editarstockmin(sucursalsingleton.getId(),stockmin);
        sucursalsingleton.setStockmin(stockmin);
        
        daoproducto.inventario(jtabla,sucursalsingleton.getId(),stockmin,"TODO");
//        daoproducto.inventario(jtabla,sucursalsingleton.getId());      
//        ColorRowTabla colorrow= new ColorRowTabla(3, stockmin);
    }//GEN-LAST:event_jsstockminStateChanged

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtablaMouseReleased

    private void jtfdescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfdescripcionFocusGained

    private void jtfdescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusLost
       
    }//GEN-LAST:event_jtfdescripcionFocusLost

    private void jtfdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyReleased
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_jtfdescripcionKeyReleased

    private void jbtnimprimirstockminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirstockminActionPerformed
        // TODO add your handling code here:
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
                jlblmensajeimpresion.setVisible(true);
                daoproducto.imprimirinventariostockmin(sucursalsingleton.getId(), sucursalsingleton.getStockmin());
                jlblmensajeimpresion.setVisible(false);
        }
        };
        Thread T = new Thread(runnable);
        T.start();
    }//GEN-LAST:event_jbtnimprimirstockminActionPerformed

    private void jbtnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirActionPerformed
        // TODO add your handling code here:
        Runnable runnable = new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                jlblmensajeimpresion.setVisible(true);
                daoproducto.imprimirinventario(sucursalsingleton.getId());
                jlblmensajeimpresion.setVisible(false);
            }
        };
        Thread T = new Thread(runnable);
        T.start();
        
         
    }//GEN-LAST:event_jbtnimprimirActionPerformed

    private void jcbfamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbfamiliaActionPerformed
        // TODO add your handling code here:
         Runnable runnable=new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                jlblimagencarga.setVisible(true);
                jlblletracarga.setVisible(true);
                sensitiva();
                jlblimagencarga.setVisible(false);
                jlblletracarga.setVisible(false);
            }
        };
        Thread T = new Thread(runnable);
        T.start();
        
          
    }//GEN-LAST:event_jcbfamiliaActionPerformed

    private void jcbsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsucursalActionPerformed
        // TODO add your handling code here:
          Runnable runnable=new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                jlblimagencarga.setVisible(true);
                jlblletracarga.setVisible(true);
                sensitiva();
                jlblimagencarga.setVisible(false);
                jlblletracarga.setVisible(false);
            }
        };
        Thread T = new Thread(runnable);
        T.start();
    }//GEN-LAST:event_jcbsucursalActionPerformed

    private void jbtnimprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirMousePressed
        // TODO add your handling code here:
        jlblmensajeimpresion.setText("Imprimiendo Reporte ...");
    }//GEN-LAST:event_jbtnimprimirMousePressed

    private void jbtnimprimirstockminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirstockminMousePressed
        // TODO add your handling code here:
        jlblmensajeimpresion.setText("Imprimiendo Reporte ...");
    }//GEN-LAST:event_jbtnimprimirstockminMousePressed

    private void jbtnimprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirMouseExited
        // TODO add your handling code here:
         jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtnimprimirMouseExited

    private void jbtnimprimirstockminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirstockminMouseExited
        // TODO add your handling code here:
         jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtnimprimirstockminMouseExited

    private void jtfdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdescripcionActionPerformed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_jtfdescripcionActionPerformed

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
          posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jtfdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
         Runnable runnable=new Runnable() {

            @Override
            public void run() {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                jlblimagencarga.setVisible(true);
                jlblletracarga.setVisible(true);
                sensitiva();
                jlblimagencarga.setVisible(false);
                jlblletracarga.setVisible(false);
            }
        };
        Thread T = new Thread(runnable);
        T.start();
         
        }
    }//GEN-LAST:event_jtfdescripcionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnimprimir;
    private javax.swing.JButton jbtnimprimirstockmin;
    private javax.swing.JComboBox jcbfamilia;
    private javax.swing.JComboBox jcbsucursal;
    private javax.swing.JLabel jlblimagencarga;
    private javax.swing.JLabel jlblletracarga;
    private javax.swing.JLabel jlblmensajeimpresion;
    private javax.swing.JSpinner jsstockmin;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfdescripcion;
    // End of variables declaration//GEN-END:variables
}
