/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.FamiliaDAO;
import DAO.ProductoDAO;
import DAO.SucursalDAO;
import Pojos.Familia;
import Pojos.Producto;
import Pojos.Sucursal;
import Pojos.SucursalSingleton;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JIFrmInventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmInventario
     */
    ProductoDAO daoproducto = new ProductoDAO();
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    SucursalDAO daosucursal = new SucursalDAO();
    Mayusculas mayus = new Mayusculas();
    FamiliaDAO daofamilia = new FamiliaDAO();
    List<Familia> listfamilia= new ArrayList<>();
    Familia fam = new Familia();
    ////
    List<Producto> listprod = new ArrayList<>();
    Sucursal sucursa= new Sucursal();
    List<Sucursal> listsucur= new ArrayList<>();
    public JIFrmInventario() {
        initComponents();
       listprod= daoproducto.inventario(jtabla,sucursalsingleton.getId(),sucursalsingleton.getStockmin(),"TODO");
        jsstockmin.setValue(sucursalsingleton.getStockmin());
        double stockmin=Double.parseDouble(jsstockmin.getValue().toString());
          listfamilia = daofamilia.llenarcombo(jcbfamilia);
          listsucur = daosucursal.llenarcombo(jcbsucursal);
//        jtabla.requestFocus();
       // jtabla.setRowSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfdescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jsstockmin = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jbtnimprimir = new javax.swing.JButton();
        jbtnimprimirstockmin = new javax.swing.JButton();
        jcbsucursal = new javax.swing.JComboBox();
        jcbfamilia = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblmensajeimpresion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Buscar:");

        jtfdescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfdescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusLost(evt);
            }
        });
        jtfdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Stock Minimo:");

        jsstockmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jsstockmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsstockminStateChanged(evt);
            }
        });

        jtabla.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabla.getTableHeader().setReorderingAllowed(false);
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtabla);

        jbtnimprimir.setBackground(new java.awt.Color(255, 255, 255));
        jbtnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jbtnimprimir.setRequestFocusEnabled(false);
        jbtnimprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnimprimirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnimprimirMousePressed(evt);
            }
        });
        jbtnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirActionPerformed(evt);
            }
        });

        jbtnimprimirstockmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnimprimirstockmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        jbtnimprimirstockmin.setText("Productos con Stock Minimo");
        jbtnimprimirstockmin.setRequestFocusEnabled(false);
        jbtnimprimirstockmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnimprimirstockminMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtnimprimirstockminMousePressed(evt);
            }
        });
        jbtnimprimirstockmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirstockminActionPerformed(evt);
            }
        });

        jcbsucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsucursalActionPerformed(evt);
            }
        });

        jcbfamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbfamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbfamiliaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("Familia:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Sucursal:");

        jlblmensajeimpresion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblmensajeimpresion.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addComponent(jsstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jcbfamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnimprimir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnimprimirstockmin))
                            .addComponent(jlblmensajeimpresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbfamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsstockmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnimprimir)
                            .addComponent(jbtnimprimirstockmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblmensajeimpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        jPanel2.setBackground(new java.awt.Color(238, 238, 238));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("INVENTARIO DE PRODUCTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyTyped
        // TODO add your handling code here:
       mayus.convertirmayus(jtfdescripcion);
    }//GEN-LAST:event_jtfdescripcionKeyTyped

    private void jsstockminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsstockminStateChanged
        // TODO add your handling code here:
        double stockmin=Double.parseDouble(jsstockmin.getValue().toString());
        daosucursal.editarstockmin(sucursalsingleton.getId(),stockmin);
        sucursalsingleton.setStockmin(stockmin);
        daoproducto.inventario(jtabla,sucursalsingleton.getId(),stockmin,"TODO");
//        daoproducto.inventario(jtabla,sucursalsingleton.getId());      
//        ColorRowTabla colorrow= new ColorRowTabla(3, stockmin);
    }//GEN-LAST:event_jsstockminStateChanged

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtablaMouseReleased

    private void jtfdescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfdescripcionFocusGained

    private void jtfdescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusLost
       
    }//GEN-LAST:event_jtfdescripcionFocusLost

    private void jtfdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyReleased
        // TODO add your handling code here:
          String descrip= jtfdescripcion.getText().toUpperCase();
       
            fam = listfamilia.get(jcbfamilia.getSelectedIndex());
            sucursa = listsucur.get(jcbsucursal.getSelectedIndex());
            
        if(jcbfamilia.getSelectedIndex()==0 && jcbsucursal.getSelectedIndex()==0){
           
         listprod=daoproducto.busquedasensitivainventario(jtabla, "TODOSUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia());
        
        }
        if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()==0){
        listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIASUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia());
        
        }
         if(jcbfamilia.getSelectedIndex() ==0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "TODO", descrip,
        sucursa.getId(),fam.getIdfamilia());
         }
         
          if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIA", descrip,
        sucursa.getId(),fam.getIdfamilia());
         }
       
       
    }//GEN-LAST:event_jtfdescripcionKeyReleased

    private void jbtnimprimirstockminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirstockminActionPerformed
        // TODO add your handling code here:
        daoproducto.imprimirinventariostockmin(sucursalsingleton.getId(), sucursalsingleton.getStockmin());
         jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtnimprimirstockminActionPerformed

    private void jbtnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirActionPerformed
        // TODO add your handling code here:
        daoproducto.imprimirinventario(sucursalsingleton.getId());
          jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtnimprimirActionPerformed

    private void jcbfamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbfamiliaActionPerformed
        // TODO add your handling code here:
           String descrip= jtfdescripcion.getText().toUpperCase();
       if(listfamilia.size()>0 && listsucur.size()>0){
       
         fam = listfamilia.get(jcbfamilia.getSelectedIndex());
            sucursa = listsucur.get(jcbsucursal.getSelectedIndex());
            
        if(jcbfamilia.getSelectedIndex()==0 && jcbsucursal.getSelectedIndex()==0){
           
         listprod=daoproducto.busquedasensitivainventario(jtabla, "TODOSUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia());
        
        }
        if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()==0){
        listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIASUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia());
        
        }
         if(jcbfamilia.getSelectedIndex() ==0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "TODO", descrip,
        sucursa.getId(),fam.getIdfamilia());
         }
         
          if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIA", descrip,
        sucursa.getId(),fam.getIdfamilia());
         }
        
       
       }
          
    }//GEN-LAST:event_jcbfamiliaActionPerformed

    private void jcbsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsucursalActionPerformed
        // TODO add your handling code here:
          String descrip= jtfdescripcion.getText().toUpperCase();
       if(listfamilia.size()>0 && listsucur.size()>0){
       
         fam = listfamilia.get(jcbfamilia.getSelectedIndex());
            sucursa = listsucur.get(jcbsucursal.getSelectedIndex());
            
        if(jcbfamilia.getSelectedIndex()==0 && jcbsucursal.getSelectedIndex()==0){
           
         listprod=daoproducto.busquedasensitivainventario(jtabla, "TODOSUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia());
        
        }
        if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()==0){
        listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIASUCURSAL", descrip,
        sucursa.getId(),fam.getIdfamilia());
        
        }
         if(jcbfamilia.getSelectedIndex() ==0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "TODO", descrip,
        sucursa.getId(),fam.getIdfamilia());
         }
         
          if(jcbfamilia.getSelectedIndex() !=0  && jcbsucursal.getSelectedIndex()!=0){
              listprod=daoproducto.busquedasensitivainventario(jtabla, "FAMILIA", descrip,
        sucursa.getId(),fam.getIdfamilia());
         }
        
       
       }
    }//GEN-LAST:event_jcbsucursalActionPerformed

    private void jbtnimprimirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirMousePressed
        // TODO add your handling code here:
        jlblmensajeimpresion.setText("Imprimiendo Reporte ...");
    }//GEN-LAST:event_jbtnimprimirMousePressed

    private void jbtnimprimirstockminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirstockminMousePressed
        // TODO add your handling code here:
        jlblmensajeimpresion.setText("Imprimiendo Reporte ...");
    }//GEN-LAST:event_jbtnimprimirstockminMousePressed

    private void jbtnimprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirMouseExited
        // TODO add your handling code here:
         jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtnimprimirMouseExited

    private void jbtnimprimirstockminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnimprimirstockminMouseExited
        // TODO add your handling code here:
         jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtnimprimirstockminMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnimprimir;
    private javax.swing.JButton jbtnimprimirstockmin;
    private javax.swing.JComboBox jcbfamilia;
    private javax.swing.JComboBox jcbsucursal;
    private javax.swing.JLabel jlblmensajeimpresion;
    private javax.swing.JSpinner jsstockmin;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfdescripcion;
    // End of variables declaration//GEN-END:variables
}
