/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.ReparacionDAO;
import Pojos.Cliente;
import Pojos.Empleado;
import Pojos.EmpleadoSingleton;
import Pojos.PrecioReparacion;
import Pojos.Reparacion;
import Pojos.SucursalSingleton;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author info2017
 */
public class JIFReparaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReparaciones
     */
    Empleado empleado=new Empleado();
    Cliente cliente=new Cliente();
//    Empleado empleadologin;
    EmpleadoSingleton empleadosingleton=EmpleadoSingleton.getinstancia();
    ReparacionDAO daoreparacion=new ReparacionDAO();
    byte[]  fotoB;
    Reparacion reparacion= new Reparacion();
    long idreparacion;
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    List<PrecioReparacion> listprecio = new ArrayList<>();
    PrecioReparacion precio = new PrecioReparacion();
    Mayusculas mayus = new Mayusculas();
    public JIFReparaciones() {
        
        initComponents();
        jbtnaceptar.setEnabled(false);
        fotoB= new byte[0];//INICIALIZO EL BYTE CON 0 
        reparacion.setFoto(fotoB);//LE ENVIO 0 BYTES POR DEFAULT
//        daoreparacion.llenarcombobox(jcbdispositivo);
        listprecio=daoreparacion.llenarcombobox(jcbdispositivo);
    }
    public void setempleado(Empleado empleado){
        this.empleado= empleado;
        jlblnombre.setText(empleado.getNombre());
    }
    public void setcliente(Cliente cliente){
        this.cliente=cliente;
        jlblcliente.setText(cliente.getNombre_razons());
    }
//    public void inicializofoto(){
//        try {
//            String rutaimagen=null;
//            File file = new File(rutaimagen);
//            byte[]  fotobys= Files.readAllBytes(file.toPath());
//            reparacion.setFoto(fotobys);
//        } catch (IOException ex) {
//            Logger.getLogger(JIFReparaciones.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
//    
//    }
    public void validaaceptar (){
        System.out.println("idem"+empleado.getId_empleado());
        
        try {
            System.out.println(jtfprecio.getText());
             
            if (empleado.getId_empleado()!=0 && !jtfmarca.getText().equals("MARCA") && !jtfmarca.getText().equals("")&& !jtfmodelo.getText().equals("MODELO") &&
                !jtfmodelo.getText().equals("") && !jtafallas.getText().equals("")
                && !jtafallas.getText().equals("FALLAS") && cliente.getId_cliente()!= 0  && precio.getId() !=0){
                jbtnaceptar.setEnabled( true);
//                jlblmensaje.setText("");
            }else {
                jbtnaceptar.setEnabled(false);
            }
        } catch (NumberFormatException e) {
                jbtnaceptar.setEnabled(false);
//                jlblmensaje.setText("INGRESE PRECIO");
        }
       
    }
    public void nuevo(){
    empleado= new Empleado();
    reparacion= new Reparacion();
    cliente=new Cliente();
    idreparacion=0;
    jtfmarca.setText("MARCA");
    jtfmodelo.setText("MODELO");
    jlblfoto.setIcon(null);
    jlblnombre.setText("---");
    jlblcliente.setText("---");
    jtafallas.setText("FALLAS");
    jtacausas.setText("CAUSAS");
    jtaobservacion.setText("OBSERVACIÓN");
//    jtadiagnostico.setText("DIAGNOSTICO");
    jbtnaceptar.setEnabled(false);
   
    jXDate.setDate(null);
    jtfprecio.setText("");
    reparacion.setFoto(fotoB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfmarca = new javax.swing.JTextField();
        jtfmodelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtafallas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtacausas = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaobservacion = new javax.swing.JTextArea();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jlblfoto = new javax.swing.JLabel();
        jbtnfoto = new javax.swing.JButton();
        jbtnaceptar = new javax.swing.JButton();
        jlblnombre = new javax.swing.JLabel();
        jbtnbuscartecnico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlblcliente = new javax.swing.JLabel();
        jbtncliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jXDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jsphora = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jspmin = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jtfprecio = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfpreciorevision = new javax.swing.JFormattedTextField();
        jcbdispositivo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfdescuento = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NUEVA REPARACIÓN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("TECNICO REPARACIÓN:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtfmarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfmarca.setText("MARCA");
        jtfmarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfmarcaFocusLost(evt);
            }
        });
        jtfmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfmarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfmarcaKeyTyped(evt);
            }
        });

        jtfmodelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfmodelo.setText("MODELO");
        jtfmodelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmodeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfmodeloFocusLost(evt);
            }
        });
        jtfmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfmodeloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfmodeloKeyTyped(evt);
            }
        });

        jtafallas.setColumns(20);
        jtafallas.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jtafallas.setRows(5);
        jtafallas.setText("FALLAS");
        jtafallas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtafallasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtafallasFocusLost(evt);
            }
        });
        jtafallas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtafallasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtafallasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtafallas);

        jtacausas.setColumns(20);
        jtacausas.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jtacausas.setRows(5);
        jtacausas.setText("CAUSAS");
        jtacausas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtacausasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtacausasFocusLost(evt);
            }
        });
        jtacausas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtacausasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtacausasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtacausas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jtfmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jtfmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jtaobservacion.setColumns(20);
        jtaobservacion.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jtaobservacion.setRows(5);
        jtaobservacion.setText("OBSERVACIÓN");
        jtaobservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtaobservacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtaobservacionFocusLost(evt);
            }
        });
        jtaobservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaobservacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaobservacionKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jtaobservacion);

        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblfoto.setBackground(new java.awt.Color(255, 255, 255));
        panelNice1.add(jlblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 170));

        jbtnfoto.setBackground(new java.awt.Color(255, 255, 255));
        jbtnfoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FOTO.png"))); // NOI18N
        jbtnfoto.setText("FOTO");
        jbtnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfotoActionPerformed(evt);
            }
        });

        jbtnaceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Checked.png"))); // NOI18N
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });

        jlblnombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblnombre.setText("---");

        jbtnbuscartecnico.setBackground(new java.awt.Color(255, 255, 255));
        jbtnbuscartecnico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnbuscartecnico.setText("...");
        jbtnbuscartecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscartecnicoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("CLIENTE:");

        jlblcliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblcliente.setText("---");

        jbtncliente.setBackground(new java.awt.Color(255, 255, 255));
        jbtncliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtncliente.setText("...");
        jbtncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclienteActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA Y HORA DE ENTREGA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jXDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("HORA:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, 20));

        jsphora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jsphora.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"}));
        jPanel3.add(jsphora, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("MIN:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, 20));

        jspmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jspmin.setModel(new javax.swing.SpinnerListModel(new String[] {"00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"}));
        jPanel3.add(jspmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PRECIO:");

        jtfprecio.setEditable(false);
        jtfprecio.setForeground(new java.awt.Color(255, 51, 102));
        jtfprecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###,###"))));
        jtfprecio.setCaretColor(new java.awt.Color(255, 51, 102));
        jtfprecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfprecioKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PRECIO REVISIÓN:");

        jtfpreciorevision.setEditable(false);
        jtfpreciorevision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfpreciorevision.setCaretColor(new java.awt.Color(255, 51, 51));

        jcbdispositivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jcbdispositivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbdispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdispositivoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DISPOSITIVO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DESCUENTO:");

        jtfdescuento.setCaretColor(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(jlblcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jbtncliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(jlblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtnbuscartecnico)))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jbtnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jcbdispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfpreciorevision, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jtfdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jbtnaceptar)))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jlblcliente)
                            .addComponent(jbtncliente))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jlblnombre)
                            .addComponent(jbtnbuscartecnico))
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelNice1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addGap(3, 3, 3)
                        .addComponent(jbtnfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)
                        .addComponent(jcbdispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jtfprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(jtfpreciorevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(jtfdescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jbtnaceptar)))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbuscartecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscartecnicoActionPerformed
        // TODO add your handling code here:
        JDBuscarEmpleado Bempleado = new JDBuscarEmpleado(new java.awt.Frame(),isVisible(),this);
        Bempleado.setVisible(true);
    }//GEN-LAST:event_jbtnbuscartecnicoActionPerformed

    private void jtfmarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmarcaFocusGained
        // TODO add your handling code here:
        if(jtfmarca.getText().equals("MARCA")){
          jtfmarca.setText("");
        
        
        }
    }//GEN-LAST:event_jtfmarcaFocusGained

    private void jtfmarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmarcaFocusLost
        // TODO add your handling code here:
         if(jtfmarca.getText().equals("")){
          jtfmarca.setText("MARCA");
        
        
        }
    }//GEN-LAST:event_jtfmarcaFocusLost

    private void jtfmodeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmodeloFocusGained
        // TODO add your handling code here:
        if(jtfmodelo.getText().equals("MODELO")){
          jtfmodelo.setText("");
        
        
        }
    }//GEN-LAST:event_jtfmodeloFocusGained

    private void jtafallasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtafallasFocusGained
        // TODO add your handling code here:
        if(jtafallas.getText().equals("FALLAS")){
          jtafallas.setText("");
              
        }
        
    }//GEN-LAST:event_jtafallasFocusGained

    private void jtfmodeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmodeloFocusLost
        // TODO add your handling code here:
        if(jtfmodelo.getText().equals("")){
          jtfmodelo.setText("MODELO");
        
        
        }
    }//GEN-LAST:event_jtfmodeloFocusLost

    private void jtafallasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtafallasFocusLost
        // TODO add your handling code here:
        if(jtafallas.getText().equals("")){
          jtafallas.setText("FALLAS");
              
        }
    }//GEN-LAST:event_jtafallasFocusLost

    private void jtacausasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtacausasFocusGained
        // TODO add your handling code here:
         if(jtacausas.getText().equals("CAUSAS")){
          jtacausas.setText("");
              
        }
    }//GEN-LAST:event_jtacausasFocusGained

    private void jtacausasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtacausasFocusLost
        // TODO add your handling code here:
        if(jtacausas.getText().equals("")){
          jtacausas.setText("CAUSAS");
              
        }
    }//GEN-LAST:event_jtacausasFocusLost

    private void jtaobservacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaobservacionFocusGained
        // TODO add your handling code here:
        if(jtaobservacion.getText().equals("OBSERVACIÓN")){
          jtaobservacion.setText("");
              
        }
    }//GEN-LAST:event_jtaobservacionFocusGained

    private void jtaobservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaobservacionFocusLost
        // TODO add your handling code here:
        if(jtaobservacion.getText().equals("")){
          jtaobservacion.setText("OBSERVACIÓN");
              
        }
    }//GEN-LAST:event_jtaobservacionFocusLost

    private void jbtnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfotoActionPerformed
        // TODO add your handling code here:
        String rutaimagen=null;
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos png & jpg", "png", "jpg");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {                        
                try {
                    rutaimagen = chooser.getSelectedFile().getAbsolutePath();
                    System.out.println("rutaimg"+rutaimagen);
                    File file = new File(rutaimagen);
                    byte[]  fotobys= Files.readAllBytes(file.toPath());
                    reparacion.setFoto(fotobys);
                    
                    
                    Image icono=ImageIO.read(chooser.getSelectedFile()).getScaledInstance
                    (jlblfoto.getWidth(),jlblfoto.getHeight(),Image.SCALE_DEFAULT);
                    jlblfoto.setIcon(new ImageIcon(icono));
                    jlblfoto.updateUI();

//                   validaguardar();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
                }
            }    
    }//GEN-LAST:event_jbtnfotoActionPerformed

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        String codigo;
        if (empleado.getId_empleado()!=0 && !jtfmarca.getText().equals("MARCA") && !jtfmarca.getText().equals("")&& !jtfmodelo.getText().equals("MODELO") &&
                !jtfmodelo.getText().equals("") && !jtafallas.getText().equals("")
                && !jtafallas.getText().equals("FALLAS")&& cliente.getId_cliente()!= 0 && precio.getId() !=0){
            reparacion.setIdempleado(empleado.getId_empleado());
            reparacion.setIdcliente(cliente.getId_cliente());
            reparacion.setAtendido(empleadosingleton.getNombre());
            reparacion.setMarca(jtfmarca.getText());
            reparacion.setModelo(jtfmodelo.getText());
            reparacion.setFallas(jtafallas.getText());
            reparacion.setCausas(jtacausas.getText());
            reparacion.setObservacion(jtaobservacion.getText());
           // reparacion.setDiagnostico(jtadiagnostico.getText());
            System.out.println(jtfprecio.getValue());
            reparacion.setPrecio(Double.parseDouble(jtfprecio.getValue().toString()));
//            System.out.println(jXDate.getDate().getTime()+" "+jsphora.getValue()+":"+jspmin.getValue()+":"+"00");
//            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//        jXDate.setFormats(dateFormat); 
//        DateFormat sysDate = new SimpleDateFormat("yyyy");
//        DateFormat sysDate1 = new SimpleDateFormat("MM");
//        DateFormat sysDate2 = new SimpleDateFormat("dd");
//        int año = Integer.parseInt(sysDate.format(jXDate.getDate()).toString()); 
//        int mes = Integer.parseInt(sysDate1.format(jXDate.getDate()).toString());
//        int dia = Integer.parseInt(sysDate2.format(jXDate.getDate()).toString());
//            System.err.println("año"+año);
//            System.err.println("mes"+mes);
//            System.err.println("dia"+dia);
            reparacion.setFechaE(new java.sql.Timestamp(jXDate.getDate().getTime()));
            reparacion.setHora(jsphora.getValue()+":"+jspmin.getValue());
            reparacion.setId_sucural(sucursalsingleton.getId());
            reparacion.setPrecio(Double.parseDouble(jtfprecio.getValue().toString()));
            reparacion.setPreciorevision(Double.parseDouble(jtfpreciorevision.getValue().toString()));
            reparacion.setDescuento(Double.parseDouble(jtfdescuento.getValue().toString()));
            idreparacion=daoreparacion.insertar(reparacion);
//            JOptionPane.showMessageDialog(null, codigo,"TOME NOTA DEL CODIGO DE REPARACION",JOptionPane.INFORMATION_MESSAGE);
            daoreparacion.imprimirticketcaja(idreparacion);
            nuevo();                                                                         
            
        }else {
            JOptionPane.showMessageDialog(null, "RELLENE LOS CAMPOS OBLIGATORIOS");
        
        }
        
        
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfmarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmarcaKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtfmarcaKeyReleased

    private void jtfmodeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmodeloKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtfmodeloKeyReleased

    private void jtafallasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtafallasKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtafallasKeyReleased

    private void jtacausasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtacausasKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtacausasKeyReleased

    private void jtaobservacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaobservacionKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtaobservacionKeyReleased

    private void jbtnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclienteActionPerformed
        // TODO add your handling code here:
        JDBuscarCliente Bcliente= new JDBuscarCliente(new java.awt.Frame(), isVisible(),this);
        Bcliente.setVisible(true);
    }//GEN-LAST:event_jbtnclienteActionPerformed

    private void jtfprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfprecioKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtfprecioKeyReleased

    private void jcbdispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdispositivoActionPerformed
        // TODO add your handling code here:
        int index=jcbdispositivo.getSelectedIndex();
        precio= listprecio.get(index);
        jtfprecio.setValue(precio.getPrecio());
        jtfpreciorevision.setValue(precio.getPreciorevision());
        validaaceptar();
    }//GEN-LAST:event_jcbdispositivoActionPerformed

    private void jtfmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmarcaKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfmarca);
    }//GEN-LAST:event_jtfmarcaKeyTyped

    private void jtfmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmodeloKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfmodelo);
    }//GEN-LAST:event_jtfmodeloKeyTyped

    private void jtafallasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtafallasKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayusTA(jtafallas);
    }//GEN-LAST:event_jtafallasKeyTyped

    private void jtacausasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtacausasKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayusTA(jtacausas);
    }//GEN-LAST:event_jtacausasKeyTyped

    private void jtaobservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaobservacionKeyTyped
        // TODO add your handling code here:
         mayus.convertirmayusTA( jtaobservacion);
    }//GEN-LAST:event_jtaobservacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXDatePicker jXDate;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JButton jbtnbuscartecnico;
    private javax.swing.JButton jbtncliente;
    private javax.swing.JButton jbtnfoto;
    private javax.swing.JComboBox jcbdispositivo;
    private javax.swing.JLabel jlblcliente;
    private javax.swing.JLabel jlblfoto;
    private javax.swing.JLabel jlblnombre;
    private javax.swing.JSpinner jsphora;
    private javax.swing.JSpinner jspmin;
    private javax.swing.JTextArea jtacausas;
    private javax.swing.JTextArea jtafallas;
    private javax.swing.JTextArea jtaobservacion;
    private javax.swing.JFormattedTextField jtfdescuento;
    private javax.swing.JTextField jtfmarca;
    private javax.swing.JTextField jtfmodelo;
    private javax.swing.JFormattedTextField jtfprecio;
    private javax.swing.JFormattedTextField jtfpreciorevision;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
}
