/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.ReparacionDAO;
import Pojos.Cliente;
import Pojos.Empleado;
import Pojos.EmpleadoSingleton;
import Pojos.PrecioReparacion;
import Pojos.Reparacion;
import Pojos.SucursalSingleton;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author info2017
 */
public class JIFReparaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReparaciones
     */
    Empleado empleado=new Empleado();
    Cliente cliente=new Cliente();
//    Empleado empleadologin;
    EmpleadoSingleton empleadosingleton=EmpleadoSingleton.getinstancia();
    ReparacionDAO daoreparacion=new ReparacionDAO();
    byte[]  fotoB;
    Reparacion reparacion= new Reparacion();
    long idreparacion;
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    List<PrecioReparacion> listprecio = new ArrayList<>();
    PrecioReparacion precio = new PrecioReparacion();
    Mayusculas mayus = new Mayusculas();
     int posx;
    int posy;
    public JIFReparaciones() {
        
        initComponents();
        jbtnaceptar.setEnabled(false);
        fotoB= new byte[0];//INICIALIZO EL BYTE CON 0 
        reparacion.setFoto(fotoB);//LE ENVIO 0 BYTES POR DEFAULT
//        daoreparacion.llenarcombobox(jcbdispositivo);
        listprecio=daoreparacion.llenarcombobox(jcbdispositivo);
        jdpfecha.setDate(new Date());
        
        
         ///// hora actual
        Date fecha = new Date();
        DateFormat df = new SimpleDateFormat("HH:mm:ss");
        jtfhora.setValue(df.format(fecha));
    }
    public void setempleado(Empleado empleado){
        this.empleado= empleado;
        jlblnombre.setText(empleado.getNombre());
    }
    public void setcliente(Cliente cliente){
        this.cliente=cliente;
        jlblcliente.setText(cliente.getNombre_razons());
    }
//    public void inicializofoto(){
//        try {
//            String rutaimagen=null;
//            File file = new File(rutaimagen);
//            byte[]  fotobys= Files.readAllBytes(file.toPath());
//            reparacion.setFoto(fotobys);
//        } catch (IOException ex) {
//            Logger.getLogger(JIFReparaciones.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    
//    
//    }
    public void validaaceptar (){
        System.out.println("idem"+empleado.getId_empleado());
        
        try {
            System.out.println(jtfprecio.getText());
             Double precio = Double.parseDouble(jtfprecio.getText());
             Double preciorev = Double.parseDouble(jtfpreciorevision.getText());
             String dispo=jcbdispositivo.getSelectedItem().toString();
                     
                     
                     
                     
            if (empleado.getId_empleado()!=0  && !jtfmarca.getText().equals("")&&
                !jtfmodelo.getText().equals("") && !jtafallas.getText().equals("")
                && cliente.getId_cliente()!= 0  && precio >= 0 && preciorev >=0 && !dispo.equals("") ){
                jbtnaceptar.setEnabled( true);
//                jlblmensaje.setText("");
            }else {
                jbtnaceptar.setEnabled(false);
            }
        } catch (Exception e) {
                jbtnaceptar.setEnabled(false);
//                jlblmensaje.setText("INGRESE PRECIO");
        }
       
    }
    public void nuevo(){
    empleado= new Empleado();
    reparacion= new Reparacion();
    cliente=new Cliente();
    idreparacion=0;
    jtfmarca.setText("");
    jtfmodelo.setText("");
    jlblfoto.setIcon(null);
    jlblnombre.setText("* * *");
    jlblcliente.setText("* * *");
    jtafallas.setText("");
    jtacausas.setText("");
    jtaobservacion.setText("");
//    jtadiagnostico.setText("DIAGNOSTICO");
    jbtnaceptar.setEnabled(false);
    jtfpreciorevision.setText("");
//    jtfdescuento.setText("");
   
    jtfprecio.setText("");
    reparacion.setFoto(fotoB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfmarca = new javax.swing.JTextField();
        jtfmodelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtafallas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtacausas = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaobservacion = new javax.swing.JTextArea();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jlblfoto = new javax.swing.JLabel();
        jbtnfoto = new javax.swing.JButton();
        jbtnaceptar = new javax.swing.JButton();
        jlblnombre = new javax.swing.JLabel();
        jbtnbuscartecnico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlblcliente = new javax.swing.JLabel();
        jbtncliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jdpfecha = new org.jdesktop.swingx.JXDatePicker();
        jtfhora = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbdispositivo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jtfprecio = new javax.swing.JTextField();
        jtfpreciorevision = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setText("Técnico:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtfmarca.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfmarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfmarcaFocusLost(evt);
            }
        });
        jtfmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfmarcaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfmarcaKeyTyped(evt);
            }
        });

        jtfmodelo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfmodelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmodeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfmodeloFocusLost(evt);
            }
        });
        jtfmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfmodeloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfmodeloKeyTyped(evt);
            }
        });

        jtafallas.setColumns(20);
        jtafallas.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtafallas.setRows(5);
        jtafallas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtafallasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtafallasFocusLost(evt);
            }
        });
        jtafallas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtafallasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtafallasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtafallas);

        jtacausas.setColumns(20);
        jtacausas.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtacausas.setRows(5);
        jtacausas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtacausasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtacausasFocusLost(evt);
            }
        });
        jtacausas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtacausasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtacausasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtacausas);

        jLabel9.setText("Marca:");

        jLabel10.setText("Modelo:");

        jLabel11.setText("Fallas:");

        jLabel12.setText("Causas:");

        jLabel13.setText("Observación:");

        jtaobservacion.setColumns(20);
        jtaobservacion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtaobservacion.setRows(5);
        jtaobservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtaobservacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtaobservacionFocusLost(evt);
            }
        });
        jtaobservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaobservacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaobservacionKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jtaobservacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 360));

        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblfoto.setBackground(new java.awt.Color(255, 255, 255));
        panelNice1.add(jlblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 170));

        jPanel1.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 230, 190));

        jbtnfoto.setBackground(new java.awt.Color(255, 255, 255));
        jbtnfoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FOTO.png"))); // NOI18N
        jbtnfoto.setBorderPainted(false);
        jbtnfoto.setContentAreaFilled(false);
        jbtnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfotoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 40, 40));

        jbtnaceptar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnaceptar.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save20x20.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.setBorderPainted(false);
        jbtnaceptar.setContentAreaFilled(false);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, -1, 40));

        jlblnombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblnombre.setText("* * *");
        jPanel1.add(jlblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 450, -1));

        jbtnbuscartecnico.setBackground(new java.awt.Color(255, 255, 255));
        jbtnbuscartecnico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnbuscartecnico.setText("...");
        jbtnbuscartecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscartecnicoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbuscartecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jlblcliente.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblcliente.setText("* * *");
        jPanel1.add(jlblcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 450, -1));

        jbtncliente.setBackground(new java.awt.Color(255, 255, 255));
        jbtncliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtncliente.setText("...");
        jbtncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclienteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha y Hora de Entrega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jdpfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 20));

        try {
            jtfhora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jtfhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 90, -1));

        jLabel3.setText("H24:MM:SS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Precio Revisión:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 110, -1));

        jcbdispositivo.setEditable(true);
        jcbdispositivo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jcbdispositivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbdispositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbdispositivoActionPerformed(evt);
            }
        });
        jPanel1.add(jcbdispositivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 270, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Dispositivo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        jtfprecio.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfprecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtfprecioMouseReleased(evt);
            }
        });
        jtfprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfprecioKeyReleased(evt);
            }
        });
        jPanel1.add(jtfprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 200, -1));

        jtfpreciorevision.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfpreciorevision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfpreciorevisionMousePressed(evt);
            }
        });
        jtfpreciorevision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfpreciorevisionKeyReleased(evt);
            }
        });
        jPanel1.add(jtfpreciorevision, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 220, -1));

        jPanel7.setBackground(new java.awt.Color(220, 151, 96));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("NUEVA REPARACION");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarblanco.png"))); // NOI18N
        jLabel15.setToolTipText("Cerrar");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel15MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 840, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnbuscartecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscartecnicoActionPerformed
        // TODO add your handling code here:
        JDBuscarEmpleado Bempleado = new JDBuscarEmpleado(new java.awt.Frame(),isVisible(),this);
        Bempleado.setVisible(true);
    }//GEN-LAST:event_jbtnbuscartecnicoActionPerformed

    private void jtfmarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmarcaFocusGained
    
    }//GEN-LAST:event_jtfmarcaFocusGained

    private void jtfmarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmarcaFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtfmarcaFocusLost

    private void jtfmodeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmodeloFocusGained
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jtfmodeloFocusGained

    private void jtafallasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtafallasFocusGained
     
        
    }//GEN-LAST:event_jtafallasFocusGained

    private void jtfmodeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmodeloFocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jtfmodeloFocusLost

    private void jtafallasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtafallasFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtafallasFocusLost

    private void jtacausasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtacausasFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtacausasFocusGained

    private void jtacausasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtacausasFocusLost
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jtacausasFocusLost

    private void jtaobservacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaobservacionFocusGained
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jtaobservacionFocusGained

    private void jtaobservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaobservacionFocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtaobservacionFocusLost

    private void jbtnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfotoActionPerformed
        // TODO add your handling code here:
        String rutaimagen=null;
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos png & jpg", "png", "jpg");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {                        
                try {
                    rutaimagen = chooser.getSelectedFile().getAbsolutePath();
                    System.out.println("rutaimg"+rutaimagen);
                    File file = new File(rutaimagen);
                    byte[]  fotobys= Files.readAllBytes(file.toPath());
                    reparacion.setFoto(fotobys);
                    
                    
                    Image icono=ImageIO.read(chooser.getSelectedFile()).getScaledInstance
                    (jlblfoto.getWidth(),jlblfoto.getHeight(),Image.SCALE_DEFAULT);
                    jlblfoto.setIcon(new ImageIcon(icono));
                    jlblfoto.updateUI();

//                   validaguardar();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
                }
            }    
    }//GEN-LAST:event_jbtnfotoActionPerformed

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        String codigo;
      
            reparacion.setIdempleado(empleado.getId_empleado());
            reparacion.setIdcliente(cliente.getId_cliente());
            reparacion.setAtendido(empleadosingleton.getNombre().trim().toUpperCase());
            reparacion.setMarca(jtfmarca.getText().trim().toUpperCase());
            reparacion.setModelo(jtfmodelo.getText().trim().toUpperCase());
            reparacion.setFallas(jtafallas.getText().trim().toUpperCase());
            reparacion.setCausas(jtacausas.getText().trim().toUpperCase());
            reparacion.setObservacion(jtaobservacion.getText().trim().toUpperCase());
           // reparacion.setDiagnostico(jtadiagnostico.getText());
            System.out.println(jtfprecio.getText());
            reparacion.setPrecio(Double.parseDouble(jtfprecio.getText()));
//            System.out.println(jXDate.getDate().getTime()+" "+jsphora.getValue()+":"+jspmin.getValue()+":"+"00");
//            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//        jXDate.setFormats(dateFormat); 
//        DateFormat sysDate = new SimpleDateFormat("yyyy");
//        DateFormat sysDate1 = new SimpleDateFormat("MM");
//        DateFormat sysDate2 = new SimpleDateFormat("dd");
//        int año = Integer.parseInt(sysDate.format(jXDate.getDate()).toString()); 
//        int mes = Integer.parseInt(sysDate1.format(jXDate.getDate()).toString());
//        int dia = Integer.parseInt(sysDate2.format(jXDate.getDate()).toString());
//            System.err.println("año"+año);
//            System.err.println("mes"+mes);
//            System.err.println("dia"+dia);
            reparacion.setFechaE(new SimpleDateFormat("yyyy-MM-dd").format(jdpfecha.getDate())+" "+jtfhora.getValue());
//            reparacion.setFechaE(new java.sql.Timestamp(jdpfecha.getDate().getTime()));
//            reparacion.setHora(jtfhora.getValue().toString());
            reparacion.setId_sucural(sucursalsingleton.getId());
            reparacion.setPrecio(Double.parseDouble(jtfprecio.getText().toString()));
            reparacion.setPreciorevision(Double.parseDouble(jtfpreciorevision.getText()));
            reparacion.setDescuento(0.0);
            idreparacion=daoreparacion.insertar(reparacion);
//            JOptionPane.showMessageDialog(null, codigo,"TOME NOTA DEL CODIGO DE REPARACION",JOptionPane.INFORMATION_MESSAGE);
            daoreparacion.imprimir(idreparacion);
            nuevo();                                                                         
            
       
        
        
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfmarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmarcaKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtfmarcaKeyReleased

    private void jtfmodeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmodeloKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtfmodeloKeyReleased

    private void jtafallasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtafallasKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtafallasKeyReleased

    private void jtacausasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtacausasKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtacausasKeyReleased

    private void jtaobservacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaobservacionKeyReleased
        // TODO add your handling code here:
        validaaceptar();
    }//GEN-LAST:event_jtaobservacionKeyReleased

    private void jbtnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclienteActionPerformed
        // TODO add your handling code here:
        JDBuscarCliente Bcliente= new JDBuscarCliente(new java.awt.Frame(), isVisible(),this);
        Bcliente.setVisible(true);
    }//GEN-LAST:event_jbtnclienteActionPerformed

    private void jcbdispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbdispositivoActionPerformed
        // TODO add your handling code here:
//        int index=jcbdispositivo.getSelectedIndex();
//        precio= listprecio.get(index);
//        jtfprecio.setValue(precio.getPrecio());
//        jtfpreciorevision.setValue(precio.getPreciorevision());
        validaaceptar();
    }//GEN-LAST:event_jcbdispositivoActionPerformed

    private void jtfmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmarcaKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayus(jtfmarca);
    }//GEN-LAST:event_jtfmarcaKeyTyped

    private void jtfmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmodeloKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayus(jtfmodelo);
    }//GEN-LAST:event_jtfmodeloKeyTyped

    private void jtafallasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtafallasKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayusTA(jtafallas);
    }//GEN-LAST:event_jtafallasKeyTyped

    private void jtacausasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtacausasKeyTyped
        // TODO add your handling code here:
//        mayus.convertirmayusTA(jtacausas);
    }//GEN-LAST:event_jtacausasKeyTyped

    private void jtaobservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaobservacionKeyTyped
        // TODO add your handling code here:
//         mayus.convertirmayusTA( jtaobservacion);
    }//GEN-LAST:event_jtaobservacionKeyTyped

    private void jtfprecioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfprecioMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfprecioMouseReleased

    private void jtfpreciorevisionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfpreciorevisionMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfpreciorevisionMousePressed

    private void jtfprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfprecioKeyReleased
        // TODO add your handling code here:
         validaaceptar();
    }//GEN-LAST:event_jtfprecioKeyReleased

    private void jtfpreciorevisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfpreciorevisionKeyReleased
        // TODO add your handling code here:
         validaaceptar();
    }//GEN-LAST:event_jtfpreciorevisionKeyReleased

    private void jLabel15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseReleased

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
          posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
         int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel7MouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JButton jbtnbuscartecnico;
    private javax.swing.JButton jbtncliente;
    private javax.swing.JButton jbtnfoto;
    private javax.swing.JComboBox jcbdispositivo;
    private org.jdesktop.swingx.JXDatePicker jdpfecha;
    private javax.swing.JLabel jlblcliente;
    private javax.swing.JLabel jlblfoto;
    private javax.swing.JLabel jlblnombre;
    private javax.swing.JTextArea jtacausas;
    private javax.swing.JTextArea jtafallas;
    private javax.swing.JTextArea jtaobservacion;
    private javax.swing.JFormattedTextField jtfhora;
    private javax.swing.JTextField jtfmarca;
    private javax.swing.JTextField jtfmodelo;
    private javax.swing.JTextField jtfprecio;
    private javax.swing.JTextField jtfpreciorevision;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
}
