/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import DAO.SucursalDAO;
import DAO.VentasDAO;
import Pojos.Cliente;
import Pojos.Sucursal;
import Pojos.Ventas;
import java.awt.Frame;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JIFVentaConsultar extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFVentaConsultar
     */
    VentasDAO daoventa = new VentasDAO();
    Cliente cliente = new Cliente();
   
    Ventas venta;
    Sucursal sucursal;
    SucursalDAO sucursaldao = new SucursalDAO();
    List<Sucursal> listsucursal;
    List<Ventas> listventa;
     int posx;
    int posy;
    public JIFVentaConsultar() {
        initComponents();
//        jbtnimprimirporventa.setEnabled(false);
//        jbtnimprimirtodo.setEnabled(false);
        jdpdesdeV.setDate(new Date());
        jdphastaV.setDate(new Date());
        jlblmensajever.setVisible(false);
        busqueda();
    }
    
//    public void setcliente(Cliente cliente){
//        this.cliente=cliente;
//        jlblcliente.setText(cliente.getNombre_razons());
//        jlblrut.setText(cliente.getRut());
//        listventcli=daoventa.mostrarporcliente(jtablacliente,  cliente.getId_cliente(),jlblmsjcliente);
//        jbtnimprimirtodo.setEnabled(true);
//    }
    
//    public void refrecar(){
//     listventcli=daoventa.mostrarporcliente(jtablacliente,  cliente.getId_cliente(),jlblmsjcliente);
//     jbtnimprimirtodo.setEnabled(true);
//    }
    
    public void busqueda(){
    Runnable runnable = new Runnable() {

        @Override
        public void run() {
//            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       jlblimagencarga.setVisible(true);
       jlblletracarga.setVisible(true);
       if(listsucursal==null){
        listsucursal=sucursaldao.llenarcombo(jcbsucursal);
       }
       
    if(jdpdesdeV.getDate()!=null && jdphastaV.getDate()!=null){
     if(jcbsucursal.getSelectedIndex()==0){
             listventa=daoventa.busquedasensitiva(jtabla,  new Timestamp(jdpdesdeV.getDate().getTime()), new Timestamp(jdphastaV.getDate().getTime())
                     ,  jlbltotal,0,"todo",jtfbuscar.getText().toUpperCase());
        
        }else {
             sucursal=listsucursal.get(jcbsucursal.getSelectedIndex());
               listventa=daoventa.busquedasensitiva(jtabla,  new Timestamp(jdpdesdeV.getDate().getTime()), new Timestamp(jdphastaV.getDate().getTime())
                     ,  jlbltotal,sucursal.getId(),"sucursal",jtfbuscar.getText().toUpperCase());
        
        }
    }
     jlblimagencarga.setVisible(false);
     jlblletracarga.setVisible(false);
     }
    };
    Thread T = new Thread(runnable);
    T.start();
  
    }
    public void ver(){
    int index= jtabla.getSelectedRow();
        if(index>=0){
            jlblmensajever.setVisible(true);
            venta= listventa.get(index);
            JDMostrarVenta mostraV = new JDMostrarVenta(new Frame(), isVisible(),venta.getIdventa());
            jlblmensajever.setVisible(false);
            mostraV.setVisible(true);
        
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione Venta");
        
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jdpdesdeV = new org.jdesktop.swingx.JXDatePicker();
        jdphastaV = new org.jdesktop.swingx.JXDatePicker();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jcbsucursal = new javax.swing.JComboBox();
        jlblletracarga = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfbuscar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jlblimagencarga = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jlbltotal = new javax.swing.JLabel();
        jbtnver = new javax.swing.JButton();
        jlblmensajever = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1254, 588));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(238, 238, 238));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel11.setText("CONSULTAR VENTAS CONCRETADAS");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarblanco.png"))); // NOI18N
        jLabel18.setToolTipText("Cerrar");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel18MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 815, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 11))); // NOI18N

        jdpdesdeV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpdesdeVActionPerformed(evt);
            }
        });

        jdphastaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdphastaVActionPerformed(evt);
            }
        });

        jLabel14.setText("Desde:");

        jLabel15.setText("Hasta:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpdesdeV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdphastaV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jdphastaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jdpdesdeV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));

        jcbsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbsucursalActionPerformed(evt);
            }
        });
        getContentPane().add(jcbsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 122, 405, -1));

        jlblletracarga.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        jlblletracarga.setForeground(new java.awt.Color(0, 0, 0));
        jlblletracarga.setText("Cargando Registros ...");
        getContentPane().add(jlblletracarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 220, -1));

        jLabel16.setText("Sucursal:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 127, -1, -1));

        jtfbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbuscarActionPerformed(evt);
            }
        });
        jtfbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(jtfbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 122, 357, -1));

        jLabel17.setText("Cod. / Cliente / Vendedor:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 124, -1, -1));

        jlblimagencarga.setBackground(new java.awt.Color(255, 255, 255));
        jlblimagencarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblimagencarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ring.gif"))); // NOI18N
        getContentPane().add(jlblimagencarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 870, 210));

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jtabla);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1230, 382));

        jlbltotal.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlbltotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal.setText("* * *");
        getContentPane().add(jlbltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 329, -1));

        jbtnver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/view25px.png"))); // NOI18N
        jbtnver.setText("Ver");
        jbtnver.setToolTipText("Ver detalle");
        jbtnver.setBorderPainted(false);
        jbtnver.setContentAreaFilled(false);
        jbtnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnverActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 90, 22));

        jlblmensajever.setForeground(new java.awt.Color(0, 0, 0));
        jlblmensajever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loading4.gif"))); // NOI18N
        jlblmensajever.setText("Cargando detalle ...");
        getContentPane().add(jlblmensajever, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdpdesdeVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpdesdeVActionPerformed
        // TODO add your handling code here:
        busqueda();
    }//GEN-LAST:event_jdpdesdeVActionPerformed

    private void jdphastaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdphastaVActionPerformed
        // TODO add your handling code here:
        busqueda();
    }//GEN-LAST:event_jdphastaVActionPerformed

    private void jtfbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarKeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jtfbuscarKeyReleased

    private void jcbsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbsucursalActionPerformed
        // TODO add your handling code here:
        busqueda();
    }//GEN-LAST:event_jcbsucursalActionPerformed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
////         int index= jtabla.getSelectedRow();
////        
////        if(index>=0){
////           
////          
////            if(evt.getClickCount()==2){
////                
////             venta= listventa.get(index);
////             JDMotivoExtorno motextorno =new JDMotivoExtorno(new JFrame(),isVisible(),venta,this);
////             motextorno.setVisible(true);
////            }
        
    }//GEN-LAST:event_jtablaMouseReleased

    private void jbtnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnverActionPerformed
        // TODO add your handling code here:
        Runnable runnable = new Runnable() {
            public void run() {
                ver();
            }
        };
        Thread T =new Thread(runnable);
        T.start();
        
        
    }//GEN-LAST:event_jbtnverActionPerformed

    private void jtfbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbuscarActionPerformed
        // TODO add your handling code here:
            busqueda();
    }//GEN-LAST:event_jtfbuscarActionPerformed

    private void jLabel18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel18MouseReleased

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
         int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
         posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_jPanel7MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnver;
    private javax.swing.JComboBox jcbsucursal;
    private org.jdesktop.swingx.JXDatePicker jdpdesdeV;
    private org.jdesktop.swingx.JXDatePicker jdphastaV;
    private javax.swing.JLabel jlblimagencarga;
    private javax.swing.JLabel jlblletracarga;
    private javax.swing.JLabel jlblmensajever;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfbuscar;
    // End of variables declaration//GEN-END:variables
}
