/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesGlobales.Mayusculas;
import DAO.FamiliaDAO;
import DAO.ProductoDAO;
import Pojos.Familia;
import Pojos.Producto;
import Pojos.SucursalSingleton;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author info2017
 */
public class JIProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIProductos
     */
   ProductoDAO daoproducto = new ProductoDAO();
   Boolean editar;
 
   String rutaimagen=null;
   byte[]  fotoB=new byte[0];
   
   Familia familia =new Familia();
   SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
   Mayusculas mayus = new Mayusculas();
   List<Producto> listprod= new ArrayList<>();
    FamiliaDAO daofamilia = new FamiliaDAO();
    List<Familia> listfamilia= new ArrayList<>();
     Producto producto = new Producto();
    public JIProductos() {
        initComponents();
         bloquearjtf( false, false, false,false);
        bloquearjbtn(true, false, false, false, false, true,false,false,false);
        jbtngenerarcodigo.setEnabled(false);
       listprod= daoproducto.mostrarproducto(jtablaproducto,sucursalsingleton.getId());
       listfamilia=daofamilia.llenarcombo(jcbfamilia);
    }
    public void close() {
        jbtncancelar.doClick();

}
    public void bloquearjtf(boolean codigo, boolean descripcion,boolean observacion,boolean precio){
    jtfcodigo.setEnabled(codigo);
    jtfdescripcion.setEnabled(descripcion);
    jtaobservacion.setEnabled(observacion);
    jtfprecioventa.setEnabled(precio);
     
    
    }
    public void bloquearjbtn(boolean nuevo,boolean editar,boolean guardar,boolean eliminar,boolean cancelar,
    boolean salir,boolean foto,boolean codbarra,boolean familia)
    {///,boolean codigo ){
    jbtnnuevo.setEnabled(nuevo);
    jbtneditar.setEnabled(editar);
    jbtnguardar.setEnabled(guardar);
    jbtneliminar.setEnabled(eliminar);
    jbtncancelar.setEnabled(cancelar);
    
    jbtnfoto.setEnabled(foto);
    jbtngeneracodigobarras.setEnabled(codbarra);
    jbtnbuscarfamilia.setEnabled(familia);
   // jbtngenerarcodigo.setEnabled(codigo);
    
    }
     public void limpiarjtf(){
    jtfcodigo.setText("CODIGO");
    jtfdescripcion.setText("DESCRIPCION");
    jtaobservacion.setText("OBSERVACION");
    jtffamilia.setText("FAMILIA");
    jlblImageProducto.setIcon(null);
    jtfprecioventa.setValue(0);
    }
    public void validaguardar(){
        String cod= jtfcodigo.getText().replaceAll("\\s","");
        String jfamilia= jtffamilia.getText().replaceAll("\\s","");
        String desc = jtfdescripcion.getText().replaceAll("\\s","");
    if(!cod.equals("CODIGO") && cod.length() > 4 && !jfamilia.equals("FAMILIA") && !jfamilia.equals("") &&
            Double.parseDouble(jtfprecioventa.getValue().toString()) >=0 && desc.length() > 0
            && !jtfdescripcion.getText().equals("DESCRIPCION")){
        bloquearjbtn(false, false, true,false ,true, true,true,false,true);
    }else {
         bloquearjbtn(true, false, false, false, true, true,true,false,true);
    
    }
    
    }
    public void setfamilia(Familia familia){
    this.familia= familia;
    jtffamilia.setText(familia.getDescripcion());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfbuscarproducto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtablaproducto = new javax.swing.JTable();
        jbtnnuevo = new javax.swing.JButton();
        jbtneditar = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        jbtneliminar = new javax.swing.JButton();
        jbtncancelar = new javax.swing.JButton();
        jtfcodigo = new javax.swing.JTextField();
        jtfdescripcion = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaobservacion = new javax.swing.JTextArea();
        jbtngenerarcodigo = new javax.swing.JButton();
        jtffamilia = new javax.swing.JTextField();
        jbtnbuscarfamilia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jbtnfoto = new javax.swing.JButton();
        jbtngeneracodigobarras = new javax.swing.JButton();
        jlblImageProducto = new javax.swing.JLabel();
        jlblmensajeimpresion = new javax.swing.JLabel();
        jtfprecioventa = new javax.swing.JFormattedTextField();
        jcbfamilia = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Buscar:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jtfbuscarproducto.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jtfbuscarproducto.setToolTipText("");
        jtfbuscarproducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfbuscarproductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfbuscarproductoFocusLost(evt);
            }
        });
        jtfbuscarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbuscarproductoActionPerformed(evt);
            }
        });
        jtfbuscarproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarproductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfbuscarproductoKeyTyped(evt);
            }
        });
        jPanel4.add(jtfbuscarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 220, -1));

        jtablaproducto.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtablaproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaproducto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtablaproducto.getTableHeader().setReorderingAllowed(false);
        jtablaproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaproductoMouseReleased(evt);
            }
        });
        jtablaproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtablaproductoKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jtablaproducto);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 740, 370));

        jbtnnuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbtnnuevo.setText("Nuevo");
        jbtnnuevo.setToolTipText("Nuevo");
        jbtnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnuevoActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 90, -1));

        jbtneditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneditar.setText("Editar");
        jbtneditar.setToolTipText("Editar");
        jbtneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 90, -1));

        jbtnguardar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnguardar.setText("Guardar");
        jbtnguardar.setToolTipText("Guardar");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 90, 20));

        jbtneliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneliminar.setText("Eliminar");
        jbtneliminar.setToolTipText("Eliminar");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 90, -1));

        jbtncancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbtncancelar.setText("Cancelar");
        jbtncancelar.setToolTipText("Cancelar");
        jbtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jbtncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, 90, -1));

        jtfcodigo.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jtfcodigo.setText("CODIGO");
        jtfcodigo.setToolTipText("Codigo");
        jtfcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfcodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfcodigoFocusLost(evt);
            }
        });
        jtfcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfcodigoKeyTyped(evt);
            }
        });
        jPanel4.add(jtfcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 210, -1));

        jtfdescripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 10)); // NOI18N
        jtfdescripcion.setText("DESCRIPCION");
        jtfdescripcion.setToolTipText("Descripcion");
        jtfdescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdescripcionFocusLost(evt);
            }
        });
        jtfdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyTyped(evt);
            }
        });
        jPanel4.add(jtfdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 300, -1));

        jtaobservacion.setColumns(20);
        jtaobservacion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtaobservacion.setRows(5);
        jtaobservacion.setText("OBSERVACIONES");
        jtaobservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtaobservacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtaobservacionFocusLost(evt);
            }
        });
        jtaobservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaobservacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtaobservacionKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(jtaobservacion);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 460, 110));

        jbtngenerarcodigo.setBackground(new java.awt.Color(255, 255, 255));
        jbtngenerarcodigo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jbtngenerarcodigo.setText("GENERAR CODIGO");
        jbtngenerarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngenerarcodigoActionPerformed(evt);
            }
        });
        jPanel4.add(jbtngenerarcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, -1, 20));

        jtffamilia.setFont(new java.awt.Font("Segoe UI Light", 1, 10)); // NOI18N
        jtffamilia.setText("FAMILIA");
        jtffamilia.setEnabled(false);
        jPanel4.add(jtffamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 150, -1));

        jbtnbuscarfamilia.setBackground(new java.awt.Color(255, 255, 255));
        jbtnbuscarfamilia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnbuscarfamilia.setText("...");
        jbtnbuscarfamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscarfamiliaActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnbuscarfamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 250, 50, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Precio Venta:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, 20));

        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnfoto.setBackground(new java.awt.Color(255, 255, 255));
        jbtnfoto.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jbtnfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FOTO.png"))); // NOI18N
        jbtnfoto.setText("Foto Referencial");
        jbtnfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfotoActionPerformed(evt);
            }
        });
        panelNice1.add(jbtnfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 180, 40));

        jbtngeneracodigobarras.setBackground(new java.awt.Color(255, 255, 255));
        jbtngeneracodigobarras.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jbtngeneracodigobarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/codprod.png"))); // NOI18N
        jbtngeneracodigobarras.setText("Generar Cod. Barras");
        jbtngeneracodigobarras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtngeneracodigobarrasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbtngeneracodigobarrasMousePressed(evt);
            }
        });
        jbtngeneracodigobarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngeneracodigobarrasActionPerformed(evt);
            }
        });
        panelNice1.add(jbtngeneracodigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 210, 50));

        jlblImageProducto.setBackground(new java.awt.Color(255, 255, 255));
        jlblImageProducto.setForeground(new java.awt.Color(255, 255, 255));
        jlblImageProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelNice1.add(jlblImageProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 130));

        jlblmensajeimpresion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblmensajeimpresion.setForeground(new java.awt.Color(255, 51, 51));
        panelNice1.add(jlblmensajeimpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 210, 20));

        jPanel4.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 460, 150));

        jtfprecioventa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jPanel4.add(jtfprecioventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 130, -1));

        jcbfamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbfamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbfamiliaActionPerformed(evt);
            }
        });
        jPanel4.add(jcbfamilia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 180, -1));

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("MANTENIMIENTO DE PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1243, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfbuscarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbuscarproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbuscarproductoActionPerformed

    private void jtfbuscarproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarproductoKeyReleased
        // TODO add your handling code here:
        String descrip= jtfbuscarproducto.getText().trim().toUpperCase();
         Familia fam = new Familia();
            fam = listfamilia.get(jcbfamilia.getSelectedIndex());
        if(jcbfamilia.getSelectedIndex()==0){
           
        listprod=daoproducto.busquedasensitivaproducto(jtablaproducto,"TODO", descrip,
                sucursalsingleton.getId(),fam.getIdfamilia());
        
        }else{
         listprod=daoproducto.busquedasensitivaproducto(jtablaproducto,"", descrip,
                sucursalsingleton.getId(),fam.getIdfamilia());
        }
       
    }//GEN-LAST:event_jtfbuscarproductoKeyReleased

    private void jtfbuscarproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarproductoKeyTyped
        // TODO add your handling code here:
       mayus.convertirmayus(jtfbuscarproducto);
    }//GEN-LAST:event_jtfbuscarproductoKeyTyped

    private void jtablaproductoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaproductoMouseReleased
        // TODO add your handling code here:
       
        Producto prodb;
        prodb = listprod.get(jtablaproducto.getSelectedRow());
//        id = Long.parseLong(jtablaproducto.getValueAt(jtablaproducto.getSelectedRow(), 0).toString());
        producto = daoproducto.buscarproducto("ID", prodb.getIdproducto(),sucursalsingleton.getId(),jlblImageProducto,null);    
        jtfcodigo.setText(producto.getCodigo());
        jtfdescripcion.setText(producto.getDescripcion());
        jtaobservacion.setText(producto.getObservacion());
        //jtffamilia.setText(producto.getDireccion());
        jtffamilia.setText(producto.getDescripfamilia());
        familia.setIdfamilia(producto.getIdfamilia());
        fotoB= producto.getFoto();
        jtfprecioventa.setValue(producto.getPrecio());
//        jspmargen.setValue(producto.getMargenG());
        bloquearjbtn(true, true, false, false, false, true,false,true,false);
        jbtngenerarcodigo.setEnabled(false);
    }//GEN-LAST:event_jtablaproductoMouseReleased

    private void jbtnfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfotoActionPerformed
        // TODO add your handling code here:
//          Empleado empleado = new Empleado();
//        System.out.println("idfoto"+id);
//        empleado.setId_empleado(id);
    JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Archivos png & jpg", "png", "jpg");
        chooser.setFileFilter(filter);
        String userHome = System.getProperty( "user.home" );
        chooser.setCurrentDirectory(new File(userHome));
        chooser.setAcceptAllFileFilterUsed(false);
        int retrival = chooser.showOpenDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {                        
                try {
                    rutaimagen = chooser.getSelectedFile().getAbsolutePath();
                    File file = new File(rutaimagen);
                    byte[]  fotobys= Files.readAllBytes(file.toPath());
                    fotoB=fotobys;
                    
                    
                    Image icono=ImageIO.read(chooser.getSelectedFile()).getScaledInstance
                    (jlblImageProducto.getWidth(),jlblImageProducto.getHeight(),Image.SCALE_DEFAULT);
                    jlblImageProducto.setIcon(new ImageIcon(icono));
                    jlblImageProducto.updateUI();

                   validaguardar();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
                }
            }     
    }//GEN-LAST:event_jbtnfotoActionPerformed

    private void jbtngeneracodigobarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngeneracodigobarrasActionPerformed
        // TODO add your handling code here:
//            GenerarCodigoBarras codbarra= new GenerarCodigoBarras();
//
//        String codigo= jtfcodigo.getText().replaceAll("\\s","");
//        codbarra.generarcodigobarras( "E:\\"+codigo+".pdf",codigo );
//        JOptionPane.showMessageDialog(this,"CODIGO GENERADO EXITOSAMENTE");
        Producto prod;
        prod= listprod.get(jtablaproducto.getSelectedRow());
        daoproducto.imprimircodigo(prod.getIdproducto());
         jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtngeneracodigobarrasActionPerformed

    private void jbtnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnuevoActionPerformed
        // TODO add your handling code here:
         bloquearjtf(true, true, true,true);
        bloquearjbtn(true, false, false, false, true, true,true,false,true);
        jbtngenerarcodigo.setEnabled(true);
        limpiarjtf();
        editar=false;

        editar=false;
    }//GEN-LAST:event_jbtnnuevoActionPerformed

    private void jbtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditarActionPerformed
        // TODO add your handling code here:
         bloquearjtf(false, true, true,true);
        editar=true;
        bloquearjbtn(true, false, false, false, true, true,true,false,true);
        jbtngenerarcodigo.setEnabled(true);
    }//GEN-LAST:event_jbtneditarActionPerformed

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        // TODO add your handling code here:
//        Producto producto= new Producto();
        String codigo=jtfcodigo.getText().replaceAll("\\s","");
        String descripcion=jtfdescripcion.getText().trim();
        String observacion=jtaobservacion.getText().trim();
        producto.setIdfamilia(familia.getIdfamilia());
        producto.setCodigo(codigo);
        producto.setDescripcion(descripcion);
        producto.setObservacion(observacion);
        producto.setPrecio(Double.parseDouble(jtfprecioventa.getValue().toString()));
        producto.setFoto(fotoB);
        producto.setId_sucursal(sucursalsingleton.getId());
        
        if (codigo.length()>0 && descripcion.length()>0 && observacion.length()>0
                ){
            if(!codigo.equals("NOMBRES Y APELLIDOS")){
                if(editar==false){
                  boolean valida=daoproducto.duplicado(0, codigo,"GUARDAR");
                   if(valida==true){
                       daoproducto.insertarproducto(producto);
                   }else{
                    JOptionPane.showMessageDialog(null, "EL PRODUCTO YA SE ENCUENTRA REGISTRADO","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
                }    
                 
                }
               
                else{
                    
                   
                    boolean Vvalida=daoproducto.duplicado(producto.getIdproducto(), codigo,"EDITAR");
                 if(Vvalida==true){
                      daoproducto.editarproducto(producto);
                 }else {
                     JOptionPane.showMessageDialog(null, "EL RUT INGRESADO YA SE ENCUENTRA REGISTRADO","SISTEMA",JOptionPane.INFORMATION_MESSAGE);
                 }
                   
                   
                        } 
                
                       
                    
                
                
            }else {
                JOptionPane.showMessageDialog(null, "RELLENE LOS CAMPOS","ERROR",JOptionPane.ERROR_MESSAGE);
            } 
           
        }else {
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS DATOS","ERROR",JOptionPane.ERROR_MESSAGE);
        
        }
        daoproducto.mostrarproducto(jtablaproducto,sucursalsingleton.getId());
        bloquearjbtn(true, false, false, false, false, true,false,false,false);
        jbtngenerarcodigo.setEnabled(false);
        bloquearjtf(false, false, false,false);
        limpiarjtf();
     
    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        // TODO add your handling code here:
        int index= jtablaproducto.getSelectedRow();
        long id = Long.parseLong(jtablaproducto.getValueAt(index, 0).toString());
        if (index<0){
            JOptionPane.showMessageDialog(this, "SELECCIONE PRODUCTO A ELIMINAR EN LA TABLA");
        }else {
            if (JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE ELIMINAR EL PRODUCTO","ELIMINAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                daoproducto.eliminarproducto(id);
                bloquearjtf( false, false, false,false);
                bloquearjbtn(true, false, false, false, false, true,false,false,false);
                jbtngenerarcodigo.setEnabled(false);
                limpiarjtf();
                daoproducto.mostrarproducto(jtablaproducto,sucursalsingleton.getId());
               
            }

        }
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jbtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncancelarActionPerformed
        // TODO add your handling code here:
               int index = jtablaproducto.getSelectedRow();
        if(index>=0){
            jtablaproductoMouseReleased(null);
        } else {
        limpiarjtf();
        }
         bloquearjtf( false, false, false,false);
        bloquearjbtn(true, false, false, false, false, true,false,false,false);
        jbtngenerarcodigo.setEnabled(false);
        
    }//GEN-LAST:event_jbtncancelarActionPerformed

    private void jtfbuscarproductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarproductoFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jtfbuscarproductoFocusGained

    private void jtfbuscarproductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfbuscarproductoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfbuscarproductoFocusLost

    private void jtfcodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcodigoFocusGained
        // TODO add your handling code here:
         if(jtfcodigo.getText().equals("CODIGO")){
            jtfcodigo.setText("");
        
        }
    }//GEN-LAST:event_jtfcodigoFocusGained

    private void jtfcodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfcodigoFocusLost
        // TODO add your handling code here:
         if(jtfcodigo.getText().equals("")){
            jtfcodigo.setText("CODIGO");
        
        }
    }//GEN-LAST:event_jtfcodigoFocusLost

    private void jtfdescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusGained
        // TODO add your handling code here:
         if(jtfdescripcion.getText().equals("DESCRIPCION")){
            jtfdescripcion.setText("");
        
        }
    }//GEN-LAST:event_jtfdescripcionFocusGained

    private void jtfdescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdescripcionFocusLost
        // TODO add your handling code here:
         if(jtfdescripcion.getText().equals("")){
            jtfdescripcion.setText("DESCRIPCION");
        
        }
    }//GEN-LAST:event_jtfdescripcionFocusLost

    private void jtaobservacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaobservacionFocusGained
        // TODO add your handling code here:
         if(jtaobservacion.getText().equals("OBSERVACION")){
            jtaobservacion.setText("");
        
        }
    }//GEN-LAST:event_jtaobservacionFocusGained

    private void jtaobservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaobservacionFocusLost
        // TODO add your handling code here:
         if(jtaobservacion.getText().equals("")){
            jtaobservacion.setText("OBSERVACION");
        
        }
    }//GEN-LAST:event_jtaobservacionFocusLost

    private void jbtnbuscarfamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscarfamiliaActionPerformed
        // TODO add your handling code here:
        
        JDBuscarFamilia bfamilia= new JDBuscarFamilia(new java.awt.Frame(), isVisible(),familia,this);
        
        bfamilia.setVisible(true);
    }//GEN-LAST:event_jbtnbuscarfamiliaActionPerformed

    private void jtfdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfdescripcionKeyReleased

    private void jtaobservacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaobservacionKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtaobservacionKeyReleased

    private void jtablaproductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablaproductoKeyReleased
        // TODO add your handling code here:
        jtablaproductoMouseReleased(null);
    }//GEN-LAST:event_jtablaproductoKeyReleased

    private void jtfcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcodigoKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfcodigoKeyReleased

    private void jbtngenerarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngenerarcodigoActionPerformed
        // TODO add your handling code here:
        daoproducto.generarcodigo(jtfcodigo);
        validaguardar();
        jbtngenerarcodigo.setEnabled(false);
    }//GEN-LAST:event_jbtngenerarcodigoActionPerformed

    private void jtfdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyTyped
        // TODO add your handling code here:
        mayus.convertirmayus(jtfdescripcion);
        validaguardar();
    }//GEN-LAST:event_jtfdescripcionKeyTyped

    private void jtaobservacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaobservacionKeyTyped
        // TODO add your handling code here:
         mayus.convertirmayusTA(jtaobservacion);
    }//GEN-LAST:event_jtaobservacionKeyTyped

    private void jtfcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcodigoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)
                ) {
                evt.consume();
            }
            if (c == '.' && jtfcodigo.getText().contains(".")) {
                evt.consume();
                } 
        
    }//GEN-LAST:event_jtfcodigoKeyTyped

    private void jcbfamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbfamiliaActionPerformed
        // TODO add your handling code here:
        System.out.println("listfamia"+listfamilia.size());
         String descrip= jtfbuscarproducto.getText().toUpperCase();
        if(listfamilia.size()>0){
            Familia fam;
            fam=listfamilia.get(jcbfamilia.getSelectedIndex());
            System.out.println("idfamilia"+fam.getIdfamilia());
            if(jcbfamilia.getSelectedIndex()==0){
             listprod=daoproducto.busquedasensitivaproducto(jtablaproducto,"TODO", descrip,
                sucursalsingleton.getId(),fam.getIdfamilia());
            
            }else {
            listprod=daoproducto.busquedasensitivaproducto(jtablaproducto,"", descrip,
                sucursalsingleton.getId(),fam.getIdfamilia());
            }
             
        
        }
        
    }//GEN-LAST:event_jcbfamiliaActionPerformed

    private void jbtngeneracodigobarrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtngeneracodigobarrasMousePressed
        // TODO add your handling code here:
        jlblmensajeimpresion.setText("Generando ...");
    }//GEN-LAST:event_jbtngeneracodigobarrasMousePressed

    private void jbtngeneracodigobarrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtngeneracodigobarrasMouseExited
        // TODO add your handling code here:
        jlblmensajeimpresion.setText("");
    }//GEN-LAST:event_jbtngeneracodigobarrasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbtnbuscarfamilia;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JButton jbtneditar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JButton jbtnfoto;
    private javax.swing.JButton jbtngeneracodigobarras;
    private javax.swing.JButton jbtngenerarcodigo;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JButton jbtnnuevo;
    private javax.swing.JComboBox jcbfamilia;
    private javax.swing.JLabel jlblImageProducto;
    private javax.swing.JLabel jlblmensajeimpresion;
    private javax.swing.JTable jtablaproducto;
    private javax.swing.JTextArea jtaobservacion;
    private javax.swing.JTextField jtfbuscarproducto;
    private javax.swing.JTextField jtfcodigo;
    private javax.swing.JTextField jtfdescripcion;
    private javax.swing.JTextField jtffamilia;
    private javax.swing.JFormattedTextField jtfprecioventa;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    // End of variables declaration//GEN-END:variables
}
