/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import ClasesGlobales.CifradoMD5;
import ClasesGlobales.LookAndFeel;
import Conexion.Conexion;
import DAO.EmpleadoDAO;
import DAO.SucursalDAO;
import DAO.UsuariosDAO;
import Pojos.EmpleadoSingleton;
import Pojos.Sucursal;
import Pojos.SucursalSingleton;
import Pojos.UsuarioSingleton;
import com.sun.awt.AWTUtilities;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
 
     int posx;
    int posy;
//    Empleado empleado = new Empleado();
    EmpleadoDAO daoempleado = new EmpleadoDAO();
    UsuariosDAO daousuario= new UsuariosDAO();
    SucursalDAO daosucursal= new SucursalDAO();
    EmpleadoSingleton empleadosingleton;
    SucursalSingleton sucursalsingleton = SucursalSingleton.getinstancia();
    
    List<Sucursal> listsucursal= new ArrayList<>();
    LookAndFeel look = new LookAndFeel();
    
    
    public Login() {
        initComponents();
       try {
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoicono.png")).getImage());
            
        } catch (Exception e) {
        }
        
       setLocationRelativeTo(null);
       listsucursal=daosucursal.llenarcombo(jcbsucursal);
       pruebaconexion();
    }
    
    public void pruebaconexion(){
     Conexion conexion= new Conexion();
     conexion.getConnection();
     
     if(conexion.pruebaconexion()==true){
         jlblrpruebaconexion.setText("");
     } else{ 
         jlblrpruebaconexion.setText("No se obtuvo conexion con el servidor pongase en contacto con el administrador del sistema");
         jcbsucursal.setEnabled(false);
         jtfusuario.setEnabled(false);
         jtfclave.setEnabled(false);
         jlblaceptar.setVisible(false);
     }
     conexion.devolverConexionPool();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblrpruebaconexion = new javax.swing.JLabel();
        jtfusuario = new javax.swing.JTextField();
        jtfclave = new javax.swing.JPasswordField();
        jlblcerrar = new javax.swing.JLabel();
        jlblaceptar = new javax.swing.JLabel();
        jcbsucursal = new javax.swing.JComboBox();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblrpruebaconexion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jlblrpruebaconexion.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jlblrpruebaconexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 510, 20));

        jtfusuario.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfusuario.setText("USUARIO");
        jtfusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfusuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfusuarioFocusLost(evt);
            }
        });
        jtfusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtfusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 270, 20));

        jtfclave.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jtfclave.setText("CLAVE");
        jtfclave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfclaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfclaveFocusLost(evt);
            }
        });
        jtfclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfclaveActionPerformed(evt);
            }
        });
        getContentPane().add(jtfclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 270, 20));

        jlblcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlblcerrarMousePressed(evt);
            }
        });
        getContentPane().add(jlblcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 60, 30));

        jlblaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enter.png"))); // NOI18N
        jlblaceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlblaceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlblaceptarMousePressed(evt);
            }
        });
        getContentPane().add(jlblaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 70, -1));

        jcbsucursal.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jcbsucursal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sin conexion" }));
        getContentPane().add(jcbsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login3.png"))); // NOI18N
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMouseDragged(evt);
            }
        });
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
        // TODO add your handling code here:
        
           posy=evt.getY();
        posx=evt.getX();
    }//GEN-LAST:event_fondoMousePressed

    private void fondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseDragged
        // TODO add your handling code here:
          int xp=evt.getXOnScreen() - posx;
        int yp=evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_fondoMouseDragged

    private void jtfusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfusuarioFocusGained
        // TODO add your handling code here:
        if (jtfusuario.getText().equals("USUARIO")){
            jtfusuario.setText("");
        
        }
        
    }//GEN-LAST:event_jtfusuarioFocusGained

    private void jtfusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfusuarioActionPerformed
        // TODO add your handling code here:
        jlblaceptarMousePressed(null);
    }//GEN-LAST:event_jtfusuarioActionPerformed

    private void jtfusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfusuarioFocusLost
        // TODO add your handling code here:
        if(jtfusuario.getText().equals("")){
           jtfusuario.setText("USUARIO");
        }
    }//GEN-LAST:event_jtfusuarioFocusLost

    private void jtfclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfclaveActionPerformed
        // TODO add your handling code here:
        jlblaceptarMousePressed(null);
    }//GEN-LAST:event_jtfclaveActionPerformed

    private void jlblaceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblaceptarMousePressed
        // TODO add your handling code here:
        if((jtfusuario.getText().length()>0 && !jtfusuario.getText().equals("USUARIO")) &&
                (new String(jtfclave.getPassword()).length()>0) && jcbsucursal.getSelectedIndex()>0){
            
            UsuarioSingleton user;
            user = daousuario.validauser(jtfusuario.getText(), CifradoMD5.Cifrado(new String(jtfclave.getPassword())));
            System.out.println("user"+user.getUsuario());
            if(user.getUsuario()!=null){
                
                empleadosingleton = daoempleado.cargarempleadosinfoto("ID", user.getIdempleado());
                System.out.println(listsucursal.get(1));
                sucursalsingleton = sucursalsingleton.setcargarsucursal(listsucursal.get(jcbsucursal.getSelectedIndex()));
                MDIMenu menu = new MDIMenu();
//                menu.cargarImagen();
//                look.setLook(user.getTema(), menu);
                this.dispose();
                /*Se envia el objeto login para regresar en caso de cerrar sesión, y se
                envía el objeto usuario, que contiene toda la información del usuario*/
                menu.setVisible(true);
            }else {
                JOptionPane.showMessageDialog(null, "USUARIO O CLAVE ERRONEOS INTENTE NUEVAMENTE");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Rellena todos los campos.","Error", JOptionPane.ERROR_MESSAGE);
        }      


    }//GEN-LAST:event_jlblaceptarMousePressed

    private void jlblcerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblcerrarMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlblcerrarMousePressed

    private void jtfclaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfclaveFocusGained
        // TODO add your handling code here:
        if(new String(jtfclave.getPassword()).equals("CLAVE")){
            jtfclave.setText("");
        
        
        }
    }//GEN-LAST:event_jtfclaveFocusGained

    private void jtfclaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfclaveFocusLost
        // TODO add your handling code here:
        if(new String(jtfclave.getPassword()).equals("")){
            jtfclave.setText("CLAVE");
        
        
        }
    }//GEN-LAST:event_jtfclaveFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Login login =new Login();
                AWTUtilities.setWindowOpaque(login, false);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox jcbsucursal;
    private javax.swing.JLabel jlblaceptar;
    private javax.swing.JLabel jlblcerrar;
    private javax.swing.JLabel jlblrpruebaconexion;
    private javax.swing.JPasswordField jtfclave;
    private javax.swing.JTextField jtfusuario;
    // End of variables declaration//GEN-END:variables
}
